### ISSUE TITLE
Do Not Invoke Getters Implicitly - Hide it behind explicit UI

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react-devtools#775] opened 2017-06-01 18:58 UTC
Enumerating over the keys of an object [currently invokes all getters on that object](https://github.com/facebook/react-devtools/blob/40f926dfab63051446e9b671c369c703f2e21c67/agent/Bridge.js#L439). Which can cause all kinds of issues. We should use `getOwnPropertyDescriptor` here instead. If it's a getter we should wait to invoke it until explicit told to. Chrome has a little `(...)` UI that you can click to invoke the getter.

That makes it safer to browse around while debugging an issue without having to worry about state changing and therefore changing the thing you're trying to debug.

**Comment by gaearon** [comment] 2017-06-02 14:11
I believe this will be solved by https://github.com/facebook/react-devtools/pull/569.

**Comment by zinoviev** [comment] 2017-06-02 14:52
@sebmarkbage @gaearon Yep, this is how it works now, awaiting for review and merge

**Comment by theREALdebater** [comment] 2018-09-28 15:22
Related question #959

**Comment by bvaughn** [comment] 2019-08-19 23:24
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:24 UTC
Labels: difficulty: medium, enhancement
