### ISSUE TITLE
Started to crash quite recently with a "Uncaught TypeError: Cannot read property 'replace' of null" error

### ISSUE THREAD

**Issue by dperetti** [facebook/react-devtools#1176] opened 2018-10-01 11:43 UTC
This is happening to me in Electron when devtools 3.4.0 open. (UI is "Waiting for roots to load").

<img width="529" alt="screenshot 2018-10-01 at 13 37 05" src="https://user-images.githubusercontent.com/845612/46286510-b734a800-c57f-11e8-9521-37bb0ac82e63.png">
<img width="723" alt="screenshot 2018-10-01 at 13 37 22" src="https://user-images.githubusercontent.com/845612/46286516-bd2a8900-c57f-11e8-8dcb-44efa2928fb5.png">

**Comment by dperetti** [comment] 2018-10-13 19:27
"topsecret", huh ? 😆

**Comment by VladimirMilov** [comment] 2018-10-16 12:16
Same issue here..

**Comment by wufeng87** [comment] 2018-10-23 01:34
Same issue here after I added chrome redux plugin.

**Comment by happier2** [comment] 2018-10-23 05:50
Same issue...

**Comment by andrewbranch** [comment] 2018-10-24 00:48
Got this in the Chrome extension initially after upgrading to react-dom@16.6 from 16.3, but resolved by disabling the extension and re-enabling. ¯\\_(ツ)_/¯

**Comment by Kelin2025** [comment] 2018-10-25 05:01
I had this bug on my macbook but not on windows pc. Then I updated React to 16.6 and got the same bug on win too :(

**Comment by AlexanderArce** [comment] 2018-11-12 10:07
I fixed this issue removing the `electron-react-devtools`. I was using both `electron-react-devtools` and `react-developer-tools`.

**Comment by dolsem** [comment] 2018-12-15 02:39
I am getting the same issue in React Native with React 16.6

**Comment by madcat23** [comment] 2018-12-19 10:20
I had the same issue. I was able to fix it only by deleting the extensions folder. In my case (Windows):
`C:\Users\{USERNAME}\AppData\Roaming\Electron`

Other platforms:
* `$XDG_CONFIG_HOME` or `~/.config` on Linux
* `~/Library/Application Support` on macOS

**Comment by pronebird** [comment] 2019-02-06 12:13
Same error here.

**Comment by Gorhom** [comment] 2019-03-12 08:43
I solved this issue on React Native by updating `react-devtools-core` to `3.6.1`, steps:

1. navigate to `./node_modules/react-native`
2. open package.json and update `react-devtools-core` to `3.6.1`
3. run `yarn install` or `npm install`

it should work 👍

**Comment by bvaughn** [comment] 2019-08-19 23:07
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:07 UTC
