### ISSUE TITLE
React detector detects react but Resct developer tool says no react

### ISSUE THREAD

**Issue by macbursys** [facebook/react-devtools#811] opened 2017-06-12 22:58 UTC
On https://www.hellosign.com/ site React detector extension on chrome detects react & turns blue but React developer tool says no react &doesn't show in chrome debugger.
![react_dev_issue](https://user-images.githubusercontent.com/29124650/27058763-c5be8926-4f98-11e7-804e-fbfebae7abbc.png)

**Comment by bvaughn** [comment] 2017-06-13 15:48
I just tested with Chrome + DevTools 2.3.3 (the latest) and www.hellosign.com doesn't light up for me.

Which DevTools version you're using? I don't actually recognize the icon in your screenshot.

Since version 2.1.5, the icon has looked like this:
![ssscreen-shot-2017-06-13-at-8 45 31-am](https://user-images.githubusercontent.com/29597/27091383-d377f378-5014-11e7-91ed-fc1e8048131b.png)

And before that it looked like this:
![ss-2-screen-shot-2017-06-13-at-8 45 31-am](https://user-images.githubusercontent.com/29597/27091452-fa84531c-5014-11e7-9350-9409be148b60.png)

**Comment by bvaughn** [comment] 2017-06-13 15:49
Ah, I believe you're showing Kent C Dodd's [react-detector](https://chrome.google.com/webstore/detail/react-detector/jaaklebbenondhkanegppccanebkdjlh?hl=en) extension in your screenshot.

**Comment by bvaughn** [comment] 2017-06-13 16:09
Confirmed that react-detector does light up for www.hellosign.com but React DevTools (this project) does not so I'm going to close this issue. Cheers. 😄

**Closed by bvaughn** 2017-06-13 16:09 UTC
