### ISSUE TITLE
Highlight updates issue redux

### ISSUE THREAD

**Issue by BartlomiejLewandowski** [facebook/react-devtools#1354] opened 2019-06-16 20:14 UTC
Apologies if this is a false issue, it looks a bit similar to 
https://github.com/facebook/react-devtools/issues/1023.

I have an app which uses redux to publish state changes. It seems that all my connected components are highlighted to show they are being updated via the highlight updates feature.

This would make sense, so I've run the React Profiler to show me what has actually changed. I've then fixed a single component, which after the changes no longer shows rerenders in the Profiler view, but the updates are still being shown in the UI.

I've uploaded a video to show the error: 
https://drive.google.com/file/d/1hR-oaGQJRNQ3sP11SpZUUbQ6ALVoOorm/view?usp=sharing

When clicking I send a redux event that changes the state, we can see that all of the connected components rerender. The profiler shows a different thing though, both for the Component and the wrapped component with connect.

**Comment by BarthesSimpson** [comment] 2019-06-22 21:51
https://github.com/facebook/react-devtools/issues/1290

**Comment by bvaughn** [comment] 2019-08-19 23:05
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:05 UTC
