### ISSUE TITLE
in Chrome the tab can't show

### ISSUE THREAD

**Issue by lizhangqu** [facebook/react-devtools#289] opened 2015-11-19 15:12 UTC
My Chrome is  46.0.2490.86 m,And the react-devtools is 0.14.5,the React tab can't show in developer mode

**Comment by bentaly** [comment] 2015-11-19 16:48
same here, using rect native, from the emulator or device

**Comment by broderix** [comment] 2015-11-19 17:32
+1, chrome46, osx 10.10

**Comment by mbrock** [comment] 2015-11-19 23:46
see https://github.com/facebook/react-devtools/issues/229

**Comment by roysG** [comment] 2015-11-20 02:08
same

**Comment by MrJadaml** [comment] 2015-11-23 23:41
Also having that issue. I was able to get the tab back by selecting 'Allow Access to file URLs' checkbox in the extension settings, but now the tab just looks like it's stuck connecting and tells me  "interact with the app (just tap the screen) in order to establish the bridge." though still won't establish the connection.

**Comment by jt3k** [comment] 2015-11-27 11:35
me too

**Comment by barock19** [comment] 2015-11-29 02:53
+1

**Comment by narychen** [comment] 2015-11-30 09:16
you guys see this page   http://facebook.github.io/react-native/docs/known-issues.html#content
It says that [It's currently not possible to use the "React" tab in the devtools to inspect app widgets. ]

**Comment by ajwhite** [comment] 2015-12-04 00:57
Damn. Hope that support comes in

**Comment by kassens** [comment] 2015-12-17 00:24
Closing as duplicate of #229.

**Closed by kassens** 2015-12-17 00:24 UTC
