### ISSUE TITLE
Problem of Memory in Firefox 57.0 (64-bit)

### ISSUE THREAD

**Issue by selialkile** [facebook/react-devtools#948] opened 2017-11-28 16:07 UTC
When I started to debug my code, the memory of firefox grow so much and firefox become too slow and need to be restarted.

Env: 
Firefox 57.0 (64-bit) 
Ubuntu 17.10
16GB RAM

**Comment by mattgreenfield** [comment] 2018-02-09 14:53
See https://github.com/facebook/react-devtools/issues/333

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
