### ISSUE TITLE
It shows 'image decode failed' when I add it to chrome extension

### ISSUE THREAD

**Issue by Pandapm** [facebook/react-devtools#880] opened 2017-09-06 02:52 UTC
either Chrome  60.0.3112.113 (64-bit)  or Canary 63.0.3206.0 (64-bit)

![image](https://user-images.githubusercontent.com/9839752/30092297-d5d49b9c-9283-11e7-9f92-a9156fecbe9e.png)

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment] 2018-04-01 20:40
This may be due to umatrix extension interfering with Chrome extension installer functions. In order to fix it, ensure you have the following line in your umatrix permanent rules settings committed:

matrix-off: behind-the-scene true

That will allow Chrome to send the request and bypass any manipulation by umatrix.

**Comment by bvaughn** [comment] 2019-08-19 23:16
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:16 UTC
