### ISSUE TITLE
Detect when file:// access is not enabled

### ISSUE THREAD

**Issue by kassens** [facebook/react-devtools#306] opened 2015-12-22 22:04 UTC
We can check in code if the plugin has access to `file://` URLs and warn if not. We could implement a warning that people have to manually check the box on the `chrome://extensions` page.

see #172

https://developer.chrome.com/extensions/extension#method-isAllowedFileSchemeAccess

**Comment by Bnaya** [comment] 2015-12-24 10:18
+1

**Comment by Tushkiz** [comment] 2017-02-19 10:44
I am talking a look at this.

**Comment by gaearon** [comment] 2017-02-20 20:06
You'll need to use the Chrome shell to test your changes. It's in `shells/chrome`. Try to build it and load it locally to verify your dev environment.

The files in `shells/chrome` are representative of Chrome extensions, so you'd need to find the code where it initializes. You'd likely want to check why it doesn't display the tab when React is missing. This is probably intentional, but we may want to change this to always display the tab. If you change it to always display the tab, then you can make it show a warning when it can't find React on the page, and show a more specific warning when this is because of the file permissions.

Does this help?

**Comment by Tushkiz** [comment] 2017-02-21 04:30
Got my dev environment working, doing those `build.sh` things manually for now (Windows 😩)

**Comment by gaearon** [comment] 2017-02-24 22:33
If you can change it to be cross-platform (e.g. using Node scripts) in a separate PR that would be rad.

**Comment by Tushkiz** [comment] 2017-02-25 15:03
Sure thing.

**Comment by Tushkiz** [comment] 2017-04-25 18:01
hey @gaearon, I have raised a PR for this at #632  It is in progress, just the zip of bundle is remaining.

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
Labels: difficulty: medium, someone is working on this

**Comment by Tushkiz** [comment] 2019-08-20 05:19
Thanks @bvaughn and congratulations on the new release. New dev tools is amazing

**Comment by bvaughn** [comment] 2019-08-20 15:52
:) Thank you!
