### ISSUE TITLE
Hi i am not able to access rect devtools on chrome

### ISSUE THREAD

**Issue by abhaykumar01** [facebook/react-devtools#945] opened 2017-11-22 08:04 UTC

**Comment by abhaykumar01** [comment] 2017-11-22 08:04
const path = require('path');
const webpack = require('webpack');
const { CheckerPlugin } = require('awesome-typescript-loader')

module.exports = {
	devServer:{
		compress: true,
		contentBase: "./src",
		overlay: {
			warnings: true,
			errors: true
		  },
		https: false,
		host: "localhost",
		port: 3000,
		hotOnly:true
	},
	entry:[
		"webpack-hot-middleware/client?reload=true", // Note that it reloads the page if hot module reloading fails
		"./src/app.tsx"
	],
	output:{
		path: path.resolve(__dirname, "dist"),
		filename: 'js/bundle.js'
	},
	resolve: {
		extensions: [".ts", ".tsx", ".js", ".jsx"]
	},
	module: {
		rules: [
			{ test: /\.tsx?$/, loader: "awesome-typescript-loader" }
		  ]
		
	},		
	plugins:[
		new CheckerPlugin()
	],
	watch : true,
	devtool: "cheap-module-eval-source-map"
};

**Comment by hristo-kanchev** [comment] 2018-12-14 11:55
@abhaykumar01 Can you post a codesandbox repro link? Thanks!

**Comment by abhaykumar01** [comment] 2018-12-19 10:30
thanks Man,

But i found solution.

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
