### ISSUE TITLE
Stay on Selected Component After Refreshing

### ISSUE THREAD

**Issue by xiao-vincent** [facebook/react-devtools#992] opened 2018-02-20 22:17 UTC
Is there a way to stay on the selected component after refreshing the browser?

It's a bit tedious to search for the component again after making changes to the code.

**Comment by emil14** [comment] 2018-02-22 13:29
+1

**Comment by ultrox** [comment] 2018-03-09 12:55
I was looking the same thing, its so annoying my filters gets cleared out every single time I refresh.

**Comment by OrDuan** [comment] 2018-07-26 08:18
Big pain point for me too.
Just opened a [PR](https://github.com/facebook/react-devtools/pull/1067)

**Comment by BrentLabasan** [comment] 2019-03-07 18:52
In addition, having whichever props and/or states that were expanded before, continue to be expanded after a page refresh, would be a huge time saver.

This would be such a huge time saver.

**Comment by bvaughn** [comment] 2019-08-19 23:13
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:13 UTC
