### ISSUE TITLE
Refactor keyboard selection code to be unit-testable

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#806] opened 2017-06-09 19:31 UTC
The `skipWrapper` and `getNewSelection` functions have been extremely prone to mistakes.
See https://github.com/facebook/react-devtools/pull/781 and https://github.com/facebook/react-devtools/pull/788.

This is partly because they need to account for nested `Wrapper` components (such as the case with arrays in React Fiber).

We need to figure out a way to make them unit-testable, and actually write a regression suite ensuring keyboard navigation works in all directions from different points of the tree. I’m not sure how to approach it—you’d need to figure out the best way to do it.

**Comment by bvaughn** [comment] 2019-08-19 23:23
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:23 UTC
Labels: difficulty: medium, good first bug
