### ISSUE TITLE
Nested props dont expand in the profiler tab

### ISSUE THREAD

**Issue by httpete-ire** [facebook/react-devtools#1148] opened 2018-09-07 10:18 UTC
Awesome job with the profiler. 

When inspecting the props on the profiler tab any nested objects/arrays dont expand, they do from the elements tab.

[video of the bug](https://streamable.com/6tpzk)

I am happy to have a look at this if you could point me in the right direction 🐼

**Comment by bvaughn** [comment] 2018-09-07 14:09
Sounds like a duplicate of #1116 😄 but yes, if you're interested in taking a look– I'd love it.

Not sure how much of a pointer I can provide, other than to say "start with this component" – https://github.com/facebook/react-devtools/blob/master/plugins/Profiler/views/ProfilerFiberDetailPane.js

**Comment by bvaughn** [comment] 2018-09-07 14:09
PS. Thank you 😄

**Comment by httpete-ire** [comment] 2018-09-07 22:43
@bvaughn so I have taken a brief look into this issue. 

From what I can see the `inspect` prop being passed to `DataView` in the `ProfilerFiberDetailPane` component is an [empty function](https://github.com/facebook/react-devtools/blob/master/plugins/Profiler/views/ProfilerFiberDetailPane.js#L117).

I looked into the `PropsState` component and can see that it is passing the inspect prop that comes from the default [store](https://github.com/facebook/react-devtools/blob/master/frontend/PropState.js#L221).

From what I can see the `ProfilerStore` does not have an inspect method. This is as far as I have got so far with investigating this issue. As this is a new code base to me I'm kind of stuck on where to go from here. Do you think we can add an inspect method to the `ProfilerStore`? It might be quite a bit of work because by the looks of it the default Store contains a map of nodes, `ProfileStore` doesnt.

**Comment by bvaughn** [comment] 2018-09-10 16:13
> From what I can see the inspect prop being passed to DataView in the ProfilerFiberDetailPane component is an empty function.

😆 Oh man, I forgot about doing that "temporarily"

I got curious over the weekend and played around with this a bit too (see #1151) but it only works for the last snapshot in the series 😦

**Comment by bvaughn** [comment] 2019-08-19 23:09
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:09 UTC
Labels: plugin: profiler
