### ISSUE TITLE
[New Devtools] Stuck on "Connecting to react..."

### ISSUE THREAD

**Issue by jfahrenkrug** [facebook/react-devtools#179] opened 2015-09-03 14:23 UTC
I have a React app written in TypeScript and packaged up with webpack. I load it from a file URL (I have allowed the Chrome extension access to file URLs). The React tab shows up but when I open it, it is forever stuck on "Connecting to react...". Any ideas?

I use React 0.13.3 and Chrome 45 on a Mac.

**Comment by jaredly** [comment] 2015-09-03 17:14
Some diagnostics:
- are there any errors in the console?
- when you inspect the devtools (pop them into a new window, and then hit CMD-OPTION-J), are there any errors in that console?

**Comment by jfahrenkrug** [comment] 2015-09-03 19:40
Thanks for your help, Jared. There are no errors in the app's console, but the dev-tools console reports 

    /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

and then

    "failed to connect"
        (anonymous function)	@	panel.js:1165

Any idea?

**Comment by jaredly** [comment] 2015-09-03 21:10
hmmmm that warning certainly couldn't come from this.
does it work for other pages? like https://facebook.github.io/react/

**Comment by jfahrenkrug** [comment] 2015-09-03 21:21
Yes, it works fine for other pages. Is there something special I have to do to my React app so that the dev-tools can connect to it?

**Comment by jaredly** [comment] 2015-09-03 21:32
Nope, shouldn't be. @spicyj you opened an issue that it's not working on
any file urls anymore?

**Comment by spicyj** [comment] 2015-09-03 21:33
Yes, #172. Chrome Web Store doesn't allow listing file URLs in the permissions, but it worked fine with the old tools which didn't list any permissions in the manifest.

**Comment by Volodymyr128** [comment] 2015-09-04 10:18
Had the same problem ('Connectiong to react...') on React 0.12.2, Chrome  44.0.2403.157 m. 
Then I noticed I forgot to lunch `npm run build` % 'npm start' which looks like:
`"start": "watchify -o js/bundle.js -v -d js/app.js",`
`"build": "browserify . -t [envify --NODE_ENV production] | uglifyjs -cm > js/bundle.min.js"`
Hope that may be helpful

**Comment by brennanerbz** [comment] 2015-09-05 19:22
Same issue when packaged with Webpack.

**Comment by acamari** [comment] 2015-09-09 23:34
Hi to all:

I think this is completely isolated to file://, I can reproduce this problem 100% when
using file:// and never when using http://; I'm using this project that requires no building:

```
#!/bin/sh

#-----------------------
cat > package.json <<END
{
  "name": "debugreactdevtools",
  "dependencies": {
    "react": "^0.13.3"
  }
}
END

#-----------------------
cat > index.html <<END
<!doctype html><html><head></head><body><div id="helloworld"></div><script src="node_modules/react/dist/react.js"></script><script src="js/example.js"></script></body></html>
END

#-----------------------
cat > js/example.js <<END
var HelloMessage = React.createClass({displayName: "HelloMessage",
  render: function() {
    return React.createElement("div", null, "Hello ", this.props.name);
  }
});

React.render(React.createElement(HelloMessage, {name: "John"}), document.getElementById("helloworld"));
END

#-----------------------
npm install react
# requires no build process
chrome index.html
```

I'm using react-0.13.3; 

$ chrome --version;
Chromium 40.0.2214.115 
$ uname -a
OpenBSD maetel.00z.us 5.7 GENERIC.MP#881 amd64
$ 

chrome -> extensions -> react developer tools -> background page shows the following
error: 

```
Unchecked runtime.lastError while running tabs.executeScript: Cannot access contents of url "file:///home/acamari/src/me/www/lab/debugreactdevtools/index.html". Extension manifest must request permission to access this host.
    at installContentScript (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js:91:16)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js:67:6

handleResponse              extensions::sendRequest:82
```

(also shows log from previous tests on other bigger projects)
![img](http://i.imgur.com/86aBFa6.png?1)

**Comment by spicyj** [comment] 2015-09-09 23:36
Closing in favor of #172 then; if anyone can repro with non-file URLs, please open a new issue.

**Closed by spicyj** 2015-09-09 23:36 UTC
