### ISSUE TITLE
Cannot read property 'displayName' of undefined

### ISSUE THREAD

**Issue by Dolinskaya** [facebook/react-devtools#1168] opened 2018-09-25 09:24 UTC
Hi guys! I upgrade react-devtools to 3.4.0 version and catch an error:

**Cannot read property 'displayName' of undefined in backend.js** 
![image](https://user-images.githubusercontent.com/20880768/46005203-6b848900-c0bd-11e8-9253-bd8a682aa62b.png)
Before 3.4.0 I had 3.3.2 and it was ok.
So, I can't use tab react-devtools, because that have waiting status:

**Waiting for roots to load...**

Browser: Ya.Browser v 18.9.0.3363 (64-bit)

**Comment by zebogen** [comment] 2018-09-25 21:32
I observed this as well when rendering React Context elements with React 16.3.0. It works properly with React 16.3.1 and up.

Looks like a prefix was added to the `context` internal property on ReactContext elements in the 16.3.1 release: https://github.com/facebook/react/pull/12501

**Comment by benwiley4000** [comment] 2018-09-30 03:44
Repro:
```jsx
const MyContext = React.createContext();
ReactDOM.render(
  <MyContext.Provider />,
  document.getElementById('container')
);
```

Version: 3.4.0 (september 20)
Google Chrome: 67.0.3396.62 (Official Build) (64-bit)
OS: Linux (elementary 4.13.0-43-generic)

Here's the line where we hit a snag: https://github.com/facebook/react-devtools/blob/69d137c7feb95c1559ffe54045d518fb86e19e05/backend/attachRendererFiber.js#L272

Stack trace:
```
backend.js:9969 Uncaught TypeError: Cannot read property 'displayName' of undefined
    at getDataFiber (backend.js:9969)
    at enqueueMount (backend.js:10137)
    at mountFiber (backend.js:10225)
    at backend.js:10285
    at Set.forEach (<anonymous>)
    at Object.walkTree (backend.js:10283)
    at backend.js:8534
    at <anonymous>:52:32
    at Array.map (<anonymous>)
    at Object.emit (<anonymous>:51:66)
getDataFiber @ backend.js:9969
enqueueMount @ backend.js:10137
mountFiber @ backend.js:10225
(anonymous) @ backend.js:10285
walkTree @ backend.js:10283
(anonymous) @ backend.js:8534
(anonymous) @ VM79:52
emit @ VM79:51
setupBackend @ backend.js:8621
module.exports @ backend.js:8567
(anonymous) @ backend.js:116
g @ backend.js:981
EventEmitter.emit @ backend.js:894
(anonymous) @ backend.js:302
(anonymous) @ backend.js:7619
(anonymous) @ backend.js:7618
_handleMessage @ backend.js:7611
listener @ backend.js:92
postMessage (async)
handleMessageFromDevtools @ contentScript.js:18
EventImpl.dispatchToListener @ VM68 extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ VM74 extensions::utils:138
EventImpl.dispatch_ @ VM68 extensions::event_bindings:387
EventImpl.dispatch @ VM68 extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ VM74 extensions::utils:138
dispatchOnMessage @ VM75 extensions::messaging:392
```

**Comment by benwiley4000** [comment] 2018-09-30 04:10
Opened a PR to fix: #1175.

**Comment by Albert-Gao** [comment] 2018-10-25 02:37
I have this issue too. And strange enough, it works on FF while not on Chrome.

**Comment by fillipvt** [comment] 2018-10-25 16:16
Just got this problem too. After updating to react@16.6.0, react-dom@16.6.0 got error at backend.js line 9159

```
backend.js:9159 Uncaught TypeError: Cannot read property 'displayName' of null
    at getDisplayName (backend.js:9159)
    at getDataFiber (backend.js:9888)
    at enqueueMount (backend.js:10158)
    at mountFiber (backend.js:10246)
    at backend.js:10306
    at Set.forEach (<anonymous>)
    at Object.walkTree (backend.js:10304)
    at backend.js:8534
    at <anonymous>:52:32
    at Array.map (<anonymous>)
```

This is the part of `backend.js` where the problem occurs:

```
// The displayName property is not guaranteed to be a string.
// It's only safe to use for our purposes if it's a string.
// github.com/facebook/react-devtools/issues/803
if (typeof type.displayName === 'string') {
  displayName = type.displayName;
}

if (!displayName) {
  displayName = type.name || fallbackName;
}
```

Just here to chime in, if there's anything I can do I'd be glad to help.

**Comment by dbryantm** [comment] 2018-10-25 17:18
I just added #1195. Only way I could fix it is to rollback to react@16.5.2 and react-dom@16.5.2.

**Comment by cdaz5** [comment] 2018-11-09 14:51
For what its worth I had the same issue, turns out I had to restart my chrome as the react dev tools were version 3.4.0 .. once I restarted the dev tools were upgraded to 3.4.2 and the error went away... hope this helps!!

**Comment by cdaz5** [comment] 2018-11-09 16:34
nice @dbryantm! I totally missed your comment above! Dang, wish I would have seen it before lol could have saved me some time.

**Comment by vramana** [comment] 2018-11-15 08:19
Seems to be fixed in 16.6.3

**Comment by tannera** [comment] 2018-11-15 09:31
Getting this issue after upgrading to react-native 0.57.5 and React 16.6.3

**Comment by blksheep93** [comment] 2018-12-05 19:30
Getting 'Cannot read property 'displayName' of null. Using React DevTools v. 3.4.3., React v. 16.6.3, React-Dom. Gonna try rolling back to 16.5.2 and see what happens.

**Comment by blksheep93** [comment] 2018-12-05 20:18
Nah still happening.

**Comment by hristo-kanchev** [comment] 2018-12-09 10:38
@blksheep93 Can't seem to reproduce this.

Can you post a repro snippet (or codesandbox link)?

Thanks!

**Comment by blksheep93** [comment] 2018-12-17 02:47
Sorry, but I've never used codesandbox before, or else I'd set up a link for you. All the research I've done to fox this suggests that the problem is based around the consumer.

Repro:

RDT Version: 3.4.3
Chrome Version: 71.0.3578.98 
OS: Mac mojave version 10.14.2


Here goes first stack trace
```
> Uncaught TypeError: Cannot read property 'displayName' of null
>     at getDisplayName (backend.js:9159)
>     at getDataFiber (backend.js:9888)
>     at enqueueMount (backend.js:10158)
>     at mountFiber (backend.js:10246)
>     at backend.js:10306
>     at Set.forEach (<anonymous>)
>     at Object.walkTree (backend.js:10304)
>     at backend.js:8534
>     at <anonymous>:52:32
>     at Array.map (<anonymous>)
```


and the snippet it's pointing to:
```
 // The displayName property is not guaranteed to be a string.
	  // It's only safe to use for our purposes if it's a string.
	  // github.com/facebook/react-devtools/issues/803
	  if (typeof type.displayName === 'string') {
	    displayName = type.displayName;
```

then the second error in the stack trace

```
Warning: React DevTools encountered an error: TypeError: Cannot read property 'displayName' of null
warningWithoutStack | @ | react-dom.development.js:506
-- | -- | --
  | (anonymous) | @ | react-dom.development.js:9577
  | onCommitRoot | @ | react-dom.development.js:9625
  | commitRoot | @ | react-dom.development.js:17493
  | completeRoot | @ | react-dom.development.js:18912
  | performWorkOnRoot | @ | react-dom.development.js:18841
  | performWork | @ | react-dom.development.js:18749
  | performSyncWork | @ | react-dom.development.js:18723
  | requestWork | @ | react-dom.development.js:18592
  | scheduleWork | @ | react-dom.development.js:18401
  | enqueueSetState | @ | react-dom.development.js:12313
  | module.exports../node_modules/react/cjs/react.development.js.Component.setState | @ | react.development.js:372
  | setTimeout | @ | prices.jsx:45
  | setTimeout (async) |   |  
  | networkRequest | @ | prices.jsx:43
  | networkRequest | @ | react-hot-loader.development.js:587
  | componentDidMount | @ | prices.jsx:33
  | componentDidMount | @ | react-hot-loader.development.js:577
  | commitLifeCycles | @ | react-dom.development.js:15961
  | commitAllLifeCycles | @ | react-dom.development.js:17262
  | callCallback | @ | react-dom.development.js:149
  | invokeGuardedCallbackDev | @ | react-dom.development.js:199
  | invokeGuardedCallback | @ | react-dom.development.js:256
  | commitRoot | @ | react-dom.development.js:17458
  | completeRoot | @ | react-dom.development.js:18912
  | performWorkOnRoot | @ | react-dom.development.js:18841
  | performWork | @ | react-dom.development.js:18749
  | performSyncWork | @ | react-dom.development.js:18723
  | requestWork | @ | react-dom.development.js:18592
  | scheduleWork | @ | react-dom.development.js:18401
  | scheduleRootUpdate | @ | react-dom.development.js:19069
  | updateContainerAtExpirationTime | @ | react-dom.development.js:19097
  | updateContainer | @ | react-dom.development.js:19154
  | module.exports../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render | @ | react-dom.development.js:19416
  | (anonymous) | @ | react-dom.development.js:19556
  | unbatchedUpdates | @ | react-dom.development.js:18952
  | legacyRenderSubtreeIntoContainer | @ | react-dom.development.js:19552
  | render | @ | react-dom.development.js:19613
  | (anonymous) | @ | index.js:10
  | ./app/index.js | @ | renderer.dev.js:3503
  | __webpack_require__ | @ | bootstrap:724
  | fn | @ | bootstrap:101
  | 0 | @ | fetch.js:516
  | __webpack_require__ | @ | bootstrap:724
  | module.exports../app/Routes.js.Object.defineProperty.value | @ | bootstrap:791
  | (anonymous)
```

and the code its referring to ( @prices.jsx)

```
render() {
    return (
      <Provider value={this.state.data} >
        {this.state.loading ? "Loading..." : this.props.children}
      </Provider>
    )
  }
```

**Comment by matchu** [comment] 2018-12-20 01:45
@hristo-kanchev @vramana: Does this repro case work for y'all? https://github.com/matchu/react-devtools-context-bug-repro

**Comment by vramana** [comment] 2018-12-20 05:53
@matchu Works I think. I'll check later.

**Comment by bvaughn** [comment] 2019-01-03 19:20
To clarify: React 16.3.0 used `context` and 16.3.1+ use  `_context`.

A repro case can be found here: https://unpkg.com/react@16.3.0/cjs/react.development.js

**Closed** 2019-01-03 19:45 UTC
