### ISSUE TITLE
Support for extension

### ISSUE THREAD

**Issue by ar7casper** [facebook/react-devtools#298] opened 2015-12-16 12:02 UTC
Hi, 

I'm developing an extension using react and I just read that you don't support extensions. 
Would love to know why and if there's anything i can contribute in order for that to happen.

Thanks.

**Comment by ngyikp** [comment] 2016-01-11 06:39
Most likely duplicate of https://github.com/facebook/react-devtools/issues/173

**Comment by spicyj** [comment] 2016-01-11 07:11
Yeah.

**Closed by spicyj** 2016-01-11 07:11 UTC

**Comment by ar7casper** [comment] 2016-01-11 15:04
Hi Ben,

Not sure if it's the same problem, he's developing a popup and I'm building
a web-based extension app.

Never mind, no matter how you call it, I'd love to help you out - please
let me know what / where I should do? where should I begin, just gimme a
hint and i'll try to create some relevant pull requests :)

BR,
Alex.

Alex

**Comment by ngyikp** [comment] 2016-01-12 02:09
If you're building a [Chrome app](https://developer.chrome.com/apps/about_apps) or just opening a new tab to `chrome-extension://`, then I got a workaround for you: https://github.com/facebook/react-devtools/issues/91
