### ISSUE TITLE
Extension server error: Inspector protocol error: Object reference chain is too long

### ISSUE THREAD

**Issue by waldi** [facebook/react-devtools#1360] opened 2019-07-09 14:28 UTC
Hi,
My react-devtools on chrome are crashing in our application. The application is quite big and complex and I unfortunately don't really know how I can reproduce it.
We have a navigation tree in our application and if i right-click -> inspect one of the items and go to react-tools it works. If I then right click my item above and inspect it, once I go to react-tools it crashes and gives me this output in the react-devtools-console: 
```
shell.js:8066 Main._createAppUI: 21.22998046875ms
shell.js:8066 Main._showAppUI: 80.9140625ms
shell.js:8066 Main._initializeTarget: 10.090087890625ms
shell.js:8066 Main._lateInitialization: 6.494873046875ms
shell.js:5197 Object reference chain is too long
_evaluateGlobal @ shell.js:5197
shell.js:7963 Extension server error: Inspector protocol error: Object reference chain is too long
makeStatus @ shell.js:7963
panel.js:formatted:14716 TypeError: Cannot read property 'get' of undefined
    at t.value (panel.js:formatted:29231)
    at panel.js:formatted:18654
    at Object.props (panel.js:formatted:18656)
    at r.value (panel.js:formatted:374)
    at Ri (panel.js:formatted:14256)
    at Mi (panel.js:formatted:14246)
    at Bi (panel.js:formatted:14453)
    at Sa (panel.js:formatted:15532)
    at Ea (panel.js:formatted:15555)
    at sl (panel.js:formatted:15934)
Vi @ panel.js:formatted:14716
panel.js:formatted:15908 Uncaught TypeError: Cannot read property 'get' of undefined
    at t.value (panel.js:formatted:29231)
    at panel.js:formatted:18654
    at Object.props (panel.js:formatted:18656)
    at r.value (panel.js:formatted:374)
    at Ri (panel.js:formatted:14256)
    at Mi (panel.js:formatted:14246)
    at Bi (panel.js:formatted:14453)
    at Sa (panel.js:formatted:15532)
    at Ea (panel.js:formatted:15555)
    at sl (panel.js:formatted:15934)
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
panel.js:3 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object._dispatch (<anonymous>:11:12)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
panel.js:3 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object.dispatchShowEvent [as _customDispatch] (<anonymous>:26:6)
    at Object._dispatch (<anonymous>:10:22)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
shell.js:5197 Object reference chain is too long
_evaluateGlobal @ shell.js:5197
shell.js:7963 Extension server error: Inspector protocol error: Object reference chain is too long
makeStatus @ shell.js:7963
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
panel.js:3 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object._dispatch (<anonymous>:11:12)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
panel.js:3 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object.dispatchShowEvent [as _customDispatch] (<anonymous>:26:6)
    at Object._dispatch (<anonymous>:10:22)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
shell.js:5197 Object reference chain is too long
_evaluateGlobal @ shell.js:5197
shell.js:7963 Extension server error: Inspector protocol error: Object reference chain is too long
makeStatus @ shell.js:7963
panel.js:3 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object._dispatch (<anonymous>:11:12)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
panel.js:3 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object.dispatchShowEvent [as _customDispatch] (<anonymous>:26:6)
    at Object._dispatch (<anonymous>:10:22)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
shell.js:5197 Object reference chain is too long
_evaluateGlobal @ shell.js:5197
shell.js:7963 Extension server error: Inspector protocol error: Object reference chain is too long
makeStatus @ shell.js:7963
main.js:1 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object._dispatch (<anonymous>:11:12)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
send @ panel.js:3
value @ panel.js:28
value @ panel.js:3
(anonymous) @ main.js:1
_fire @ VM15:9
_dispatch @ VM15:11
_onMessage @ VM15:71
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
send @ panel.js:formatted:9110
value @ panel.js:formatted:29865
value @ panel.js:formatted:29844
main.js:1 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object.dispatchShowEvent [as _customDispatch] (<anonymous>:26:6)
    at Object._dispatch (<anonymous>:10:22)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
send @ panel.js:3
value @ panel.js:28
value @ panel.js:3
(anonymous) @ main.js:1
_fire @ VM15:9
dispatchShowEvent @ VM15:26
_dispatch @ VM15:10
_onMessage @ VM15:71
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
send @ panel.js:formatted:9110
value @ panel.js:formatted:29865
value @ panel.js:formatted:29844
shell.js:5197 Object reference chain is too long
_evaluateGlobal @ shell.js:5197
shell.js:7963 Extension server error: Inspector protocol error: Object reference chain is too long
makeStatus @ shell.js:7963
callback @ shell.js:7873
onEvaluate @ shell.js:7960
main.js:1 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object._dispatch (<anonymous>:11:12)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
send @ panel.js:3
value @ panel.js:28
value @ panel.js:3
(anonymous) @ main.js:1
_fire @ VM15:9
_dispatch @ VM15:11
_onMessage @ VM15:71
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
send @ panel.js:formatted:9110
value @ panel.js:formatted:29865
value @ panel.js:formatted:29844
main.js:1 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object.dispatchShowEvent [as _customDispatch] (<anonymous>:26:6)
    at Object._dispatch (<anonymous>:10:22)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
send @ panel.js:3
value @ panel.js:28
value @ panel.js:3
(anonymous) @ main.js:1
_fire @ VM15:9
dispatchShowEvent @ VM15:26
_dispatch @ VM15:10
_onMessage @ VM15:71
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
send @ panel.js:formatted:9110
value @ panel.js:formatted:29865
value @ panel.js:formatted:29844
shell.js:5197 Object reference chain is too long
_evaluateGlobal @ shell.js:5197
shell.js:7963 Extension server error: Inspector protocol error: Object reference chain is too long
makeStatus @ shell.js:7963
callback @ shell.js:7873
onEvaluate @ shell.js:7960
panel.js:3 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object._dispatch (<anonymous>:11:12)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
panel.js:3 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object.dispatchShowEvent [as _customDispatch] (<anonymous>:26:6)
    at Object._dispatch (<anonymous>:10:22)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
shell.js:5197 Object reference chain is too long
_evaluateGlobal @ shell.js:5197
shell.js:7963 Extension server error: Inspector protocol error: Object reference chain is too long
makeStatus @ shell.js:7963
panel.js:3 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object._dispatch (<anonymous>:11:12)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
panel.js:3 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object.dispatchShowEvent [as _customDispatch] (<anonymous>:26:6)
    at Object._dispatch (<anonymous>:10:22)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
shell.js:5197 Object reference chain is too long
_evaluateGlobal @ shell.js:5197
shell.js:7963 Extension server error: Inspector protocol error: Object reference chain is too long
makeStatus @ shell.js:7963
panel.js:3 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object._dispatch (<anonymous>:11:12)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
panel.js:3 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:3)
    at e.value (panel.js:28)
    at t.value (panel.js:3)
    at main.js:1
    at Object._fire (<anonymous>:9:14)
    at Object.dispatchShowEvent [as _customDispatch] (<anonymous>:26:6)
    at Object._dispatch (<anonymous>:10:22)
    at ExtensionServerClient._onMessage (<anonymous>:71:9)
panel.js:formatted:9110 Uncaught Error: Attempting to use a disconnected port object
    at Object.send (panel.js:formatted:9110)
    at e.value (panel.js:formatted:29865)
    at e.value (panel.js:formatted:29844)
```

I maybe suspect that it might have something to do with our react-dom being really large.

I made a screen-recording if it helps: https://www.youtube.com/watch?v=S3SNtKBbRjo

**Comment by tranlehaiquan** [comment] 2019-07-20 05:41
I got same issue : |

**Comment by cholanmadala** [comment] 2019-08-08 09:21
I am facing the same issue. Does anyone know how to fix it? 
I am using chrome - 76.0.3809.100 on Mac. I also allowed access to file URLs. 
Thanks.

**Comment by bvaughn** [comment] 2019-08-19 23:04
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:04 UTC
