### ISSUE TITLE
React Developer Tools not showing

### ISSUE THREAD

**Issue by pm0355** [facebook/react-devtools#942] opened 2017-11-15 08:18 UTC
After installing react developer tools and rect-detector, the react tab does not show in the developer tools (cmd+option+j) when visiting sites built with react (hellosign.com). Navigating to react sites shows message, "This page doesn’t appear to be using React. If this seems wrong, follow the troubleshooting instructions," and no highlighted icon. Both extensions are enabled and "Allow access to file URLs" boxes are checked. Screenshots and versions listed below.

![screen shot 2017-11-15 at 3 25 41 am](https://user-images.githubusercontent.com/7031539/32825626-a47f3608-c9b3-11e7-854e-1f0fb617bc15.png)
![screen shot 2017-11-15 at 3 26 22 am](https://user-images.githubusercontent.com/7031539/32825635-aa07f56a-c9b3-11e7-97dd-aeb4df39dd01.png)

OS: OSX 10.12.6
Browser: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
Extension: react developer tools Version 2.5.2
Extension: deact-detector Version 1.3

**Comment by jacdebug** [comment] 2017-11-20 17:43
Hi @pm0355,

I randomly landed here !! had a quick look on this here is my thoughts.

Are you sure this site homepage built on React ? I found on homepage React is not loaded, only some third party sites are loading it.

But their app is built on React and if you go to login page you can see the react devtools is showing.

Also please be aware that there are ways to hide react dev tools from showing, for more info on that,
https://stackoverflow.com/questions/42196819/disable-hide-download-the-react-devtools

Hope this helps.

**Comment by ngyikp** [comment] 2017-11-20 17:55
Duplicate of https://github.com/facebook/react-devtools/issues/603 https://github.com/facebook/react-devtools/issues/727 https://github.com/facebook/react-devtools/issues/811

www.hellosign.com does not use React for their homepage marketing content. However, there is a third-party widget (ZenDesk) that uses it, some React detector extensions may identify it.

React Devtools should correctly identify https://app.hellosign.com

**Closed** 2017-12-12 16:49 UTC
