### ISSUE TITLE
Device toolbar Chrome keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by hamlim** [facebook/react-devtools#890] opened 2017-09-14 11:32 UTC
Inside chrome devtools you can enable/disable the device toolbar in other panels by doing `CMD + Shift + m` on a mac. However when you are active in the React devtools this keyboard shortcut doesn't seem to work.

Quick user fix is to enable/switch to the console then enter the shortcut or change panels and enter the shortcut.

I haven't been able to extensively test this on different versions, however I am able to replicate this issue on Chrome `v63.0.3215.0` and React devtools `v2.5.0`.

**Comment by juanruizcasas** [comment] 2017-09-14 11:38
Ok

**Comment by hamlim** [comment] 2017-09-15 23:50
Is there anything else I can do to help provide information about the issue?
Is this expected?
Unsure as to what your response means here @juanruizcasas.

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
