### ISSUE TITLE
Consider using SVG for right-/down-arrows that expand/collapse elements

### ISSUE THREAD

**Issue by p-himik** [facebook/react-devtools#1353] opened 2019-06-15 09:43 UTC
Right now, the project uses plain symbols and relies on the browser for correct rendering. The issue is that the rendering depends also on the underlying OS and on the set of available fonts.
Here's how it looks on my system after some update:
![image](https://user-images.githubusercontent.com/4410314/59549747-e69f0f80-8f6a-11e9-8129-9788a3f794cc.png)
As you can see, the down arrow looks normal (but still a bit uglier than the icons used by the default Elements tab IMO) but the right arrow is a mess.
Relying on SVG would make the appearance independent on the underlying system configuration.

**Comment by bvaughn** [comment] 2019-08-19 23:05
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:05 UTC
