### ISSUE TITLE
[Bug]: Select a React element in page Button

### ISSUE THREAD

**Issue by mohamed-seada-1994** [facebook/react-devtools#910] opened 2017-10-08 19:31 UTC
I have experienced a bug in **Select a React element in page _Button_**.
When i click on this button and close chrome developing tools without selecting any element, the selecting hover keep in the page even when selecting any element or open developing tools again!
![2017-10-08_21-28-26](https://user-images.githubusercontent.com/27208846/31320142-c232cf2c-ac6f-11e7-8171-9507db2c1f08.gif)

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
