### ISSUE TITLE
[Proposal] Display/Audit Suspense caches

### ISSUE THREAD

**Issue by sw-yx** [facebook/react-devtools#1141] opened 2018-09-01 03:44 UTC
basically this would be a new tab in the devtools displaying what's inside the caches, giving the author control over key-based invalidation for easier testing and debugging. I'm sure there are more needs we don't even know about yet, but generally the idea is to have a cache-library-agnostic way to hook into caches (so that hopefully we don't all have to install a million other chrome extensions, but also take advantage of unique knowledge about Placeholders that the React Devtools should own). 

There's a possibility that every cache library will want to implement their own devtools but that feels duplicative and it's likely to be a hurdle to smaller teams wanting to try writing cache libraries. I feel like the best place for this is with react-devtools, but reasonable people might disagree. Anyway, just raising the idea.

Relevant code:
- pomber/hitchcock: https://github.com/pomber/hitchcock
- suspense fixture: https://github.com/facebook/react/tree/master/fixtures/unstable-async/suspense

**Comment by bvaughn** [comment] 2019-08-19 23:09
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:09 UTC

**Comment by swyxio** [comment] 2019-08-20 16:15
sad!

**Comment by bvaughn** [comment] 2019-08-20 16:17
You would be 😋
