### ISSUE TITLE
Detect duplicate React and show a different message

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#700] opened 2017-05-08 18:39 UTC
It would be cool if, in addition to DEV mode detection, we could detect when there are two instances of ReactDOM on the page.

This issue mentions how we could detect it: https://github.com/facebook/react-devtools/issues/692.

One thing to keep in mind is it's valid to have two different renderers (e.g. ReactDOM + ReactART), but not two instances of one renderer. Not sure if there's an easy way to tell those cases apart, but we can make changes to React if necessary to support that.

**Comment by chisler** [comment] 2017-05-09 13:24
I'd be happy to try to fix it!

**Comment by gaearon** [comment] 2017-05-09 13:47
👍

**Comment by chisler** [comment] 2017-05-10 20:41
Hi! This is my first open source contribution. I log current status of the issue.

1. Detecting several renderers is simple.
1. Guessing renderer type by the object is not, at least for now. 

However, I found only 1 custom renderer that explicitly fires `.inject` => may interfere dumb checking `hook._renderers.length > 1`. 

<details>
  <summary>Duplicate React among A-C <a href="https://github.com/facebook/react/wiki/sites-using-react">sites-using-react</a>, found with extension
</summary>

- https://www.astenonline.com/
- http://www.arte.tv/en/
- https://www.conciergeauctions.com/
- https://clashofclans.com/

</details>

<details> 
  <summary>Renderes I’ve studied</summary>

I've studied popular renderers (from [list1](https://github.com/chentsulin/awesome-react-renderer) & [list2](http://iamdustan.com/react-renderers/)) on the matter of self-injection. 

Renderers that inject themselves correctly:
- [react-dom](https://github.com/facebook/react/tree/master/packages/react-dom)
- [react-three-renderer](https://github.com/toxicFork/react-three-renderer)

These do not inject themselves:
- [react-art](https://github.com/reactjs/react-art)
- [react-canvas](https://github.com/Flipboard/react-canvas)
- [react-three](https://github.com/Izzimach/react-three)
- [aframe-react](https://github.com/aframevr/aframe-react)
- [react-blessed](https://github.com/Yomguithereal/react-blessed)
- [react-dom-stream](https://github.com/aickin/react-dom-stream)
- [react-titanium](https://github.com/yuchi/react-titanium/)
- [react-pdf](https://github.com/diegomura/react-pdf)
- [konsul](https://github.com/mohebifar/konsul)
- [mylittledom](https://github.com/manaflair/mylittledom)
…

These ones fire injection but are not hooked in browser:
- [react-hardware](https://github.com/iamdustan/react-hardware)
- [react-vr](https://github.com/facebook/react-vr)

</details>

P.S. Maybe we could use `[[FunctionLocation]]` of `render` somehow, I don’t see the generic solution yet. I hope it's ok to think about it for a few more days.

**Comment by ngyikp** [comment] 2017-09-24 04:03
Additional problem: It's impossible to tell whether a duplicated React is a mistake by the site developer or they are using some third-party libraries that also uses React. (https://github.com/facebook/react/issues/10768)

Example: https://www.kenhub.com/en/atlas/acromion (third-party library: https://djtflbt20bdde.cloudfront.net )

Perhaps in future version that can show a table of React renderers on the page and the minification status for each?

**Comment by chisler** [comment] 2017-09-24 07:36
Hi! Thank you for the comment. 

I pointed that out in code: [`// Currently we overwrite buildType with each injected renderer's type`](https://github.com/facebook/react-devtools/pull/714/files#diff-439718d2e367a4585cd08ce8ec48a328R202).

The issue with overwriting is applicable to any renderer inspection: it only depends on the order they inject. The table will allow to report unminified _and_ duplicated React as well. 

I wanted to suggest the table too, though I felt like it's a next step, because it's a change in the [way](https://github.com/facebook/react-devtools/blob/83adb171e700f43846f559f3e009acf99d6bba31/shells/webextension/src/background.js#L73) we report, not duplication problem.

**Comment by bvaughn** [comment] 2019-08-19 23:28
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:28 UTC
Labels: difficulty: medium, someone is working on this
