### ISSUE TITLE
Warnings with Immutable.js

### ISSUE THREAD

**Issue by roganov** [facebook/react-devtools#126] opened 2015-08-06 14:20 UTC
With enabled plugin, I'm seeing multiple warnings regarding the access of `length` property on `Immutable.js` objects. When I disable the extension, the warnings are gone.
It also may be an issue on my side, so please excuse in this case.
Warning message:
```
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at src_Map__Map.Object.defineProperty.get (/* removed */)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:50:21)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:70:17)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:70:17)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:70:17)
    at eval (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:72:2), <anonymous>:178:19)
    at Array.map (native)
    at Bridge.flush (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:72:2), <anonymous>:173:33)
    at eval (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:72:2), <anonymous>:161:17)
```
The warning originates at `dehydrate.js?ca6a:59`

**Comment by ngyikp** [comment] 2015-08-06 14:43
Duplicate of https://github.com/facebook/react-devtools/issues/125 and https://github.com/facebook/react-devtools/issues/106

**Closed** 2015-08-06 15:32 UTC

**Comment by roganov** [comment] 2015-08-06 15:44
Sorry, didn't search in closed issues.
