### ISSUE TITLE
App responding very slowly while debugging

### ISSUE THREAD

**Issue by AaronDrobek** [facebook/react-devtools#1284] opened 2019-01-22 17:00 UTC
Browser 10.14 Mojave 
React Native Debugger (Stand alone) Version 0.8.2
Device iPhone X Version 12.0.1
While running app locally on actual device, the debugger seems to slow down the functionality of the app. Sometimes up to 45 second delay between a button being pressed, and the app responding. This delay does not happen while not in debug mode. I have done some research into time sync between device and machine being off. I have ensured both are running off the same time zone and server. Do you have any other trouble shoots to attempt to remedy this delay?

**Comment by bvaughn** [comment] 2019-07-31 21:07
React Native Debugger is a third party tool and includes a lot of things in addition to React DevTools. For what it's worth, the upcoming version 4 release of DevTools [will make significant performance improvements](https://github.com/bvaughn/react-devtools-experimental/blob/master/OVERVIEW.md) on the React DevTools side- and React Native Debugger will be updating to use this version (https://github.com/jhen0409/react-native-debugger/pull/371). Whether this resolves the performance issue in that tool is hard to say, although I suspect it would help a lot.

**Comment by bvaughn** [comment] 2019-08-19 23:06
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:06 UTC
