### ISSUE TITLE
Instance of descendant class is shown as instance of base class in component's props

### ISSUE THREAD

**Issue by jeron-diovis** [facebook/react-devtools#1276] opened 2019-01-16 08:01 UTC
It's looks very similar to #308, but about passing some class instance to component's props. Not related to `React.Component` at all.

In short, I'm doing following:

```js
class A { ...whatever... }

class B extends A {
  constructor() {
    super()
    this.some = {}
  }

  get foo() {
    return this.some.value
  }
}

<MyComponent the_instance={new B()} />
```

Then, devtools shows me correct info:

![screenshot 2019-01-15 11 56 16](https://user-images.githubusercontent.com/2756868/51233715-44570d80-1973-11e9-8c4e-f4f1b437ee01.png)

When accessing in console `$r.props.the_instance.foo`, it also works normal:

![screenshot 2019-01-15 11 57 28](https://user-images.githubusercontent.com/2756868/51233716-44efa400-1973-11e9-9e93-ca1a84d10e11.png)

**BUT** when *expanding* `the_instance` prop in devtool's sidebar, smth strange happens:

![screenshot 2019-01-15 11 56 55](https://user-images.githubusercontent.com/2756868/51233717-44efa400-1973-11e9-9af8-b1bd2ff7c6ad.png)

Now it's an instance of not `B` but `A`, and obviously crashes because can't read property of undefined.

Not fatal, but annoying thing, which complicates debugging.

---

Don't know how to create live demo, because have no idea how to connect react-devtools to React inside iframe.

If it can help, my .babelrc:
```
{
  "presets": [
    [ "env", {
      "targets": {
        "browsers": [
          "last 2 versions"
        ]
      },
      "useBuiltIns": true
    }],

    "react"
  ],

  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",

    [ "transform-runtime", { "polyfill": false } ],

    [ "transform-builtin-extend", {
      "globals": [ "Error" ]
    }],

    "transform-decorators-legacy",
    "transform-class-properties",
    "transform-async-generator-functions"
  ],

  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source"
      ]
    }
  }
}
```

**Comment by bvaughn** [comment] 2019-01-16 22:06
Looks like a duplicate of #893 and #976

Repro case: https://codesandbox.io/s/887ql3mrv8

**Closed by bvaughn** 2019-01-16 22:06 UTC
