### ISSUE TITLE
Make "click to view source in editor" work for Create React App based apps

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#726] opened 2017-05-17 22:18 UTC
I mean this link:

<img width="403" alt="screen shot 2017-05-17 at 23 06 48" src="https://cloud.githubusercontent.com/assets/810438/26178471/2d0c4bb0-3b56-11e7-8ecf-82648f637b71.png">

It opens the file in Electron shell (https://github.com/facebook/react-devtools/pull/633), but doesn't work in browser extensions because they can't open files. However, Create React App [has a hook that launches the editor](https://github.com/facebookincubator/create-react-app/blob/c27d7650143312fe6f6e50ad899fc9baaaffd6f9/packages/react-error-overlay/src/components/frame.js#L276-L281).

I think we should allow the browser code to set a special field on the `__REACT_DEVTOOLS_GLOBAL_HOOK__`, like `launchEditor`.

Instead of determining whether to enable the clicks by [checking](https://github.com/facebook/react-devtools/blob/d343f3a696a2842fb8e2c7d3ff244a87781e1448/frontend/Panel.js#L335) shell config [includes `showElementSource`](https://github.com/facebook/react-devtools/blob/d343f3a696a2842fb8e2c7d3ff244a87781e1448/packages/react-devtools-core/src/standalone.js#L34-L36), we could check whether `__REACT_DEVTOOLS_GLOBAL_HOOK__.launchEditor` is a function.

We would define it in the Electron shell to be the existing `launchEditor` implementation. And we would add code to CRA to define it on `__REACT_DEVTOOLS_GLOBAL_HOOK__` at runtime. This way anybody who uses CRA would get it for free.

**Comment by gaearon** [comment] 2017-05-17 22:30
@Timer is looking into it

**Comment by sidorares** [comment] 2017-08-05 11:41
can we have default behaviour for this in chrome extension to open line in 'Sources' pane?

opening line in Sources pane is easy - https://developer.chrome.com/extensions/devtools_panels#method-openResource

Difficult part would be to map from absolute path transform-react-jsx-source generates to `webpack://` + relative local path url. If having 'debugger' permission to extension is an option we could have access to all parsed sources names and try to map them ( longest matching suffix might be a good rule )

**Comment by bvaughn** [comment] 2019-08-19 23:24
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:24 UTC
Labels: difficulty: medium, someone is working on this
