### ISSUE TITLE
Change value via state using React DevTools doesn't fire event handlers

### ISSUE THREAD

**Issue by vasilii-kovalev** [facebook/react-devtools#1054] opened 2018-06-24 20:25 UTC
Hello. I apologize in advance for my English.
I faced such problem when using React DevTools.

There are two components:
```jsx
class Parent extends Component {
    constructor(props) {
        super(props);

        this.state = {
            checked: false,
            // other properties
        };
    }

    filter = ({ target: { checked } }) => {
        this.setState({ checked });
        
        // filter data logic.
    }
    
    render() {
        const {
            checked,
            // other properties
        } = this.state;

        return (
            <Fragment>
                <Child
                    onChange={this.filter}
                    checked={checked}
                    // other props
                />
                { /* other components */ }
            </Fragment>
        );
    }
}
```

```jsx
const Child = ({ checked, onChange }) => (
    <label htmlFor="filter-checkbox">
        { 'Some label text' }
        <input
            id="filter-checkbox"
            type="checkbox"
            onChange={onChange}
            checked={checked}
        />
    </label>
);
```

When I click on the checkbox, event handler is called and `filter` method in the parent component works perfectly. When I change `checked` property via React DevTools (choosing `Parent` component and clicking checkbox near `checked` property in the __"State"__ section) on the page checkbox value (check mark) changes accordingly, but event handler doesn't fire. Also, it doesn't work with __"text"__ type too. Is this a bug or a feature? :)

[Live demo on CodeSandbox](https://k0qxzk9jr3.codesandbox.io/).
[Source code](https://codesandbox.io/s/k0qxzk9jr3) of this demo.

**Comment by bvaughn** [comment] 2019-08-19 23:12
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:12 UTC
