### ISSUE TITLE
Firefox Freezes with devtools open/abnormal memory consumption.

### ISSUE THREAD

**Issue by ajcpwnz** [facebook/react-devtools#1020] opened 2018-04-19 10:18 UTC
Firefox Version 59.0.2 (64-bit), macos High Sierra.
Upon opening any react app and trying to navigate in nested component tree or using highlight tool devtools become partially or completely unresponsive, ram usage increases and in some cases browser restart is required.

Example 1: My real-world project, deep nesting – 10gb ram used out of a sudden, browser and OS became unresponsive until restart. 
<img width="1119" alt="screenshot 2018-04-19 12 39 48" src="https://user-images.githubusercontent.com/16022609/38985862-4055ec7c-43d3-11e8-8e71-907234bd577a.png">

Example 2: Fresh CreateReactApp app with some nesting. 
Repository – https://github.com/ajcpwnz/ff-cra-test.
Slight lags, Upon opening devtools amount of memory consumed increases from 800mb to 1.5-2gb, but it's possible to navigate the tree even with these 1-2s lags. 
<img width="1440" alt="screenshot 2018-04-19 13 15 02" src="https://user-images.githubusercontent.com/16022609/38986008-c4fbd356-43d3-11e8-818c-5015c0c41869.png">

Example 3: Netflix
https://www.netflix.com/browse
<img width="1440" alt="screenshot 2018-04-19 13 00 50" src="https://user-images.githubusercontent.com/16022609/38986067-fad65f0a-43d3-11e8-8bfc-b655e35ccc40.png">
After opening devtools memory consumption raises from 800mb to 2gb and upon navigating the tree it raises even further, up to 4gb. 
<img width="1440" alt="screenshot 2018-04-19 13 06 02" src="https://user-images.githubusercontent.com/16022609/38986117-249f0a9e-43d4-11e8-9fef-c520123ead83.png">

Severe lags are experienced, almost impossible to navigate tree, memory consumption restored to normal after closing devtools.

**Comment by bvaughn** [comment] 2019-08-19 23:12
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:12 UTC
