### ISSUE TITLE
Exception when inspecting a state containing a HTMLDocument

### ISSUE THREAD

**Issue by pomber** [facebook/react-devtools#952] opened 2017-12-10 21:17 UTC
Repro:
1. Go to [minimal demo](https://rawgit.com/pomber/41942e298287d583b078adfb4c9b9b4c/raw/b7a8ab21f709c220e88ceb28cde3ec62c286d71f/index.html)
2. Open React DevTools
3. Inspect Component `state.doc`

Throws:
```
TypeError: Illegal invocation on
(anonymous) (backend.js:7482)
_inspectResponse (backend.js:7478)
_handleMessage (backend.js:7360)
listener (backend.js:86)
postMessage (async)
handleMessageFromDevtools (contentScript.js:18)
EventImpl.dispatchToListener (VM29 extensions::event_bindings:403)
publicClassPrototype.(anonymous function) (VM35 extensions::utils:138)
EventImpl.dispatch_ (VM29 extensions::event_bindings:387)
EventImpl.dispatch (VM29 extensions::event_bindings:409)
publicClassPrototype.(anonymous function) (VM35 extensions::utils:138)
dispatchOnMessage (VM36 extensions::messaging:392)
```

Environment:
- Chrome Version 63.0.3239.84 (Official Build) (64-bit)
- Windows 10
- React Developer Tools 2.5.2

Here's the [gist](https://gist.github.com/pomber/41942e298287d583b078adfb4c9b9b4c)

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
