### ISSUE TITLE
Mistake in execute "npm run build extension:chrome"

### ISSUE THREAD

**Issue by randoudou** [facebook/react-devtools#1337] opened 2019-04-23 09:04 UTC
Here is the content of my "package.json":
{
  "name": "reacttools",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "build": "node build/build.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

and here's debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   'extension:chrome' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose stack Error: missing script: build
4 verbose stack     at run (D:\Program Files\nodejs\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:418:5
4 verbose stack     at checkBinReferences_ (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:373:45)
4 verbose stack     at final (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:416:3)
4 verbose stack     at then (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at ReadFileContext.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:332:20)
4 verbose stack     at ReadFileContext.callback (D:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:237:13)
5 verbose cwd D:\ReactTools
6 verbose Windows_NT 10.0.17134
7 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build" "extension:chrome"
8 verbose node v10.15.3
9 verbose npm  v6.4.1
10 error missing script: build
11 verbose exit [ 1, true ]

Thanks for helping me.
This is my first issue.

**Comment by bvaughn** [comment] 2019-08-19 23:05
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:05 UTC
