### ISSUE TITLE
Mute useless Electron logs

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#702] opened 2017-05-10 09:52 UTC
I occasionally see stuff like this printed by the [standalone devtools](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools):

<img width="882" alt="screen shot 2017-05-10 at 10 51 32 am" src="https://cloud.githubusercontent.com/assets/810438/25893167/b21ea264-356e-11e7-80de-4277b4527e73.png">

We should find a way to mute these logs if possible.

**Comment by prometheansacrifice** [comment] 2017-05-10 16:05
Should all logs be muted?

**Comment by gaearon** [comment] 2017-05-10 16:13
Yea. (At least coming from Electron native side.)

**Comment by prometheansacrifice** [comment] 2017-05-10 17:15
We can simply change `{stdio: 'inherit'}` to ` {stdio: 'ignore'}`. But that would prevent **all** logs from electron.

Else we could listen on like this process.stdout.on('data', () => {}) and turn it off appropritately

**Comment by gaearon** [comment] 2017-05-11 10:59
I'm cool with `{stdio: 'ignore'}`.

**Comment by bvaughn** [comment] 2019-08-19 23:28
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:28 UTC
Labels: difficulty: medium, someone is working on this
