### ISSUE TITLE
What causes circular structure warning? What is it?

### ISSUE THREAD

**Issue by merlinpatt** [facebook/react-devtools#950] opened 2017-12-06 04:09 UTC
Every so often I see the warning "React DevTools encountered an error: TypeError: Converting circular structure to JSON" pop up in my console.

I've tried Googling for this but it usually comes up related to Redux, which I'm currently not using.

What exactly is this circular structure that the warning is referring to? What are some likely causes?

I'm not asking for the cause of my specific project, just in general so I can better understand this and debug it.

**Comment by HaciKale** [comment] 2019-03-04 09:18
I would like to know this too, it's not often but it occurs sometimes and would be nice to have some sort of knowledge about what causes it

**Comment by apenab** [comment] 2019-03-04 14:14
I join those who want to know the solution to this problem

**Comment by DalyIng** [comment] 2019-07-16 14:14
+1, I join you guys.

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
