### ISSUE TITLE
stuck on "looking for React" if source maps failed

### ISSUE THREAD

**Issue by k1sul1** [facebook/react-devtools#965] opened 2018-01-16 08:55 UTC
Excuse me for the ambiguous title. I'm using Create React App, and sometimes Chrome throws a temper tantrum, and forgets how to parse source maps, or something. This happens about 30 times in an hour. Don't take my word for it, here's a screenshot.

![image](https://user-images.githubusercontent.com/2719615/34979496-14807a26-faaa-11e7-91cb-c86cf3781f09.png)

After I restart devtools with hitting <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>I</kbd> twice,  it works again. I don't know whether this is a problem with Chrome, Create React App, or what, so I'm reporting it here.

![image](https://user-images.githubusercontent.com/2719615/34979637-8f83ba26-faaa-11e7-8698-47f15974a919.png)

This is a bit annoying, as the "source map crash" can happen at any time, and when it happens, I have to restart the devtools, _and_ then navigate through the component tree all over again, as react-devtools doesn't remember which node was selected / open. 

Someone else must be having this problem, but my searches have been in vain.

**Comment by k1sul1** [comment] 2018-01-24 14:59
This is driving me mental. Also reported to Chromium bugtracker.

https://bugs.chromium.org/p/chromium/issues/detail?id=805430

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
