### ISSUE TITLE
More than one selected item is confusing

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#623] opened 2017-04-25 12:39 UTC
Selection is currently based on node IDs which can be confusing when there are several nodes with the same ID (due to search):

![](https://d2ppvlu71ri8gs.cloudfront.net/items/3U3R2Y1D1Y2o261m1m3C/Screen%20Recording%202017-04-25%20at%2001.37%20PM.gif?v=d7f014ec)

In this case it’s not clear which of them the keyboard is navigating, and it can lead to annoying jumps when they’re far enough for one of them to be outside the scrolling window.

I think we should somehow change the selection implementation to be local to specific nodes, and not track this globally. This can prove tricky since we also still need to support navigating with keyboard shortcuts.

I don’t know how to solve this, but open to suggestions in PRs. I presume fixing this would require refactoring how selection works.

**Comment by kiranps** [comment] 2017-04-25 16:14
@gaearon I'd like to work on this

**Comment by gaearon** [comment] 2017-04-25 16:21
Cool, you got it.

**Comment by bvaughn** [comment] 2019-08-19 23:29
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:29 UTC
Labels: bug, difficulty: medium, someone is working on this
