### ISSUE TITLE
Display "..." on getters to defer their evaluation

### ISSUE THREAD

**Issue by ddsol** [facebook/react-devtools#390] opened 2016-06-25 21:58 UTC
In `Bridge.js` there's an access to [`val.__proto__[name]`](https://github.com/facebook/react-devtools/blob/dfe8977860d1ee4298fe18c34dc86012c3d8288e/agent/Bridge.js#L381), which seems like it should be okay. However, it is possible to define a getter that expects a complete instance, rather than a empty prototype.

For instance:

```
var proto = {
  get upperName() { return this.name.toUpperCase()}
};

var instance = Object.create(proto);
instance.name = 'Foo';
console.log(instance.upperName); //=> FOO

console.log(instance.__proto__.upperName); //Throws: Cannot read property 'toUpperCase' of undefined
```

Bridge.js could
- Fetch the property get result from the original instance and put the value on the `result` upon an exception.
- `defineProperty` any getters on the `__proto__` so they continue to refer to the same instance. Any readout could then throw (i.e. `result.__proto__.upperName` still throws), but referring tto `result[name]` would not throw.
- Fetch the property get result from the original instance and put the value on the `__proto__` instead upon an exception.
- Just show an error as the property value.

It seems to me the value should show somewhere, rather than an error displayed. In any case, as it stands now, it breaks the extension. The error can only be found in the console.

Also, property getters could throw for reasons other than an instance/proto issue. It's probably a good idea to catch errors thrown and display the error in the UI, rather than aborting the code flow of the extension. It could be as simple as storing the error as a string on the property or just calling `dehydrate(err)` on the caught error.

**Comment by orangy** [comment] 2016-06-28 19:56
I'm having the same issue with kotlin.js. `List` defines `size` property with custom getter. It expects full instance, not just prototype. Now it crashes when trying to inspect it when part of the props.

**Comment by jaredly** [comment] 2016-06-29 17:49
We could probably use [`getOwnPropertyDescriptor`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor) to detect things that have getters & dehydrate them specially (chrome devtools does this, rendering the value as `...` until you click it & force evaluation)

**Comment by ddsol** [comment] 2016-06-29 17:52
Eval on request is technically superior since getters can have side effects.

**Comment by ianstormtaylor** [comment] 2016-07-20 18:39
Running into this in [`slate`](https://www.npmjs.com/package/slate) as well with getters defined.

**Comment by gaperton** [comment] 2017-01-06 22:41
PR #469 fixes this issue as well.

**Comment by gaearon** [comment] 2017-02-15 19:02
Happy to accept a standalone fix for this!

**Comment by gaearon** [comment] 2017-02-16 15:21
>We could probably use getOwnPropertyDescriptor to detect things that have getters & dehydrate them specially (chrome devtools does this, rendering the value as ... until you click it & force evaluation)

This is what we should do.

**Comment by zinoviev** [comment] 2017-02-21 10:26
Thinking about implementing this. Want to clarify how it should work:

- In dehydrate check if object member is property with  `getOwnPropertyDescriptor`
- Introduce new meta type like 'property'
- Render UI  '...' for these objects
- Eval value in response for user action

Not sure how implement last point, so tips will be useful.

**Comment by gaearon** [comment] 2017-02-21 16:22
>Not sure how implement last point, so tips will be useful.

I'm not sure either—I think you should give it a try and see what works 😛  You'll want to have access to the getter and the target object so that you can call the getter when necessary. What you described sounds reasonable to me.

**Comment by gaearon** [comment] 2017-02-24 22:11
@zinoviev Just to be clear, are you still planning to implement this?

**Comment by zinoviev** [comment] 2017-02-24 22:17
@gaearon Yep, already started

**Comment by gaearon** [comment] 2017-02-24 22:26
Awesome, thanks!

**Comment by zinoviev** [comment] 2017-02-26 18:44
Take a look at PR plz https://github.com/facebook/react-devtools/pull/569

![devtools-sample](https://cloud.githubusercontent.com/assets/848985/23342502/bac1c738-fc6c-11e6-9dee-331d62892d5c.gif)

**Comment by gaearon** [comment] 2017-03-02 00:47
Niiiiice. I will next week! If I don’t please ping me again.

**Comment by RuBAN-GT** [comment] 2018-01-30 09:06
Good day everyone! Did you fix this problem? When I try to call object with getters that calling other getters I'll get errors for them ;(

**Comment by zinoviev** [comment] 2018-01-30 09:27
@RuBAN-GT Yep, still waiting for merge

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
Labels: difficulty: medium, someone is working on this
