### ISSUE TITLE
DevTools toolbar icon can't detect React version for apps on localhost in Firefox Developer Edition

### ISSUE THREAD

**Issue by bildungsroman** [facebook/react-devtools#1082] opened 2018-08-06 22:10 UTC
The README says to turn on localhost support in Chrome, but this option doesn't exist in the Firefox version of the extension.

Firefox Developer Edition 62.0b13 (64-bit) on macOS 10.13.6

**Comment by bvaughn** [comment] 2018-08-07 02:36
What README are you talking about? I'm not sure what this issue is referring to or what "can't run in localhost"

**Comment by bildungsroman** [comment] 2018-08-07 16:36
In the FAQ, it says "If you are running your app from a local file:// URL, don't forget to check "Allow access to file URLs" on the Chrome Extensions settings page. You can find it by opening Settings > Extensions." The extension also does not detect my app when running in localhost, but there is no "Allow access to file URLs" option in the FF version of the extension.

**Comment by bildungsroman** [comment] 2018-08-07 18:08
Hmmm, it's still not working for me on FF dev 62.0b13.

**Comment by bvaughn** [comment] 2018-08-07 19:02
Can you elaborate on what you mean by "not working"? Does the DevTools extension show up? Does it say anything? Are there any errors in your console?

**Comment by bildungsroman** [comment] 2018-08-07 20:06
I get this message. No console errors. 
<img width="432" alt="screen shot 2018-08-07 at 1 05 38 pm" src="https://user-images.githubusercontent.com/5382821/43799534-a8a46dec-9a42-11e8-9c4e-f22487c574a6.png">

**Comment by bvaughn** [comment] 2018-08-07 20:07
Is your application running in a `<frame>` or `<iframe>`?

**Comment by bildungsroman** [comment] 2018-08-07 20:08
Nope. The DevTools console panel does work, however.

**Comment by bvaughn** [comment] 2018-08-07 20:09
I thought you said DevTools wasn't working? So it's just the little icon up top that detects which version of React is running?

**Comment by bildungsroman** [comment] 2018-08-07 20:11
Yes, that's right:

<img width="523" alt="screen shot 2018-08-07 at 1 08 51 pm" src="https://user-images.githubusercontent.com/5382821/43799849-738193dc-9a43-11e8-805c-b7c1541778d4.png">

**Comment by mcarpenterjr** [comment] 2018-08-09 19:12
Abstracting this up a level, I would like to "softly" suggest this might be an issue with FF , every react site site seems to "[Not appear to be using react]" when I attempt to use React Dev Tools to inspect.

**Comment by digitarald** [comment] 2018-08-15 18:27
Confirmed in 63 Nightly and 62 DevEdition.

- ✅ Devtools panel shows up
- ✅ Toolbar button state changes to blue
- ❌ Toolbar popup always shows no-react message

**Comment by digitarald** [comment] 2018-08-16 15:56
Issue was identified as a regression in Firefox. It is being fixed and requested to be uplifted to 62. Tracking in [bug 1483684](https://bugzilla.mozilla.org/show_bug.cgi?id=1483684).

Stay tuned and pardon the dust 👷

**Comment by shakhbulatgaz** [comment] 2019-01-08 14:13
Did it?

**Comment by safetypins** [comment] 2019-04-05 15:14
Where can I configure the FF extension to "Allow access file URLs"?

**Comment by bvaughn** [comment] 2019-08-19 23:11
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:11 UTC
Labels: need-info
