### ISSUE TITLE
Extension can't be installed from Chrome webstore

### ISSUE THREAD

**Issue by mangandini** [facebook/react-devtools#962] opened 2018-01-12 17:33 UTC
Not related to code as itself, trying to get attention over it.

But the extension cant't be installed because Google Chrome is returning an empty file instead the right .crx file, not sure if is a webstore issue or the build uploaded.

**Comment by ngyikp** [comment] 2018-01-26 14:40
It's working fine now, most likely some temporary Chrome Web Store glitch

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
