### ISSUE TITLE
Exception when inspecting the state, containing an instance which has getter pe

### ISSUE THREAD

**Issue by alexandr2110pro** [facebook/react-devtools#976] opened 2018-01-31 02:24 UTC
`Uncaught TypeError: Cannot read property 'length' of undefined`.

See the screenshot.

![screenshot 2018-01-31 05 22 42](https://user-images.githubusercontent.com/2496784/35601978-c76e7ed8-0646-11e8-9be9-65b1ad98d079.png)

![screenshot 2018-01-31 05 23 17](https://user-images.githubusercontent.com/2496784/35602006-e3b3d4e4-0646-11e8-8002-34669a1d3f4e.png)

**Comment by alexandr2110pro** [comment] 2018-06-10 22:10
any traction?

**Comment by alexandr2110pro** [comment] 2018-06-10 22:10
@clarkbw @sophiebits @zpao @rpl @kassens

**Comment by alexandr2110pro** [comment] 2018-08-12 01:58
@TheDartCode 

Thanks for the clarification!

**Comment by bvaughn** [comment] 2019-01-16 22:19
Duplicate of #893

Repro case: https://codesandbox.io/s/887ql3mrv8

**Closed by bvaughn** 2019-01-16 22:19 UTC
