### ISSUE TITLE
Rename right click menu option from "Find the DOM node" to "Reveal in Elements panel"

### ISSUE THREAD

**Issue by WickyNilliams** [facebook/react-devtools#912] opened 2017-10-12 11:23 UTC
In the rest of dev tools, the phrase _"Reveal in elements panel"_ is used when you want to inspect a specific node. React dev tools uses the phrase _"Find the DOM node"_.

I think it would be useful to align the terminology, so that it is familiar to users. This would allow for quicker scanning of the options, and alleviate cognitive overhead of deciding which option you need depending on the current dev tools tab

![image](https://user-images.githubusercontent.com/1091390/31487048-521759e6-af31-11e7-9aa5-fd28b360d0d8.png)

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
