### ISSUE TITLE
npm install react-devtools failure.... integrity checksum failed when using sha1.......

### ISSUE THREAD

**Issue by woshicezai** [facebook/react-devtools#1196] opened 2018-10-26 07:00 UTC
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.0
  Yarn: 0.27.5
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 2.3 AI-162.3764568

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.52.0 => 0.52.3

in my RN project,i want to npm install react-devtools(2.5.0),in a minute,there are some error log show in my terminate,like this:

Error: sha1-7Qoe24fAXU2xA3xfj0g9ijtfCCU= integrity checksum failed when using sha1: wanted sha1-7Qoe24fAXU2xA3xfj0g9ijtfCCU= but got sha1-psC74fOPOqC5Ijjstv9Cw0TUE10=. (1511 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
    at emitNone (events.js:111:20)
    at Transform.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183░░░░░░⸩ ⠧ extract:fs-extra: sill extract through2@0.2.3
      throw er; // Unhandled 'error' event
      ^

remove this package, this errors gone, working well.
please help me, this problem makes me crazy......

**Comment by bvaughn** [comment] 2019-08-19 23:07
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:07 UTC
