### ISSUE TITLE
Profiler: blank screen after switching commits

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/react-devtools#1288] opened 2019-01-29 12:45 UTC
This might have something to do with switching to a commit where the currently selected component does not exist in the tree anymore?

![screen recording 2019-01-29 at 12 42 58](https://user-images.githubusercontent.com/921609/51909116-b55ee200-23c3-11e9-9ec6-907d88e8d692.gif)

**Comment by blkwtkns** [comment] 2019-02-21 17:49
I just ran into this. You can right click in the window and choose 'reload frame' to reconnect the devtool, but you will lose all profiled data :(

**Comment by bvaughn** [comment] 2019-08-19 23:06
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:06 UTC
