### ISSUE TITLE
[React Native][Feature Request] Display layout styles in a friendlier format for reading

### ISSUE THREAD

**Issue by rigdern** [facebook/react-devtools#515] opened 2017-02-15 20:11 UTC
### Problem

Currently, the layout styles are displayed exactly the way they were written. It'd be useful to do some calculations on them and display them in a friendlier format for reading.

For example, when trying to understand how a view got its size, the `flex` and `alignSelf` properties are very useful. However, in order to understand which axis these apply to, I have to look at the parent's `flexDirection` style. I also might want to look at the parent's `alignItems` property. This process is tedious and mechanical and the inspector can automate it.

### Solution

We might want to have a layout area in the right pane that shows this computed information for you so all the information you need is in one spot. If the parent's `flexDirection` is `row`, it might look like this:
  - `width: 100`
    - `flexBasis: 0`
    - `flexGrow: 1`
    - `flexShrink: 1 (from default)`
  - `height: 100`
    - `alignSelf: flex-start (from alignItems)`

Notice also that each value is annotated with where it came from (e.g. the value is the `default` value or the value came from `alignItems` of the parent). No annotation means the value was specified explicitly.

Another inspector feature that falls into this category is #330.

### Implementation

In order to implement this, the inspector code needs to be able to walk from the current node to its parent node and get the parent's style information. It doesn't look like nodes currently have pointers to their parents.

@gaearon I know you mentioned that React is being rewritten but I'd still be interested in some information about how to walk from a node to the parent node in the current React implementation for use in this feature.

**Comment by gaearon** [comment] 2017-02-15 20:24
>how to walk from a node to the parent node in the current React implementation for use in this feature.

Interestingly, this is not something today’s React allows. There’s no backpointers.

You should have that information in DevTools UI code though. It is abstracted away from React implementation details so I think it already reconstructs the tree including parent information. I’m not sure where exactly it happens (maybe `Store.js`).

**Comment by gaearon** [comment] 2017-02-15 20:26
Also I would suggest learning from prior art in RN Inspector (Cmd+I in Simulator). When DevTools are not enabled, it shows its own layout information:

<img width="320" alt="screen shot 2017-02-15 at 20 25 50" src="https://cloud.githubusercontent.com/assets/810438/22993982/f690cb14-f3bc-11e6-9c99-cd27fa8dd7ee.png">

Is this something we could integrate here?

**Comment by gaearon** [comment] 2017-04-21 13:04
Seems like this will be solved by https://github.com/facebook/react-devtools/pull/590.
While it has some outstanding issues, I’m pretty sure I’ll merge it, so I’m closing this issue.

**Comment by rigdern** [comment] 2017-04-21 19:22
@gaearon Are you sure #590 will fix this? I skimmed through the PR and didn't see logic like this. This feature request is about doing some calculations on styles to show them in a friendlier format. For example, when looking at an element, it'll specifically tell you that the `width` was determined `flex` so that you don't have to inspect the parent to see what it's `flexDirection` is.

**Comment by gaearon** [comment] 2017-04-23 10:12
Hmm. I see now: #590 shows the computed sizes but you are interested in the *reasons* for how they were computed. (Is that right?)

**Comment by rigdern** [comment] 2017-04-24 22:57
@gaearon Yes, I want to see the reasoning behind how the width and height were computed.

**Comment by gaearon** [comment] 2017-04-25 14:24
I see. I don't really know enough about this to suggest anything. I'm not sure there's any programmatic way to "debug" flexbox, and if there is good prior art for this. Feel free to suggest any.

**Comment by rigdern** [comment] 2017-04-25 20:29
@gaearon I have a feature in mind and I described it in the "Solution" section in the initial issue description. If there's not enough detail, let me know and I can elaborate. If nobody beats me to it, I plan to work on a PR when I have some free time.

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
