### ISSUE TITLE
Make React devtools remember the last session opened

### ISSUE THREAD

**Issue by rohmanhm** [facebook/react-devtools#464] opened 2016-12-08 23:05 UTC
This issue come in after I opened a lot of tags very deep.
When I refresh the browser then **React-Devtools** open with new session and I must open each tags again.

**Comment by gaearon** [comment] 2017-02-15 19:39
Yes, this is a duplicate of https://github.com/facebook/react-devtools/issues/295.
You are welcome to contribute this, would you like to try?

**Closed by gaearon** 2017-02-15 19:39 UTC
