### ISSUE TITLE
Tiny font on Firefox 52

### ISSUE THREAD

**Issue by tambeta** [facebook/react-devtools#882] opened 2017-09-08 13:14 UTC
For some reason, the React tab in Firefox Dev Tools has a tiny font to the point of unreadability on my setup. I've installed React Devtools 2.3.3 to Firefox 52.1.2 built against GTK2 on Arch Linux, XFCE 4.12. Two screenshots for comparison:

* Inspector tab ![Inspector tab](https://user-images.githubusercontent.com/9417744/30212882-6d6c3adc-94af-11e7-815e-46a82ca41a36.png)
* React tab ![React tab](https://user-images.githubusercontent.com/9417744/30212883-6d8e801a-94af-11e7-846e-2c5e85f39e98.png)

Proposed fix: the React tab should use the same font settings as the Inspector or Console tab (which in turn seem to use whatever is set as Firefox's default monospaced font). I have set a custom DPI value via `xrandr` to match my monitor's physical properties if that is of any relevance.

I'd be happy to use any temporary workaround (e.g. editing Firefox's userChrome.css) if you can suggest one.

**Comment by clarkbw** [comment] 2017-09-13 07:42
Maybe @digitarald can take a look into this

**Comment by digitarald** [comment] 2017-09-25 20:21
Tested on ESR 52 with `2.3.3` and could not reproduce this. The font size adjusts according to whatever scaling the devtools is set to, even when zooming in and out.

@tambeta could you debug the CSS using the [browser toolbox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox) if anything else changes the font size?

**Comment by tambeta** [comment] 2017-09-26 07:48
The browser toolbox is informative. It seems that the Inspector tab uses `--monospace-font-family` (from global browser settings, I assume) and a relative (80%) font size:

![ff-inspector](https://user-images.githubusercontent.com/9417744/30848450-ddf34e16-a2a7-11e7-8fb3-3983bc51fe05.png)

while React Devtools seems to use hardcoded values (Menlo etc, 11px):

![ff-react](https://user-images.githubusercontent.com/9417744/30848464-e153d27e-a2a7-11e7-9993-b2d7c2cb677d.png)

I would propose React Devtools to mimic the host add-on's behavior.

**Comment by digitarald** [comment] 2017-09-27 05:28
Great find. I guess the build you reported on customized the theme font size.

**Comment by tambeta** [comment] 2018-03-11 20:46
@garyking Sorry, can't help you there. I haven't really looked into it, because I haven't worked with React recently. Do let me know if you happen to find a workaround, though. A very clumsy fix is to increase the global monospaced font size in browser preferences.

I can't say when the problem started, as it was present in the first version of React Devtools I ever installed (2.3.3).

**Comment by garyking** [comment] 2018-03-11 21:28
I ended up switching to using Chrome when using the React Devtools.

**Comment by quarleswn** [comment] 2018-08-21 13:32
Any update on this??? Firefox 61 here and the font size is still not adjustable.

**Comment by leanderlindahl** [comment] 2018-12-12 09:39
I have the same problem (tiny font that won't scale up) with version 3.4.3, Firefox 64.0, MacOS 10.14.1.

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
