### ISSUE TITLE
Significant overhead from message passing

### ISSUE THREAD

**Issue by digitarald** [facebook/react-devtools#1095] opened 2018-08-14 22:18 UTC
Following up on #1080, a profile of selecting elements, which was reported to be slow on Twitter.

STR: Inspect elements on reddit.com and keep hovering over a few.

Result: https://perfht.ml/2MgeVak (Content 4 is the extension process that runs the React Devtools).

A lot of time is spend sending and receiving messages, in which the native stack mostly clones data (and GCs afterwards).

Recommendation: Cut down amount of data sent or change data format to benefit from use structured cloning.

**Comment by bvaughn** [comment] 2019-08-19 23:10
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:10 UTC
Labels: performance
