### ISSUE TITLE
Tree size width is not adjusted on lower levels of trees

### ISSUE THREAD

**Issue by llamerr** [facebook/react-devtools#1287] opened 2019-01-29 11:51 UTC
![image](https://user-images.githubusercontent.com/1281970/51906253-6a959800-23cc-11e9-8adf-725ef0e21623.png)

On big trees lower nodes having small width, which making them hard to read and understand. There is already a scroll below, it will make it better if some minimal width will apply to each node, so scroll will expand

**Comment by llamerr** [comment] 2019-01-29 11:52
Probably related to https://github.com/facebook/react-devtools/pull/1112 https://github.com/facebook/react-devtools/issues/1131 https://github.com/facebook/react-devtools/issues/746

**Comment by bvaughn** [comment] 2019-08-19 23:06
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:06 UTC
