### ISSUE TITLE
Rethink how IDs are mapped to internal instances

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#769] opened 2017-06-01 16:26 UTC
Prompted by https://github.com/facebook/react-devtools/pull/767.

I think we need to remove internal instances completely from the Agent, and expose any wrappers we need from the `attachRenderer` and `attachRendererFiber`. It might make sense to move the ID generation there as well. It's still not clear how this would work for [this code](https://github.com/facebook/react-native/blob/a93b7a2da0849f15708afef1ff99022d8cc55b14/Libraries/Inspector/Inspector.js#L179) which might execute while inspector is not even running.

Finally, this exposes the fact that we [still leak this fiber](https://github.com/facebook/react/blob/f3dd489f361c0d7b122959b1718cf00723820eae/src/renderers/native/ReactNativeFiberInspector.js#L99) to the RN code.
Which is the cause of https://github.com/facebook/react-devtools/pull/767.
Maybe we should just send something else there (index offset?).

**Comment by bvaughn** [comment] 2019-08-19 23:24
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:24 UTC
