### ISSUE TITLE
react-devtools (electron) cannot launch and no error messages

### ISSUE THREAD

**Issue by VicoErv** [facebook/react-devtools#1166] opened 2018-09-24 00:50 UTC
Steps to reproduce:
1. `$ npm install -g react-devtools`
2. `$ react-devtools`
3. exit silently

temporary fix:
1. `$ npm install -g electron react-devtools`
2. `$ rm -rf react-devtools/node_modules/electron && cp electron react-devtools/node_modules/ -r`
3. `$ react-devtools`

node version 8.12.0
npm version 6.4.1
react-devtools 3.4.0 and bundled electron ^1.8.7
electron installed globally version 3.0.0

**Comment by JM-Mendez** [comment] 2018-10-01 17:19
You need to use this module instead of installing it directly

https://github.com/MarshallOfSound/electron-devtools-installer

**Comment by bvaughn** [comment] 2018-10-07 02:00
> You need to use this module instead of installing it directly

You should not need to do this. All that should be required to use the standalone (Electron) version of DevTools is the following:
```
npm install -g react-devtools
react-devtools
```

When you say "exit silently" @VicoErv, is there any error log on your system?

**Comment by theca** [comment] 2018-11-30 14:45
i have the same problem. I try to  install react dev tool directly on my project and i  run 'npm run react-devtools' after added script on package json. I have this error:

`npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! empty-project-template@ devtools: `react-devtools`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the empty-project-template@ devtools script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-11-30T14_00_00_853Z-debug.log
`

**Comment by StartupSam** [comment] 2019-05-01 03:32
Same problem here. @VicoErv , your solution sadly didn't work for me. On step 2 I get the message: "cp: cannot stat 'electron': No such file or directory". @JM-Mendez , tried using that package, but ended up with the same silent-exit result (unless I'm somehow using it incorrectly?).

I still haven't found a working solution to this.  :'(

**Comment by StartupSam** [comment] 2019-05-01 04:10
Same problem here. @VicoErv , your solution sadly didn't work for me. On step 2 I get the message: "cp: cannot stat 'electron': No such file or directory". @JM-Mendez , tried using that package, but ended up with the same silent-exit result (unless I'm somehow using it incorrectly?).

For those who come later: A solution on this page worked for me: [https://github.com/facebook/react-devtools/issues/1097](https://github.com/facebook/react-devtools/issues/1097)

**Comment by bvaughn** [comment] 2019-08-19 23:09
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:09 UTC
