### ISSUE TITLE
react-devtools throw error when setting margin as percentage

### ISSUE THREAD

**Issue by Bigdragon13th** [facebook/react-devtools#982] opened 2018-02-06 11:17 UTC
react-devtools version:  3.1.0
react-native version: 0.52.2

Devtools throw error when setting margin as percentage whenever I try to inspect the element. The element render correctly and having no issue at all if I didn't inspect the element with devtools.

Error message: "JSON value '10%' of type NSString cannot be converted to NSNumber"
Here's part of my code:

```
<TouchableHighlight onPress={this.onPress} style={wrapperStyle}>
    ...
</TouchableHighlight>
```
```
wrapperStyle: {
    marginHorizontal: "10%",
    marginBottom: 5,
    borderRadius: 4
},
```

<img width="1241" alt="screen shot 2018-02-06 at 18 16 21" src="https://user-images.githubusercontent.com/8828628/35856870-df6c2346-0b69-11e8-9dd0-68abfdaf2245.png">

**Comment by lukewis** [comment] 2018-05-08 17:09
Similar conversion issues for margin="auto", padding="50%", etc...as original poster states, it renders fine, but throws a red box when attempting to inspect it.

**Comment by bourliam** [comment] 2018-05-18 20:05
I have the exact same problem, is there any way to solve this ? Thanks

**Comment by SparkleFaerieCoder** [comment] 2018-07-14 20:05
Anyone come up with a solution for this?

**Comment by ronilitman** [comment] 2018-10-02 08:43
Any updates?

**Comment by bvaughn** [comment] 2019-08-19 23:13
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:13 UTC
