### ISSUE TITLE
Ctrl+F find doesn't work, and "Search bar" doesn't attribute names/values or content

### ISSUE THREAD

**Issue by wulftone** [facebook/react-devtools#1136] opened 2018-08-29 21:00 UTC
I'm on version 3.3.1, and Ctrl+F doesn't actually find anything.

Also, the search bar seems to only match on tag/element names, not element attributes or their values.

**Comment by wulftone** [comment] 2018-08-31 17:26
It could be noisy, but I was just expecting one or the other to help me find what I was looking for, and it couldn't :(.  I don't know if Ctrl+F ever worked.  I think it would be useful if it did, though.

**Comment by bvaughn** [comment] 2018-08-31 22:38
For what it's worth, I'm pretty sure that CTRL+F ever worked, and we never intended to match on attributes because that would slow down searching.

**Comment by bvaughn** [comment] 2018-09-01 19:50
I'm going to close this as "working as intended" 😄We can always continue discussion here and re-open in the future if it seems appropriate.

**Closed by bvaughn** 2018-09-01 19:50 UTC
