### ISSUE TITLE
percentage margin on <Image> results in redbox

### ISSUE THREAD

**Issue by gsklee** [facebook/react-devtools#821] opened 2017-06-23 07:38 UTC
I put something like `marginTop: '10%'` on an `<Image>` and whenever I move my cursor across it inside the devtool, my iOS simulator will turn into a redbox:

![http://imgur.com/Tj2hTQO.png](http://imgur.com/Tj2hTQO.png)

This error message doesn't show up inside the remote debugging console so I could only screenshot it.

**Comment by bvaughn** [comment] 2017-06-24 14:30
Is this the same issue as #820? Can we close one?

**Comment by bvaughn** [comment] 2017-06-24 16:13
Based on the error provided, it looks like you have a typo in your styles markup. (I think you typed a '0' after the '%' accidentally.) The `marginTop` style can be [either a number or a string](https://github.com/facebook/react-native/blob/a38f5b6b6a5013f31772141291716be3c4feeef0/Libraries/StyleSheet/LayoutPropTypes.js#L196-L203) but if it's a string, it has to be parseable.

Pretty sure this issue has nothing to do with DevTools so I'm closing it. If you disagree, please provide more info about how to reproduce it (eg sample code, steps to repro, etc)

**Closed by bvaughn** 2017-06-24 16:13 UTC
