### ISSUE TITLE
Profiler: missing commit index when changing which commits are visible

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#1155] opened 2018-09-12 20:14 UTC
See the gif:

![](https://dzwonsemrish7.cloudfront.net/items/3M1n0z1k3o3I0Q0d1C41/Screen%20Recording%202018-09-12%20at%2009.13%20PM.gif?v=19c8b995)

**Comment by bvaughn** [comment] 2018-09-12 22:01
The "-" is intentional when the currently-selected commit isn't visible after a filter change.

The "0-" is an oversight though for sure. 😅

**Comment by gaearon** [comment] 2018-09-13 18:07
>The "-" is intentional when the currently-selected commit isn't visible after a filter change. (There's no meaningful index we could show in this case.)

Should we change selection to jump to closest available commit?

**Comment by bvaughn** [comment] 2018-09-13 20:31
I think that might be jarring in the scenario where you change the filter, but then change it back or uncheck it.

**Comment by bvaughn** [comment] 2019-08-19 23:09
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:09 UTC
Labels: plugin: profiler
