### ISSUE TITLE
Error: "Expected to find at least one React renderer."

### ISSUE THREAD

**Issue by ghost** [facebook/react-devtools#1032] opened 2018-05-21 11:16 UTC
I get the following error when I try clicking on one of the elements under Inspector mode:  

![screenshot from 2018-05-21 16-35-59](https://user-images.githubusercontent.com/39124207/40304641-2e8088e4-5d15-11e8-92cf-530a5bbc503c.png)

I've installed react-devtools following the [instructions here](https://facebook.github.io/react-native/docs/debugging.html#react-developer-tools).  
react-devtools opens and connects to my app, but when I click on any element, I get the above red box error.  
If this isn't a `react-devtools` related error, can someone please direct me where to look? Thanks in advance! 

Platform: Android 5.1.1 Lollipop running on Genymotion
Host OS: Ubuntu 16.04 LTS
React Native: 0.55.4 (project created using `react-native init`)

**Comment by samuelpismel** [comment] 2018-06-06 15:11
Same issue here... But it is not an react-devtools bug, it happens even without the react-devtools.
Seems to be an react or some other package issue.

Android 6.0
RN 55
Expo 27

**Comment by anisimov74** [comment] 2018-06-14 14:29
I have the same problem. 
Android Emulator 
Android 6.0

**Comment by oneroundseven** [comment] 2018-07-04 07:59
same problem
Android 6.0.

**Comment by chris-divvito** [comment] 2018-08-02 23:27
Same issue here, I tracked it as far as the UIViewOperationQueue class before I stopped being able to follow the logic.

in `react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIViewOperationQueue.java`, in the inner class `FindTargetForTouchOperation`, in it's execute method, it's hitting one of the two try-catch blocks and running `mCallback.invoke();`. Because the callback is called without any of it's expected parameters the `tagId` is undefined all the way back up the callstack until it reaches `getInspectorDataForViewTag` in the JS code and triggers the error.

No idea how to resolve it, but hopefully that assists someone that can?

RN 56, android emulator 6.0 here

**Comment by yasir-netlinks** [comment] 2018-09-08 05:47
Hi guys, anyone found a solution for this problem , I am getting the same issue

**Comment by samuelpismel** [comment] 2018-09-10 17:44
The problem seems to be the package `react-native-root-siblings` which is used by some other packages (like `react-native-root-toast`) if you remove the package that has this dependency the error will stop.
I can't say this is true for all the cases, but it is true for my case:
https://github.com/magicismight/react-native-root-toast/issues/89

**Comment by sunnylqm** [comment] 2018-10-10 17:12
@samuelpismel Your guess is right. I am now the maintainer of `react-native-root-siblings` and I noticed this issue. And I spent 3 hours to test all the reasons that I can imagine, and finally I found it!

1. `react-native-root-siblings` uses an api called `setWrapperComponentProvider` to insert itself with a `wrapperContainer` into [`AppContainer.js`](https://github.com/facebook/react-native/blob/master/Libraries/ReactNative/AppContainer.js#L110), which enables it to insert/update react nodes outside user root component.
2. Now if we want to update root-siblings, we actually update the `wrapperContainer` and hence would cause any of its children to update. So we used a StaticContainer to make user component stay away from root-siblings changes.
3. So far so good, however, there is an android-only optimization called [`collapsable`](https://facebook.github.io/react-native/docs/view#collapsable) which would remove some layout-only views. Inspector needs complete views so it would [disable this optimization](https://github.com/facebook/react-native/blob/master/Libraries/ReactNative/AppContainer.js#L99). 
4. But due to the usage of StaticContainer in the `wrapperContainer`, the `collapsable` optimization can not be disabled via setState from the parent component. So when the inspector called uimanager to try to find an unexisting view, it eventually threw out this android-only exception.

I am still trying to figure out a proper way to fix this. I am open to any suggestions. Thanks.

**Comment by bvaughn** [comment] 2018-11-19 16:54
Has this issue been resolved for everyone?

**Comment by bvaughn** [comment] 2019-08-19 23:12
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:12 UTC
