### ISSUE TITLE
<option>{1}{2}</option> causes `Uncaught TypeError: Cannot read property 'props' of undefined`

### ISSUE THREAD

**Issue by kolodny** [facebook/react-devtools#307] opened 2015-12-24 16:19 UTC
demo here: http://kolodny.github.io/react-devtools-bug/  
source here: https://github.com/kolodny/react-devtools-bug

You need to open up the react devtools tab to see the error

**Comment by inklesspen** [comment] 2015-12-25 01:44
May be a duplicate of #248.

**Comment by spicyj** [comment] 2015-12-25 05:53
Yeah, dupe of #248.

**Closed by spicyj** 2015-12-25 05:53 UTC
