### ISSUE TITLE
Open component's source code in editor from dev tools

### ISSUE THREAD

**Issue by Chetane** [facebook/react-devtools#60] opened 2014-12-19 03:09 UTC
I was experimenting ways to make development faster, and realized opening component's implementation from the DevTools to be incredibly useful. This is possible by leveraging editor supporting uri scheme (e.g. For rubymine, it's something like `x-mine://open?file=/path/to/component.csjx`). I've hacked a very custom implementation that works for my project, but would like to make it much more general and eventually send a PR for this. 

Open questions in terms of UX are:
### Configuration

I imagine users would need to be able to defined transform rules from Component name to file path. This could be as simple as defining a javascript function to do so:

``` javascript
function urlForComponent(displayName) { 
  return "x-mine://open?file=/path/to/" + displayName + ".csjx";
}
```

Where should that configuration screen be? I'm not familiar with common patterns for ChromePlugins when it comes to that.
### Button to open file

My current prototype added a link in the side panel, but that feels wrong. Any suggestions in terms of best place for this link/button to be placed?

![screenshot 2014-12-18 19 08 19](https://cloud.githubusercontent.com/assets/765364/5499675/55914dd4-86e9-11e4-8fae-cdbd78b197a6.png)

I'm hoping to nail down the UX with community feedback before moving on to proper implementation.

**Comment by facebook-github-bot-7** [comment] 2015-08-04 18:05
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment] 2015-08-05 17:39
In the [beta version](http://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html) we just released, you can right-click on a component and view it in the `Sources` tab, which is as good as we can do for now. We're looking into getting open in your editor working though

**Comment by bvaughn** [comment] 2019-08-19 23:31
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:31 UTC
Labels: enhancement
