### ISSUE TITLE
Not working with react-native

### ISSUE THREAD

**Issue by laclance** [facebook/react-devtools#708] opened 2017-05-11 08:52 UTC
The image shows how far i can get.  ![screen shot 2017-05-11 at 10 35 27 am](https://cloud.githubusercontent.com/assets/10835285/25940774/855aabf0-3637-11e7-9aef-4231d455fa08.png)

Nothing happens when clicking on the View in the inspector nor on the children objects in the developer tools. When using the inspector in the simulator i can highlight elements but no details show up. 
When using the chrome developer tools the react-devtools windows stays on `Connecting to React…`
Also tried the react-devtools chrome extension which keeps saying `This page doesn’t appear to be using React. `
Also tried the stand alone react native debugger but inspector does not show up. I remember at at one stage the inspector in the react native debugger was working. i didn't really need it at the time but now i really need to inspect elements style. Any help would be appreciated.

### **EDIT**
Also maybe related: after reloading the app i always get the error: Expected to run on UI thread, which i only started getting after the last update.

"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
Mac OSX Sierra,
Android API 25

**Comment by jhen0409** [comment] 2017-05-11 10:17
I've try to fix it with https://github.com/facebook/react-native/pull/13116 but still not landed, the bug is from `requestIdleCallback` in remote debug mode, it usually on Android device.

> Also tried the stand alone react native debugger but inspector does not show up. I remember at at one stage the inspector in the react native debugger was working. i didn't really need it at the time but now i really need to inspect elements style. Any help would be appreciated.

Actually I've wrote a temporary workaround in [troubleshooting.md of react-native-debugger](https://github.com/jhen0409/react-native-debugger/blob/master/docs/troubleshooting.md), let it fallback to the [custom polyfill](https://github.com/facebook/react-devtools/blob/master/agent/Bridge.js#L23).

**Comment by laclance** [comment] 2017-05-11 11:09
Thank you very much but I tried the work around and still nothing. Ive have tried with simulator and real device.

**Comment by gaearon** [comment] 2017-05-26 18:33
>the bug is from requestIdleCallback in remote debug mode

Can we just disable using rIC on our side if the polyfill is bad? I'd be open to taking a PR that checks for a native implementation using function toString before using it.

**Comment by jhen0409** [comment] 2017-05-27 02:26
> I'd be open to taking a PR that checks for a native implementation using function toString before using it.

That will help more people get rid of this problem!

**Comment by gaearon** [comment] 2017-05-27 11:16
Sounds like a plan. Want to do it?

**Comment by jhen0409** [comment] 2017-05-29 14:01
@gaearon I submitted #749 for fixing this. :)

**Comment by bvaughn** [comment] 2019-08-19 23:28
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:28 UTC
Labels: bug, difficulty: medium, good first bug
