### ISSUE TITLE
value: NaN being displayed as null

### ISSUE THREAD

**Issue by davidfurlong** [facebook/react-devtools#653] opened 2017-04-29 09:14 UTC
![screen shot 2017-04-29 at 11 13 21](https://cloud.githubusercontent.com/assets/614768/25554406/f23eb96a-2ccc-11e7-87bd-785ea3f845bf.png)
![screen shot 2017-04-29 at 11 13 27](https://cloud.githubusercontent.com/assets/614768/25554407/f248548e-2ccc-11e7-8d75-4496fd40483a.png)

**Comment by gaearon** [comment] 2017-04-29 14:58
Thanks for reporting. The underlying issue is https://github.com/facebook/react-devtools/issues/582 if I understand it correctly. Would you like to work on fixing it?

**Comment by davidfurlong** [comment] 2017-04-29 15:50
@gaearon I can give it a try

**Comment by bvaughn** [comment] 2019-08-19 23:27
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:27 UTC
