### ISSUE TITLE
i have a bug when i try to use react tool

### ISSUE THREAD

**Issue by yuval123123** [facebook/react-devtools#659] opened 2017-05-01 09:23 UTC
Uncaught Error: findComponentRoot(..., .0.0.0.0.0.0.2.0.0.0.$0=10.0.1.0.2.$0.$/=11.0.$=10.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.

**Comment by bvaughn** [comment] 2019-08-19 23:27
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:27 UTC
