### ISSUE TITLE
I can't see react tab in console even after enabling and allowing the url's

### ISSUE THREAD

**Issue by Teja1124** [facebook/react-devtools#1009] opened 2018-04-04 08:33 UTC
Chrome Version 64.0.3282.119 (Official Build) (64-bit)

**Comment by Mujaddadi** [comment] 2018-05-23 18:29
Same

**Comment by lassombra** [comment] 2018-07-27 19:30
I'm having the same issue now with Version 67.0.3396.99 (Official Build) (64-bit) plugin version 3.2.4

**Comment by bvaughn** [comment] 2019-08-19 23:12
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:12 UTC
