### ISSUE TITLE
Store skipwrapper calling .get on undefined

### ISSUE THREAD

**Issue by chadlinden** [facebook/react-devtools#1291] opened 2019-02-04 16:31 UTC
Nodes that unmount while they are highlighted in the inspection panel crashes devtools. In `Store.skipWrapper`, the while loop `node.get('nodeType')` is invoked on `undefined`.  

[Here is a commit on my form](https://github.com/chadlinden/react-devtools/commit/888d9b2c46e68afe0cd4249306c9e319303c23e4) with a quick fix, checking the existence of the node before calling methods.

**Comment by bvaughn** [comment] 2019-08-19 23:06
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:06 UTC
