### ISSUE TITLE
devtool is unable to recognise react-native console tab in chrome

### ISSUE THREAD

**Issue by gang89** [facebook/react-devtools#918] opened 2017-10-13 05:03 UTC
My current chrome version:
Version 61.0.3163.100 (Official Build) (64-bit)

any advice?

Regards

**Comment by gaearon** [comment] 2017-11-14 10:51
I don't understand this report. Please submit detailed reports that include screenshots, what you expected to see, and what you see. It is not obvious at all what you mean.

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
