### ISSUE TITLE
[Firefox] Fails to connect when FF responsive design mode is enabled

### ISSUE THREAD

**Issue by markmichon** [facebook/react-devtools#904] opened 2017-09-28 18:38 UTC
Bit of an odd bug, but when the FF dev tools are in "Responsive Mode", the React devtools won't connect. Oddly, if the react panel connects first, then the user switches to responsive mode, it works fine.

To reproduce: Visit a dev or production react site (tested with http://gatsbyjs.org), open ff devtools and turn on responsive design mode, switch to react devtools panel.

Tested in the FF Quantum beta, as well as Firefox Developer Edition (which includes quantum)

**Comment by clarkbw** [comment] 2017-09-28 19:20
@jryans might have some clues here as to why this is happening with responsive design mode

**Comment by jryans** [comment] 2017-09-28 19:39
Thanks for bringing this up! I am fairly sure this is related to a [known issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1394841) with WebExtensions generally being unable to reach content in RDM.

Let's keep this open so we remember to check if React DevTools specifically are fixed once that bug is resolved.

**Comment by mikebabb-gc** [comment] 2017-11-01 13:21
@jryans I notice on your linked issue you mentioned you might look in to this and see how much work would be involved in resolving it, have you had a chance to?

For now a quick workaround seems to be to only enter responsive design mode after a page refresh outside of RDM has allowed React Dev Tools to connect, but it's quite a manual process toggling RDM on and off again as you work.

**Comment by jryans** [comment] 2017-11-01 21:17
> @jryans I notice on your linked issue you mentioned you might look in to this and see how much work would be involved in resolving it, have you had a chance to?

Had some time to look at this today, and it seems pretty straightforward. Hoping to land a fix soon. I'll post an update here once that's all done.

**Comment by jryans** [comment] 2017-11-10 17:02
This should now be fixed in the latest Firefox Nightly 58. @mikebabb-gc @markmichon, could one of you re-test after updating Nightly? It would be great to have verification that it's working for you as well.

**Comment by mikebabb-gc** [comment] 2017-11-12 09:51
@jryans that's great news, thank you! If @markmichon hasn't been able to test before Wednesday, I'll do it then as that'll be my next opportunity to grab Nightly and try to reproduce the bug.

**Comment by markmichon** [comment] 2017-11-12 11:27
I'm traveling for a bit without a non-ios device, so have it at. Otherwise I'll give it a shot when I'm back.

**Comment by mikebabb-gc** [comment] 2017-11-15 09:55
@jryans confirmed fixed in today's Firefox Nightly (59a1). Thanks for your work on this!

**Comment by jryans** [comment] 2017-11-15 16:49
Great, thanks for testing! I guess @markmichon or a repo owner could close this now.

**Closed** 2017-11-15 16:51 UTC
