### ISSUE TITLE
Expand and Highlight Components That are Responsible for Warnings or Errors

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react-devtools#34] opened 2014-04-28 18:48 UTC
React has a warning module that allow us to intercept warning messages. These could be displayed inside the tree so that it's easy to spot which components are responsible for warnings or errors thrown and the properties passed into them.

**Comment by jaredly** [comment] 2015-06-25 05:28
I'm looking around for the place to intercept warning messages, and I can't find it in the code or docs. Could you point me to a file?

**Comment by sebmarkbage** [comment] 2015-06-25 05:42
There is not really any way right now. Other than replacing the warning module with an override, which is what we do internally.

**Comment by sebmarkbage** [comment] 2015-06-25 05:43
You also, just intercept `console.error` (or `console.warn` for 0.13)

**Comment by bvaughn** [comment] 2019-08-19 23:31
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:31 UTC
Labels: enhancement
