### ISSUE TITLE
Remove inline styles from extension

### ISSUE THREAD

**Issue by LestaD** [facebook/react-devtools#385] opened 2016-06-20 12:45 UTC
I use dark theme for devTools.

react: 
![image](https://cloud.githubusercontent.com/assets/5620073/16194579/ed2ed4e8-36fd-11e6-805d-c8d0ed4ac0a6.png)

normal:
![image](https://cloud.githubusercontent.com/assets/5620073/16194591/fb0cb3be-36fd-11e6-835e-e79b976e812b.png)

Maybe move styles to `.css` file?

I use https://chrome.google.com/webstore/detail/devtools-theme-zero-dark/bomhdjeadceaggdgfoefmpeafkjhegbo?hl=ru

@keyanzhang @spicyj @jordwalke

**Comment by mauricecruz** [comment] 2016-07-05 16:46
@LestaD Latest ZDM theme set the background to white for React extension. Let me know if there are any issues!

**Comment by chenglou** [comment] 2016-07-05 18:08
Chrome now has a dark mode built in: 
<img width="634" alt="screenshot 2016-07-05 11 07 49" src="https://cloud.githubusercontent.com/assets/1909539/16594767/bb71184a-42a0-11e6-8166-2037b6d484e5.png">
unfortunately the devtool doesn't work with that.

**Comment by spicyj** [comment] 2016-07-05 18:35
I'm going to count this as a dupe of #108.

**Closed by spicyj** 2016-07-05 18:35 UTC
