### ISSUE TITLE
Does the "Highlight Updates" in standalone app support react native app?

### ISSUE THREAD

**Issue by ameerkat81** [facebook/react-devtools#1309] opened 2019-03-01 13:13 UTC
I'm trying to use the "Highlight Updates" with the standalone app on a react native app. I checked the "Highlight Updates" box, and the color of the text inside the red square will change every seconds, but no highlights shows.   "Highlight Updates"  doesn't support native app?
![image](https://user-images.githubusercontent.com/20416209/53640059-059cbe80-3c66-11e9-9142-df12b515c16a.png)

**Comment by orange4glace** [comment] 2019-03-30 04:00
Same issue with windows 10.

**Comment by NelGarbuzova** [comment] 2019-04-04 13:27
Same here. Does it work? Ubuntu 16.04

**Comment by bvaughn** [comment] 2019-08-19 23:08
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:08 UTC
