### ISSUE TITLE
Search input text colour

### ISSUE THREAD

**Issue by valendea** [facebook/react-devtools#1372] opened 2019-08-02 10:27 UTC
Search input text colour is always black regardless of the theme, pretty hard to read if the theme is dark. Been searching around and found that this problem has been fixed (#1279), but not sure on why this is still happening.

<img width="578" alt="Screenshot 2019-07-30 at 16 04 40" src="https://user-images.githubusercontent.com/25834253/62360354-ce974580-b542-11e9-940c-f71952782a62.png">

Browser: Chrome Version 75.0.3770.142
React DevTools Version: 3.6.0

**Comment by thayannevls** [comment] 2019-08-04 05:10
@valendea Can you tell which theme are you using?

**Comment by valendea** [comment] 2019-08-04 15:25
@thayannevls One (dark)

**Comment by a-x-** [comment] 2019-08-09 08:41
I'm using macos dark and chrome devtools dark theme

**Comment by bvaughn** [comment] 2019-08-19 23:03
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:03 UTC
