### ISSUE TITLE
Feature request: ability to change props

### ISSUE THREAD

**Issue by ffxsam** [facebook/react-devtools#314] opened 2016-01-17 09:09 UTC
It would be really useful if we could modify props!

**Comment by CoryDanielson** [comment] 2016-01-21 22:58
:eyes:

**Comment by jaredly** [comment] 2016-01-22 02:18
hmmm this used to work... but looks like a react optimization made it not work anymore
@spicyj is this now a wontfix?

**Comment by mrcwinn** [comment] 2016-02-02 00:29
Confirmed this isn't working. Why is this considered a wontfix potentially? It's not clear to me the use case of this project without being able to edit props inline, other than to see the original markup of a component. Would love to see this return!

**Comment by spicyj** [comment] 2016-02-02 00:30
This seems like a valuable feature. I don't know what React needs to do for this to work but if React needs to be changed maybe we can do it.

**Comment by jaredly** [comment] 2016-02-02 03:01
@spicyj I did a little digging and it looks like react only reads the `props` once, and then not again (and actually re-sets the `props` attribute to be the original `props` if it changes) -- unless it changes from the parent. I imagine this is an optimization, but it would be useful to be able to disable it -- maybe just on a per-instance basis? (like a `dangerouslyEnableModifiableProps()` or sth that devtools would call when a user wants to fiddle with the props)

**Comment by spicyj** [comment] 2016-02-02 19:24
Can you point me to the code you're looking at?

**Comment by jaredly** [comment] 2016-02-03 20:17
Basically I put a breakpoint [here](https://github.com/facebook/react-devtools/blob/master/backend/getData.js#L110), saw that the new props were set correctly, and then saw that the props were reset directly after the `forceUpdate()` happened

**Comment by spicyj** [comment] 2016-02-03 21:19
Well, the React element is the source of truth. Did you try making a new element and setting `._currentElement` on the internal instance?

**Comment by jaredly** [comment] 2016-02-03 22:07
hmm nope haven't

**Comment by wesbos** [comment] 2016-02-17 19:40
This feature is really helpful for both teaching as well as debugging - would love to see it back in :)

**Comment by adrianmc** [comment] 2016-03-11 19:47
Any workaround for this as of yet? I've literally spent hours having to navigate through my app because I am lacking this  feature.

**Closed** 2016-04-25 16:58 UTC

**Comment by damiangreen** [comment] 2017-09-07 15:57
This doesn't work for functional components though. They are set to read-only and can't be modified.
![image](https://user-images.githubusercontent.com/1592820/30172740-92c3fc92-93ed-11e7-951d-04c59af679d8.png)

**Comment by avalanche1** [comment] 2018-04-25 02:07
> This doesn't work for functional components though. They are set to read-only and can't be modified.
Can this be fixed pls?
