### ISSUE TITLE
Having PORT environment variable set causes react-devtools to use that value

### ISSUE THREAD

**Issue by barretthafner** [facebook/react-devtools#1064] opened 2018-07-19 00:53 UTC
I was running in circles trying to figure out why react-devtools was not connecting to a brand new [create-react-native-app](https://github.com/react-community/create-react-native-app) build in my environment, but was connecting for my colleague.  Turns out I had the `PORT` environment variable set, which causes react-devtools to try to connect on that port (8080) rather than the default (8097).  This is pretty opaque functionality that needs to be better documented and ideally would be done with a command line flag instead (ie `react-devtools --port 8080).

**Comment by bvaughn** [comment] 2019-08-19 23:11
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:11 UTC
