### ISSUE TITLE
Property Inspector is Not Resilient to Non-existent Property

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react-devtools#774] opened 2017-06-01 18:36 UTC
`val` can be `null` [here in `_inspectResponse`](https://github.com/facebook/react-devtools/blob/40f926dfab63051446e9b671c369c703f2e21c67/agent/Bridge.js#L432). Which throws and causes havoc. Reproed in Outlook 365.

What happens here is that the property keys enumerate in the property view as if they're own properties and not on the prototype. But when I try to expand one of the properties. It is now on the prototype (not own) and therefore `getIn` returns `null`.

I'm not quite sure how that's happening. Perhaps there's a getter in the user code. However, since `getIn` is explicitly invoking getters it needs to be more resilient to the assumptions changing.

**Comment by sebmarkbage** [comment] 2017-06-01 19:12
I think the source of the bug is that [dehydrate does not use getOwnPropertyNames](https://github.com/facebook/react-devtools/blob/dcdcebf7131364a74bd9c6d81ec689c6b1e05198/agent/dehydrate.js#L156-L159) like `_inspectResponse` does. So it ends up missing non-enumerable and also picks up non-own properties. I should be able to find a smaller repro...

**Comment by sebmarkbage** [comment] 2017-06-01 19:33
Ok here's a repro:

```js
function Foo() { }
Foo.prototype = {
  bar: function() {}
};
return <SomeComponent foo={new Foo()} />;
```

Try to inspect the `bar` function.

**Comment by gaearon** [comment] 2017-06-02 14:12
@zinoviev Would you be interested in looking at this?

**Comment by zinoviev** [comment] 2017-06-02 14:51
Ok I will

I almost sure the source of an issue on the backend side when we try to get value from a function defined on the prototype. Dehydrating prototype defined properties looks totally legit for me.  

Other types not failing(including getters on my branch)
`
function Foo() { }
Foo.prototype = {
  bar: 'wow',
};

return <SomeComponent foo={new Foo()} />;
`

**Comment by sebmarkbage** [comment] 2017-06-02 17:21
Dehydrating prototype defined properties are visualized differently (behind `__proto__`) so it seem misleading to dehydrate them.

**Comment by nighca** [comment] 2017-12-14 09:26
Any progress about this issue? @zinoviev 

What about we use `try...catch` to wrap the `prototype`'s property reading behavior. If that throws, use `null` instead.

**Comment by bvaughn** [comment] 2019-08-19 23:24
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:24 UTC
Labels: bug, difficulty: medium, good first bug
