### ISSUE TITLE
If the backend throws exceptions, the page breaks

### ISSUE THREAD

**Issue by sophiebits** [facebook/react-devtools#236] opened 2015-09-30 23:13 UTC
![image](https://cloud.githubusercontent.com/assets/6820/10209224/0e1020d0-678e-11e5-84cb-41de09bdc1bf.png)

We should probably catch and silence all exceptions from the devtools (when not in dev mode) and have reasonable fallback behavior.

**Comment by vinhlh** [comment] 2017-02-24 02:07
@spicyj moving these errors to warnings (with console.warn) is ok?

**Comment by spicyj** [comment] 2017-02-24 02:09
Yeah, catching them and displaying them as warnings would be okay – would be best to clearly prefix the warning message to indicate that it is an issue with react-devtools.

**Comment by vinhlh** [comment] 2017-02-24 02:17
@spicyj do you think we should to setup something like Sentry to log these errors from the users? 💃

**Comment by spicyj** [comment] 2017-02-24 02:26
I think they'll file issues instead. I doubt using Sentry in the devtools would go over well with privacy-conscious folks.

**Comment by devisscher** [comment] 2017-06-12 15:55
Not sure if this is the right place to comment, but when devtools extension is enabled I get a security error: Your connection to this origin is not secure.

This is caused by the build/backend.js file in React Dev Tools.

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
Labels: difficulty: medium, good first bug
