### ISSUE TITLE
profiler goes blank 

### ISSUE THREAD

**Issue by HosseinAlipour** [facebook/react-devtools#1365] opened 2019-07-21 11:13 UTC
After some recording and exploring results, it goes blank every single time and it's infuriating.
I don't know how exactly I can reproduce it but it mostly happens in ranked profiler and it happens every single time! Have you ever encountered this problem?
extension version: 3.6.0
![c](https://user-images.githubusercontent.com/5198502/61590374-71f46c00-abcd-11e9-959e-3afaee9bb077.gif)

**Comment by dcjones1** [comment] 2019-07-22 19:44
Same issue here. I'm using Chrome 75.0.3770.142. I start profiling something and within a minute, it'll go blank. I have to open a new tab to gain access to the react dev tools again.

**Comment by bvaughn** [comment] 2019-08-19 23:04
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:04 UTC
