### ISSUE TITLE
Cannot scroll through prop list in Firefox Developer Edition

### ISSUE THREAD

**Issue by TylerJAllen** [facebook/react-devtools#1017] opened 2018-04-11 17:43 UTC
Specs:
OS - macOS Sierra version 10.12.6
Broswer: Firefox Developer Edition version 60.0b11
Extension: React Developer Tools 3.2.1

Instructions to reproduce the issue:
On a webpage built with React, click on the React Developer Tool. Locate a component that has a list of props that exceed below the prop view window. Try to scroll down the prop list to view the rest of the props, notice that you are not able to scroll the list.

**Comment by Bagera** [comment] 2018-07-03 09:31
Same happens to me on standard Firefox 61.0.
It only happens if dev tools is in the narrow layout where props is under the breadcrumbs.
If it is wide and props has it's own column it works fine.

**Comment by bvaughn** [comment] 2019-08-19 23:12
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:12 UTC
