### ISSUE TITLE
Can't get extensions built from source to work properly

### ISSUE THREAD

**Issue by sebdel** [facebook/react-devtools#1277] opened 2019-01-16 10:12 UTC
My proxy won't let me install extensions so I'm trying to build react-devtools 3.6 (as extension for Firefox) from source. The resulting addon loads but the react tab doesn't always show up and it doesn't work anyway.

Steps to reproduce:
- 'yarn run build:extension:firefox' at the root dir
- in FF64.0, Addons->debug add-ons->load temporary addon
- select react-devtools/shells/firefox/build/unpacked/manifest.json
-> the addon is loaded

- navigate and inspect facebook.com 
-> the react tab does not appear

- navigate and inspect reactjs.org
-> the react tab appears
- click on it
-> Unable to find React on the page
-> don't know if it's relevant but with debug addon, I can see the following messages:
Loading failed for the <script> with source “moz-extension://f9ebe9aa-2295-40a0-bc73-cf0c1e100ed0/build/panel.js”

**Comment by bvaughn** [comment] 2019-01-16 21:48
I don't think there's much we can do to help here. I can't reproduce the behavior you're describing with 64.0.2 on Mac OS.

```
yarn install
yarn build:extension:firefox
```

1. Open "about:debugging"
2. Click "Load temporary add-on..."
3. Select `packed.zip` file

Here is a pre-built version of the 3.6.0 extension for Firefox, just to rule out any build problems you might be having:
[packed.zip](https://github.com/facebook/react-devtools/files/2766199/packed.zip)

Other than that, I'm not sure what else you may have installed that is interfering. Pretty hard to troubleshoot this remotely. Going to close this issue since it isn't really actionable on our end.

**Closed by bvaughn** 2019-01-16 21:48 UTC

**Comment by sebdel** [comment] 2019-01-18 10:42
Your zip works, thanks. I don't know what's wrong on my side. 
Anyway, would you consider posting prepackaged addons here: https://github.com/facebook/react-devtools#pre-packaged ? Not everyone has access to mozilla addons unfortunately.
