### ISSUE TITLE
PoC "Safety Audit" / Tab idea

### ISSUE THREAD

**Issue by jaredpalmer** [facebook/react-devtools#1172] opened 2018-09-26 18:05 UTC
We are getting ready for Fiber by wrapping `<React.StrictMode>` in various parts of our apps.  

We built a little codesandbox to visualize  our console.log output from our integration tests in order to list which components need to be updated. I think this feature could be expanded and probably piggyback off of the record feature that already exists in React DevTools. It could be it's own tab called like "Safety Audit" or something. It could be very useful for future deprecations as well.

Codesandbox Link: https://codesandbox.io/s/xo6ml4njkw
Screenshot of what the output looks like.
<img width="1180" alt="screenshot 2018-09-26 13 57 59" src="https://user-images.githubusercontent.com/4060187/46099537-00a68100-c195-11e8-8afe-e3957cc9fe56.png">

Thoughts?

**Comment by bvaughn** [comment] 2018-10-07 01:52
It's a little unclear to me what this does that React's DEV-mode warnings don't already do (assuming you're wrapping your app with `<StrictMode>`). Is it just the fact that this combines the various `console.error` calls into one?

My personal sense is that this doesn't need to be in DevTools. If you find the combined view useful, maybe you could just deploy this script to now.sh somewhere and use it that way? 😄

**Comment by bvaughn** [comment] 2019-08-19 23:07
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:07 UTC
