### ISSUE TITLE
ImmutableJS warning: "iterable.length has been deprecated" in dehydrate.js:59

### ISSUE THREAD

**Issue by nkbt** [facebook/react-devtools#125] opened 2015-08-06 04:24 UTC
I am using ImmutableJS Map as state:

```js
  getInitialState() {
    return Map();
  },
  onChange() {
    this.replaceState(Map());
  },
```

![20150806-142055](https://cloud.githubusercontent.com/assets/175264/9103839/6bce192a-3c46-11e5-9473-5af4b020b02a.png)

![20150806-142457](https://cloud.githubusercontent.com/assets/175264/9103881/f44c99f2-3c46-11e5-93f4-0c3e927c3b6e.png)

```
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at src_Map__Map.Object.defineProperty.get (webpack:///./~/immutable/dist/immutable.js?:4602:21)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:50:21)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:70:17)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:70:17)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:70:17)
    at eval (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:72:2), <anonymous>:178:19)
    at Array.map (native)
    at Bridge.flush (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:72:2), <anonymous>:173:33)
    at eval (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:72:2), <anonymous>:161:17)
```

**Comment by spicyj** [comment] 2015-08-06 04:35
Dupe of #106.

**Closed by spicyj** 2015-08-06 04:35 UTC

**Comment by nkbt** [comment] 2015-08-06 05:30
Oh, sorry checked only opened issues and didn't check closed ones.
