### ISSUE TITLE
memo()-wrapped components disappear from the profiler output

### ISSUE THREAD

**Issue by andrew-farries** [facebook/react-devtools#1197] opened 2018-10-26 07:01 UTC
### Reproduction:

https://codesandbox.io/s/y184rxnwv

### Steps to reproduce

* Start a new profiler recording
* Click on the `+` and `-` buttons a few times. 
* Stop the recording
* Observe the flame graph for each commit

### Actual behaviour:

The `MemoizedComponent` has clearly rendered in response to each click on the `+` or `-` buttons, but it is not present in the flame graph for any commit. If the `React.memo` call wrapping `MemoizedComponent` is removed, the component is present in the flame graph.

### Expected behaviour:

As the `MemoizedComponent` has rendered in each commit, it should be present in the flame graph.

This issue is possibly related to #1193.

**Comment by bvaughn** [comment] 2018-10-27 02:00
Let's consider this a duplicate of #1193 😄 We're aware of issues with `memo` and plan to fix them soon– just didn't get it done before the conference unfortunately 😦Sorry!

**Closed by bvaughn** 2018-10-27 02:00 UTC
