### ISSUE TITLE
[Hooks] Highlight Updates incorrectly reports an updates in a tree component

### ISSUE THREAD

**Issue by taras** [facebook/react-devtools#1216] opened 2018-11-04 15:00 UTC
I'm creating a demo of stability of Microstates trees. My goal was to show that Microstates re-uses references between transitions allowing caching of trees of children based on reference to a microstate.

```jsx

function FamilyTree({ person }) {
  let name = useMemo(
    () => {
      console.log('Updating name to', person.name.state);
      return (
        <input
          value={person.name.state}
          onChange={e => person.name.set(e.target.value)}
        />
      );
    },
    [person.name]
  );

  let father = useMemo(() => <FamilyTree person={person.father} />, [
    person.father
  ]);

  let mother = useMemo(() => <FamilyTree person={person.mother} />, [
    person.mother
  ]);

  return (
    <>
      {name}
      {person.name.state && (
        <ul>
          <li>Father: {father}</li>
          <li>Mother: {mother}</li>
        </ul>
      )}
    </>
  );
}
```

In this example, I'm memoizing children based on references to microstates in `person` microstate. I added a console log to log when an input is being re-rendered. Here is a screen recording of this in action.

![2018-11-04 09 39 28](https://user-images.githubusercontent.com/74687/47965549-ac55b300-e016-11e8-88e3-a6c6eb824788.gif)

To reproduce this:

1. [Create a sandbox with the demo app](https://codesandbox.io/s/github/taras/microstates-use-state)
2. Open the apps live url in the browser
3. Open React Devtools and activate "Highlight Updates"
4. Enter names a few level deep

I would expect to only see the input that I'm highlighting update, but it's showing that parent's input fields are updating as well. The console log shows that only one input is being updated when an input is changed. I suspect that it's highlighting parent elements where children are changing, but I wouldn't expect this to be visible.

Here is the demo code https://github.com/taras/microstates-use-state

**Comment by bvaughn** [comment] 2019-08-19 23:08
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:08 UTC
Labels: Hooks
