### ISSUE TITLE
React-devtools with custom port

### ISSUE THREAD

**Issue by RCTnativeapp** [facebook/react-devtools#996] opened 2018-03-06 21:55 UTC
Hi, I am trying to use React-devtools standalone app for ReactNative debugging.  When I open react-devtools it listens for port number 8097. But my app uses port number as "8999". Please help on debugging with custom port number. Also came across React-devtools-core for custom package, but not sure how to use. It would be good if anyone can help in ReactNative debugging. Thanks

**Comment by barretthafner** [comment] 2018-07-19 00:41
Setting the `PORT` environment variable (tested in macOS 10.13.5) seems to make react-devtools use that port specified instead of the default (8097).

**Comment by bvaughn** [comment] 2019-08-19 23:13
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:13 UTC
