### ISSUE TITLE
hooks native state not showing and context api state not showing

### ISSUE THREAD

**Issue by talwaserman** [facebook/react-devtools#1302] opened 2019-02-12 07:18 UTC
i found two issues,
The first is that i can't see primitive state in the devtools for hooks state
The second issue is that you can't see the context api data
**This is how the hook is displayed in devtools:**
![image](https://user-images.githubusercontent.com/4783250/52617860-d89a8e80-2ea5-11e9-938c-109d0de451c9.png)

**This is my component code:**
```import React, { Fragment, useContext, useState, useEffect } from 'react';
import PostsContainer from './appContext/constaContext';

function SearchBox(props) {
    const {posts, setPosts} = useContext(PostsContainer.Context); //global context
    const [term, updateTerm] = useState('tal'); //local state
    
    const handleSearch = () => {
        const newList = posts.filter(item => item.body.indexOf(term) > -1);
        props.updateList(newList);
    }

    return(
       <Fragment>
            Filter: 
            <input 
                type="text" 
                onKeyUp={handleSearch} 
                value={term} 
                onChange={e => updateTerm(e.target.value)}>
            </input>
        </Fragment>
    );
}


export default SearchBox;
```

**Comment by apenab** [comment] 2019-02-13 15:22
@talwaserman  Since it looks like a duplicate of #1282, can you close this issue?

**Comment by apenab** [comment] 2019-02-13 16:12
@talwaserman I think [this](https://twitter.com/apenab1995/status/1095706107425763333?s=19) can help you answer your question.

**Comment by talwaserman** [comment] 2019-02-13 16:24
Thanks @apenab it does seems that they are working on it

**Closed** 2019-02-13 16:24 UTC
