### ISSUE TITLE
In the state inspector, how are objects dealt with?

### ISSUE THREAD

**Issue by theREALdebater** [facebook/react-devtools#959] opened 2018-01-02 14:16 UTC
In the side panel, it is possible to view props and state (a superb feature), and of course the members of either can be plain old Javascript objects (POJOs?). I've noticed that generally these can be expanded to show their (own) members (and their members in turn, and so on), which I think is extremely useful. But how exactly does this work?

I think one of my objects had a 'size' property getter, and it seems the inspector attempted to call it, which resulted in n exception. I don't actually understand why the call would have caused the exception, since the object should have been constructed properly and I think the call should have worked. However, I also don't understand why 'size' got called at all. Does the inspector think an object is a collection if it sees a member of this name? If so, what members will it expect, and (if so) what will it expect them to do or return, please?
  
![react devtools state inspect issue 959 1](https://user-images.githubusercontent.com/12586829/34563351-37a0ebe4-f14a-11e7-8853-35baf3ca8ee1.png)

Additional Information
Version: 2.5.2
Updated: 25 September 2017
Size: 334KiB
Language: English

**Comment by Kovensky** [comment] 2018-03-09 12:00
Sounds like https://github.com/facebook/react-devtools/issues/775

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
