### ISSUE TITLE
DevTools failed to parse SourceMap: http://localhost:8097/backend.js.map

### ISSUE THREAD

**Issue by rybon** [facebook/react-devtools#828] opened 2017-07-05 14:49 UTC
I'm seeing this warning in the console. I can't tell if it is due to my project setup, or something in React DevTools. I'm using the standalone Electron app, the React code is running in an iframe.

**Comment by Nimelrian** [comment] 2017-08-31 07:36
It's definitely due to the devtools, it also appears for me when I'm just serving my app (no iframe, or anything, just a simple web app)

**Comment by restj90** [comment] 2017-09-11 11:43
also seeing it on app created with create-react-app

**Comment by KINGH242** [comment] 2017-09-25 16:35
In Chrome, I get the warning ;
> "DevTools failed to parse SourceMap: http://localhost:8097/backend.js.map"

And in IE11;
> SCRIPT5009: 'Symbol' is undefined

**Comment by Nimelrian** [comment] 2017-09-25 16:37
The server seems to be configured in a wrong way, since it simply returns backend.js when backend.js.map is requested, leading to the error when trying to parse the source map (since it's just simple JS). The actual source map on disk is right though.

**Comment by Talamantez** [comment] 2017-11-23 22:37
Hi - The accepted answer on this page resolved the issue with loading the DevTools.  The solution for me was to disable 'enable js source maps' and 'enable css source maps' in the Chrome Inspector Settings https://stackoverflow.com/questions/44267503/devtools-failed-to-parse-sourcemap

**Comment by ZeroZipZilch** [comment] 2018-01-10 12:04
> The solution for me was to disable 'enable js source maps' and 'enable css source maps' in the Chrome Inspector Settings

This hides the error message, but doesn't resolve the issue. In fact, it makes it a tad bit worse.

This is Chrome devtools with sourcemaps enabled:

![with-warning-and-sourcemaps](https://user-images.githubusercontent.com/15870893/34768382-f745ad5e-f5fa-11e7-82c7-6a637af7279e.png)

As you can see, even though the warning is shown, the sourcemaps work, making the warning merely a disturbance. Now, this is Chrome devtools with sourcemaps disabled:

![without-sourcemaps-and-warning](https://user-images.githubusercontent.com/15870893/34768380-f72a2fa2-f5fa-11e7-8347-241f3233c387.png)

If sourcemaps are disabled in Chrome developer-tools, the warning disappears, but so do the sourcemaps.

This seems to be an error in `react-devtools-core`

A temporary solution (which by no means is good, but works) is to: 
* Go to wherever react-devtools is installed, (in my case `%APP_DATA%/Roaming/npm/react-devtools`)
* Go to `./node-modules/react-devtools-core/build/backend.js`
* Open the file in your editor
* Scroll to the bottom
* Remove `//# sourceMappingURL=backend.js.map`

This will hide the warning while preserving the sourcemaps for your own app.

![with-sourcemaps-without-warning](https://user-images.githubusercontent.com/15870893/34770090-290b7ce2-f600-11e7-91c1-be833bd6468e.png)

----

While experimenting I attempted to visit `http://localhost:8097/backend.js.map` while react-devtools was running, and it appears like what I actually see is the contents of `backend.js` rather than `backend.js.map`.

**Comment by dguayrobotiq** [comment] 2018-10-02 18:57
Also having this issue here. Anyone have found a solution ?

**Comment by Nickman87** [comment] 2019-02-06 08:20
Same issue here, but we **don't** want the sourcemaps to be publicly available.
Is it possible to modify the build so that the sourcemaps are still present, but not referenced to directly and only used on demand and thus getting rid of this warning?

**Comment by EddyP23** [comment] 2019-08-01 12:58
I have the exact same question as @Nickman87

**Comment by rvbonfimm** [comment] 2019-08-03 15:14
Yet having the same issue, just for community report.

**Comment by bvaughn** [comment] 2019-08-19 23:23
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:23 UTC
