### ISSUE TITLE
"Highlight Updates" had false positives if using redux-form

### ISSUE THREAD

**Issue by emiljas** [facebook/react-devtools#951] opened 2017-12-09 23:33 UTC
React devtools show "highlight updates" but as you can see Clazz component always returns empty object from mapStateToProps and mapDispatchToProps.

componentWillUpdate and render functions do not execute so why I observe "highlight updates"?

Simple example to reproduce problem (click on page to trigger "highlight updates"):

```
class ClazzView extends React.Component {
    componentWillUpdate() {
        console.log("componentWillUpdate");
    }

    render() {
        console.log("render");

        return (
            <span style={ { display: "block", width: "100px", height: "100px", border: "1px solid red" } }></span>
        );
    }
}

document.addEventListener("click", () => {
    store.dispatch({ type: "action" });
}, false);

const ClazzForm = reduxForm({ form: "example" })(ClazzView);
const Clazz = connect(
    (state) => {
        return {};
    },
    () => {
        return {};
    }
)(ClazzForm);

const somethingReducer = function() {
    return {};
};

const store = createStore(
    combineReducers({ form: reduxFormReducer, something: somethingReducer }),
    window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
);

ReactDOM.render(
    <Provider store={ store }>
        <App>
            <Clazz />
        </App>
    </Provider>,
    document.getElementById('root')
);
```

**Comment by tan-c** [comment] 2018-02-02 07:41
+!

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
