### ISSUE TITLE
"match browser" is not respected if reloading with dev tools open

### ISSUE THREAD

**Issue by SimenB** [facebook/react-devtools#752] opened 2017-05-30 17:42 UTC
Dev tools does not respect "match browser" them when reloading the page with the dev tools open. Pressing `alt+r` (on mac, at least) reloading the dev tools, and not the page, makes it work.

![react dev tools](https://cloud.githubusercontent.com/assets/1404810/26596664/c4f03d9c-456f-11e7-9df4-350427aa198b.gif)

https://github.com/facebook/react-devtools/issues/108#issuecomment-304445729
/cc @gaearon @bvaughn

**Comment by clarkbw** [comment] 2017-05-30 18:32
Just dug around, I believe the issue is here: https://github.com/facebook/react-devtools/blob/master/shells/chrome/src/panel.js#L113

We need to pass in `themeName={themeName}` for reload as well so it looks more like the [last line](https://github.com/facebook/react-devtools/blob/master/shells/chrome/src/panel.js#L123)

**Comment by jhen0409** [comment] 2017-05-30 19:04
It looks like the fix for this issue have been included in [#731](https://github.com/facebook/react-devtools/pull/731/files#diff-22a93cc8173f8439ac94e061b982e6c8).

**Comment by bvaughn** [comment] 2017-05-30 19:06
Hopefully also in #751

**Comment by bvaughn** [comment] 2017-06-01 21:09
This is fixed in master by #751 😄

**Closed by bvaughn** 2017-06-01 21:09 UTC
