### ISSUE TITLE
State tree vanishes when selected component disappears

### ISSUE THREAD

**Issue by xinkule** [facebook/react-devtools#1140] opened 2018-08-31 08:13 UTC
## Problem

![gif1](https://i.gyazo.com/926b98f2346753e55eea80ab52528d2c.gif)

You can see, when I select a component, and make some actions to unmount **the** component, the whole state tree will just go blank.

But when I select a component that doesn't belong to the disappeared component, it all works well.

![gif2](https://i.gyazo.com/1ec8c42f6bbec371658cb97657b47ef2.gif)

## Version

Chrome 68.0.3440.106  
React developer tools 3.3.1

**Comment by xinkule** [comment] 2018-09-07 03:19
@gaearon I created a minimal demo, seems like it's related to portal. [demo](https://l5yqz257nz.codesandbox.io)

**Comment by elreeda** [comment] 2018-09-20 12:51
having the same issue but @xinkule demo works just fine somehow!

**Comment by xinkule** [comment] 2019-06-19 10:59
@gaearon Hey Dan, looks like it's still unsolved.

**Comment by bvaughn** [comment] 2019-08-19 23:09
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:09 UTC
