### ISSUE TITLE
The Highlight Updates feature is not documented correctly

### ISSUE THREAD

**Issue by kumar303** [facebook/react-devtools#1350] opened 2019-06-06 14:49 UTC
The documentation for the *Highlight Updates* feature is incorrect: https://reactjs.org/docs/optimizing-performance.html#avoid-reconciliation

It shows an outdated screenshot for how to check the box to turn on the feature.

You now have to  first click the gear icon to the right of the search box. That will show the checkbox. This took me an embarrassing amount of time to figure out.

**Comment by fanny** [comment] 2019-07-12 12:20
Perhaps the most appropriate repository is the [React Docs](https://github.com/reactjs/reactjs.org)

**Comment by bvaughn** [comment] 2019-08-19 23:05
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:05 UTC
