### ISSUE TITLE
[React Native] Can't edit object styles

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#891] opened 2017-09-15 16:34 UTC
Trying to set `shadowOffset` throws an error saying I'm providing a string, but an object is expected.

<img width="375" alt="screen shot 2017-09-15 at 17 34 04" src="https://user-images.githubusercontent.com/810438/30493476-23676e74-9a3c-11e7-87bb-a8bfa5b9c373.png">

**Comment by prometheansacrifice** [comment] 2017-10-28 06:13
Hi @gaearon , I would like to take this up.

I noticed a simple patch like [this one](https://github.com/facebook/react-devtools/pull/931/commits/374d553be8ff901cd78d87045583a4878ac3f7d1#diff-1eba7b953603b35c00edd70420953282), parsing the styles before `setStyle`, fixes the error but forces the use of object style as JSON string which is undesirable.

Given that this problem is already solved for the `PropsState` section of panel using `DataView`, why wasn't `ReactNativeStyle` plugin written using `DataView`. It currently uses `AutoSizeInput` which doesn't handle object like [`DataView` does](https://github.com/facebook/react-devtools/blob/064630a89fc9f4b35a44b533ecf0586e6a792c09/frontend/DataView/DataView.js#L76-L108). I ask because I'm wondering if `DataView` could be reused or should `AutoSizeInput` should mimick `DataView` with this regard.

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
Labels: bug, difficulty: medium
