### ISSUE TITLE
Release latest version to extension store?

### ISSUE THREAD

**Issue by alexkrolick** [facebook/react-devtools#961] opened 2018-01-10 00:28 UTC
![image](https://user-images.githubusercontent.com/1571667/34750117-0be28eea-f55a-11e7-9de7-92ac42c11c03.png)

Looks like 3.0.0 has existed since November, and a few PRs have been merged since September.

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
