### ISSUE TITLE
[Question] Is there any type definitions for react fiber / internals?

### ISSUE THREAD

**Issue by bendtherules** [facebook/react-devtools#1362] opened 2019-07-19 12:31 UTC
From what I understand in https://github.com/facebook/react-devtools/blob/master/backend/attachRendererFiber.js, fiber objects are mostly handled as just objects. 

**Are those properties documented or present as type definitions somewhere?**

Ofcourse, I understand that this are internal interfaces and can break/change very quickly. I am not expecting anything concrete or stable, ad-hoc resources will be also helpful.

**Comment by bvaughn** [comment] 2019-08-19 23:04
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:04 UTC
