### ISSUE TITLE
Tree view collapses immediately after expanding it

### ISSUE THREAD

**Issue by naissur** [facebook/react-devtools#1010] opened 2018-04-04 11:11 UTC
OS: macOS Sierra 10.12.6
browser: Google Chrome 65.0.3325.181
extension version: 3.2.1

![GIF, showing the behavior](https://media.giphy.com/media/9xyIHZUpbgyIQKXqvF/giphy.gif)

When inspecting element, it expands the parent nodes, and then collapses immediately. 
Also, this behavior persists even in the standalone app.

> open chrome://extensions, find react devtools, and click "background page" under "Inspected views". You might find the errors there.

This gives 6 ```Error in event handler for (unknown): Error: Attempting to use a disconnected port object
    at lOne (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js:27:17)``` errors immediately, and another one after a small delay.

**Comment by thirdhand** [comment] 2018-05-22 10:42
I'm seeing this too on MacOS Sierra both in Chrome and Firefox.

**Comment by bvaughn** [comment] 2019-08-19 23:12
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:12 UTC
Labels: bug
