### ISSUE TITLE
[RN] Custom Debugger for Remote JS debugging

### ISSUE THREAD

**Issue by ansumanshah** [facebook/react-devtools#684] opened 2017-05-04 14:34 UTC
Can we add an option for custom [debugger](https://facebook.github.io/react-native/docs/debugging.html#debugging-using-a-custom-javascript-debugger) in the standalone electron package?

Just like [`react-native-debugger`](https://github.com/jhen0409/react-native-debugger) as we have to open chrome for JS debugging, devtools for Inpecting React Components and one more tool if we use state management like redux.

**Comment by gaearon** [comment] 2017-05-04 14:54
Can you explain what would this entail on our side and how it would work?

**Comment by ansumanshah** [comment] 2017-05-04 15:39
Maybe @jhen0409 will be able to explain in detail on what would this entail.
We could just add a Plugin for this and a flag to turn it on.

I believe this would help us get the debugger for react-native inside the electron app, that will maybe help the debugger to always be in the foreground when debugging js bundle.

RN default Chrome Debugger
<img width="1280" alt="screenshotb" src="https://cloud.githubusercontent.com/assets/3208863/25711498/aea16e02-310c-11e7-87f3-b6d8565f70b3.png">
Debugger inside the electron app
<img width="1023" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3208863/25711514/b581a502-310c-11e7-9fed-9f4cf8c7cb33.png">

**Comment by gaearon** [comment] 2017-05-09 15:54
Oh my, that would be amazing. How hard is it to set up?

**Comment by jhen0409** [comment] 2017-05-09 17:48
It‘s not hard, except take code from [`debugger.html`](https://github.com/facebook/react-native/blob/master/local-cli/server/util/debugger.html), we need to know the RN packager port (default is 8081), I think it can be an option for start react-devtools, then we can use [`REACT_DEBUGGER`](https://github.com/facebook/react-native/blob/118e981174ae513426e2f5ddd7ee3c5860519ff7/local-cli/server/middleware/getDevToolsMiddleware.js#L29) env for open react-devtools by RN packager:

```bash
$ REACT_DEBUGGER="react-devtools --enable-rn-debug --rn-packager-port=8082" react-native start
```

We can even set different [`window.__REACT_DEVTOOLS_PORT__ `](https://github.com/facebook/react-native/blob/master/Libraries/Core/Devtools/setupDevtools.js#L33) in debugger worker for multi-packager support. (I'm also doing on [`react-native-debugger#63`](https://github.com/jhen0409/react-native-debugger/pull/63))

**Comment by bvaughn** [comment] 2019-08-19 23:28
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:28 UTC
