### ISSUE TITLE
Components tree height and scroll (white-space: nowrap)

### ISSUE THREAD

**Issue by Apoptotic** [facebook/react-devtools#1109] opened 2018-08-22 13:54 UTC
Before:

![react-dev-tools-good-scrool](https://user-images.githubusercontent.com/11797466/44467291-2aff9e80-a62b-11e8-9fa5-6ec6fffacbd5.PNG)

After:
![reactdevtools](https://user-images.githubusercontent.com/11797466/44467238-0277a480-a62b-11e8-8083-1c0189d14c89.PNG)

I removed "white-space: nowrap;" from the bottom container to make it look like it was before.

When there are lots of elements, how it was before reduces eye strain and the necessity to click in order to navigate.

**Comment by gaearon** [comment] 2018-08-22 15:57
Do you mean you prefer the breadcrumbs to break over multiple lines?

**Comment by bvaughn** [comment] 2018-08-22 18:13
The current behavior (no wrapping) is intentional. The previous stacked breadcrumb bar took up too much precious screen real estate. I considered removing it entirely, but some people were concerned that was too extreme– so instead, it is now single-line. This is more inline with browser's Elements panel behavior.

**Comment by bvaughn** [comment] 2018-08-22 18:13
Closing as "works as intended" unless we're misunderstanding what's being reported.

**Closed by bvaughn** 2018-08-22 18:13 UTC

**Comment by gaearon** [comment] 2018-08-23 14:04
We should still consider displaying the owner stack in it.

**Comment by bvaughn** [comment] 2018-08-24 01:33
I agree! That would make it even smaller and (IMO) more useful. I've added that as a bullet to the umbrella task.
