### ISSUE TITLE
feature request: dont show Components with regards to arbitrary exclude list (basically, hide repetitive High-Order Components from the Tree)

### ISSUE THREAD

**Issue by iamstarkov** [facebook/react-devtools#604] opened 2017-04-04 14:10 UTC
Based on #211.

It would be nice, to have a exclude list of components, which i dont want to see in my react tree.

Exclude list have to be configurable and persistent.

**Exclude list:** `[/GetContext*/, /Jss*/]`

**Tree Before:**
```jsx
<ButtonGroup>
  <GetContext(Jss(Button))>
    <Jss(Button)>
      <Button>
        <span>one</span>
      <Button>
    <Jss(Button)>
  </GetContext(Jss(Button))>
  <GetContext(Jss(Button))>
    <Jss(Button)>
      <Button>
        <span>two</span>
      <Button>
    <Jss(Button)>
  </GetContext(Jss(Button))>
  <GetContext(Jss(Button))>
    <Jss(Button)>
      <Button>
        <span>three</span>
      <Button>
    <Jss(Button)>
  </GetContext(Jss(Button))>
<ButtonGroup>
```

**Tree After:**

```jsx
<ButtonGroup>
  <Button>
    <span>one</span>
  <Button>
  <Button>
    <span>two</span>
  <Button>
  <Button>
    <span>three</span>
  <Button>
<ButtonGroup>
```

**Comment by gaearon** [comment] 2017-04-19 15:23
Also see the discussion in https://github.com/facebook/react-devtools/pull/503.
I think @jaredly started working on a generic blacklisting solution but didn’t finish it (?)

Do you want to propose a mockup for how it would work?

**Comment by iamstarkov** [comment] 2017-05-04 06:30
@gaearon what do you mean by mockup?

**Comment by shriah** [comment] 2017-05-16 05:05
<img width="838" alt="screen shot 2017-05-16 at 10 31 45 am" src="https://cloud.githubusercontent.com/assets/3917104/26090529/31e9a4ae-3a23-11e7-9a25-65cc49a3224c.png">

Something like this should work for initial implementation right ?

**Comment by drcmda** [comment] 2017-10-13 10:09
@gaearon is blacklisting really the way to go? Any random app will cause thousands of random hoc's. Using something like ant-design for instance covers any element in triggers, wrappers, animationlayers, ..., the result is this:

![screen shot 2017-10-13 at 11 49 52](https://user-images.githubusercontent.com/2223602/31541473-09371b60-b00f-11e7-8bd6-4d14b5539bbb.png)

In 99% of all cases i do not care about container hoc's. I find it very hard for this reason to use reacts dev tools, i am faster with hot-reload and console.log(this.props) than finding back the component i want to inspect in the tree.

If there'd be a simple button that eliminates all components that don't end up outputting a dom/target element, that would be very useful.

**Comment by iamstarkov** [comment] 2017-11-29 09:21
> is blacklisting really the way to go? Any random app will cause thousands of random hoc's. It would be pretty tough to create a blacklist and maintain them from project to project. 
>
> would be pretty tough to create a blacklist and maintain

no, not really. its simple RegExp https://regexr.com/3h9ib `/[\(*\)]{1}/gim` for example

**Comment by Kovensky** [comment] 2018-03-09 09:30
How about a `Symbol.for('react.devtools.hide')` property that can be set on the constructor/SFC?

**Comment by markerikson** [comment] 2018-03-09 22:23
This is especially needed with the new `React.createContext()` API, as all uses of `MyContext.Provider` and `MyContext.Consumer` show up in the tree.

It would be particularly nice if there was a checkbox to hide all "built-in React plumbing" component types (context, async/strict mode, etc).

**Comment by develleoper** [comment] 2019-06-05 22:45
Was excited to see this issue open, as it addresses one of my primary complaints with HOC's (and was exacerbated by recent switch to `React.createContext`), but it seems to have had no discussion in the last year. Has the conversation moved elsewhere, or is it just deprioritized / awaiting submissions?

**Comment by SavePointSam** [comment] 2019-06-05 22:54
the new React DevTools just [merged support for this](https://github.com/bvaughn/react-devtools-experimental/pull/295) (in regards to HOCs). You can also create custom filters based on RegExp patterns.

**Comment by develleoper** [comment] 2019-06-06 07:32
Oh, that's awesome! I tried out the beta that was mentioned in the other issue, and it works great, but I'm excited to see all the new features in the full final release. 🙂

**Comment by bvaughn** [comment] 2019-08-19 23:27
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:27 UTC
Labels: difficulty: complex, good first bug
