### ISSUE TITLE
Use filename as component name when exporting anonymous function as default

### ISSUE THREAD

**Issue by sbussard** [facebook/react-devtools#1294] opened 2019-02-05 16:50 UTC
When a component is exported via an anonymous function 

```js
//...
export default () => <SomeComponent />;
```

It shows up as `<Unknown>` in react-devtools.
But I've noticed that react-devtools is able to identify which file the component came from, so it would be helpful to somehow use the filename instead of "Unknown" so that engineers don't have to change their coding style to use the inspect feature to the fullest.

**Comment by jcousins-ynap** [comment] 2019-02-07 14:44
This also occurs in Higher Order Components

```jsx
const Hello = () => <span>Hello</span>

const withWorld = Component => () => (
  <Fragment>
    <Component />
    <span> world</span>
  </Fragment>
)

const HelloWorld = withWorld(Hello)
```
which renders
```xml
<Unknown>
  <Hello><span>Hello</span></Hello>
  <span> world</span>
</Unknown>
```

**Comment by bvaughn** [comment] 2019-08-19 23:06
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:06 UTC

**Comment by jcousins-ynap** [comment] 2019-08-23 09:39
Thanks for the update @bvaughn

**Comment by sbussard** [comment] 2019-08-29 15:16
@bvaughn the new version doesn't seem to show file names at all. Is there a way to enable that? With the codebase I work on it's absolutely critical to my workflow to have that feature.

**Comment by bvaughn** [comment] 2019-08-29 15:37
This little button logs info about the component (including the file name) to the console:
![Screen Shot 2019-08-29 at 8 36 32 AM](https://user-images.githubusercontent.com/29597/63954546-22a92300-ca38-11e9-810a-20c0da24ba30.png)

Related issue on the new repo: https://github.com/facebook/react/issues/16497

**Comment by sbussard** [comment] 2019-09-03 20:52
Awesome! Thanks
