### ISSUE TITLE
react-devtools 3.5.1 breaks standalone mode for Chrome Extensions

### ISSUE THREAD

**Issue by jamaljsr** [facebook/react-devtools#1269] opened 2019-01-04 22:24 UTC
I upgraded to v3.5.1 today and now I cannot inspect my Browser Extension through Chrome as I did previously. See [usage-with-react-dom](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools#usage-with-react-dom)

The console displays the error:
```
Uncaught ReferenceError: ReactDevToolsBackend is not defined
```

I've found what appears to be the problem. `ReactDevToolsBackend` is hard coded in [standalone.js](https://github.com/facebook/react-devtools/blob/master/packages/react-devtools-core/src/standalone.js#L154). The global exported by webpack was changed to `backend` in the recent commits v3.5.0 [28d36a22](https://github.com/facebook/react-devtools/commit/28d36a228de7ff8d72665f3c6a1b8f11ad7e94b6#diff-0da7ccbc75d9b6430b9a287fe1232b1b) and v3.5.1 [bcf6b1aa](https://github.com/facebook/react-devtools/commit/bcf6b1aaf3e15b67b5c797f95c639c810c13db32#diff-0da7ccbc75d9b6430b9a287fe1232b1b).

To fix this locally, I updated [standalone.js](https://github.com/facebook/react-devtools/blob/master/packages/react-devtools-core/src/standalone.js#L154) replacing
```
res.end(backendFile + '\n;ReactDevToolsBackend.connectToDevTools();');
```
with
```
res.end(backendFile + '\n;backend.connectToDevTools();');
```

**Comment by bvaughn** [comment] 2019-01-07 17:34
Hm...I am also unable to launch connect the standalone DevTools to Chrome, but not for the reason you mention. The error I'm getting is:

> Error: ENOENT: no such file or directory, open '/build/backend.js'

**Comment by bvaughn** [comment] 2019-01-07 17:47
> I upgraded to v3.5.1 today

Could you clarify _what_ you upgraded? Was it `react-devtools` or `react-devtools-core` (or both)?

**Comment by bvaughn** [comment] 2019-01-07 17:50
Gotcha! Thanks for confirming.

**Comment by jamaljsr** [comment] 2019-01-07 18:05
I upgraded ‘react-devtools’ to v3.5.1

**Comment by bvaughn** [comment] 2019-01-07 18:06
Yeah, makes sense now that I know you were also seeing the other error. Was confusing before. 😄

**Comment by bvaughn** [comment] 2019-01-07 18:36
A fix has been published to NPM as 3.5.2.

**Closed by bvaughn** 2019-01-07 18:36 UTC
Labels: bug

**Comment by bvaughn** [comment] 2019-01-07 20:41
Can you please confirm that you're not still getting an older version of `react-devtools-core` ?

```sh
# Remove older versions just to be safe
npm remove -g react-devtools-core && npm remove -g react-devtools

# Install latest release
npm install -g react-devtools

react-devtools
```

**Comment by jamaljsr** [comment] 2019-01-07 20:59
Yup, after I upgraded the global package, I realized the old backend.js was being served to my app. After a bit of investigation, I found that i did still have `react-devtools-core` installed in my local `node_modules` even after i uninstalled `react-devtools`. So I did a `rm -rf node_modules && npm install` to start from scratch. That's when this error showed itself. (Note: `react-devtools` is not in my `package.json`) 

I followed your steps just to be sure, but the error still persists. Here's the cmd output:
![image](https://user-images.githubusercontent.com/1356600/50793097-139d1700-1295-11e9-9673-42c6b659e023.png)

**Comment by bvaughn** [comment] 2019-01-07 21:04
Hm. Not sure why you're loading code from `C:\Data\Projects/LightningJoule` in that screenshot. It should be coming from an NPM module.

**Comment by jamaljsr** [comment] 2019-01-07 21:17
It appears that node is looking for `node_modules/react-devtools-core` using a relative path from where the `react-devtools` cmd is executed from.

![image](https://user-images.githubusercontent.com/1356600/50793944-b9ea1c00-1297-11e9-9cba-235379bfd756.png)

**Comment by bvaughn** [comment] 2019-01-07 21:19
I see. I wonder why I'm unable to reproduce this...

**Comment by bvaughn** [comment] 2019-01-07 22:31
In the past, we were using `__dirname` to do a relative import. However, in my testing– that's always resolving to `/` (root dir) on OSX so it's useless.

**Comment by bvaughn** [comment] 2019-01-07 22:40
Looks like this may be related to https://github.com/webpack/webpack/issues/1599

Maybe introduced by the recent Webpack 1->4 upgrade

**Comment by bvaughn** [comment] 2019-01-07 22:53
Okay I think I have a solid fix this time.

**Comment by bvaughn** [comment] 2019-01-07 22:58
Try v3.5.3 😅

**Comment by jamaljsr** [comment] 2019-01-08 02:33
Awesome!! It works 100% installed globally now. Thanks so much for all the effort today. Very impressive bugfix response time. 👏

**Comment by bvaughn** [comment] 2019-01-08 16:01
That's great! Thanks for confirming and for your help tracking it down.
