### ISSUE TITLE
Using with iPhone device

### ISSUE THREAD

**Issue by AndrejGajdos** [facebook/react-devtools#998] opened 2018-03-09 15:02 UTC
If I want to connect devtools with a simulator, it works. When I try an iPhone device connected by USB, I see a message "Waiting for React to connect…"

macOs Sierra 10.12.6
iOS 11.2.6
Xcode 9.2
"react-native": "0.52.0"
react-devtools@3.1.0

**Comment by sosospicy** [comment] 2018-04-21 10:15
A long time passed.. no answer yet?
Try ` adb reverse tcp:8097 tcp:8097`

**Comment by bvaughn** [comment] 2019-08-19 23:13
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:13 UTC
