### ISSUE TITLE
Vigorous perusal of large Redux stores leads to non-responsiveness and eventually OOM

### ISSUE THREAD

**Issue by tailsu** [facebook/react-devtools#599] opened 2017-03-27 10:55 UTC
It always puzzled me why the redux store had a getState() method that returned the state, instead of simply having a state variable. Now I see that had it been implemented so, the react devtools would have died with even smaller stores and apps, with the entire content of the store serialized and transported once per every connected element through the element context.

I have an app with about a 20MB worth of data (when JSON-stringified) in the store and dozens or even hundreds of components in some pages picking various stuff from the store. Then I have a legion of HoCs that dutifully forward all props to the decorated components. Some of those properties come from the store of course, thus multiplying the number of times a set of values coming from the store gets serialized and passed to the devtools.

In essence, once my app loads, devtools needs about a minute to load, and then I have about a minute of time for perusal until the entire tab crashes with an out-of-memory.

So I modded the backend to call a user-supplied callback that can decide which props to really send to the frontend:

```javascript
window.__REACT_DEVTOOLS_USER_MAPPERS__ = {
	mapState: state => state,
	mapProps: props => _.mapValues(props, (v, k) => {
		const state = store.getState();
		return state.hasOwnProperty(k) ? 'from Redux' : v;
	}),
	mapContext: context => context,
}
```
i.e., replace everything in props that is also a property of the state with the string 'from Redux'. Then I can take a look at the Redux Devtools to see the actual value. I thought that I needed to do the same for the context, but luckily, hey - `getState()`.

The counterpart in `backend/getData.js`:
```javascript
 var userMappers = window.__REACT_DEVTOOLS_USER_MAPPERS__;
...
    props = userMappers ? userMappers.mapProps(element._instance.props) : element._instance.props;
    state = userMappers ? userMappers.mapState(element._instance.state) : element._instance.state;
    context = userMappers ? userMappers.mapContext(element._instance.context) : element._instance.context;
```
And presto! React DevTools now connects at a fraction of the time that was necessary before and is actually usable.

Would you be willing to add this extension point, __REACT_DEVTOOLS_USER_MAPPERS__ , to the kit? What are your thoughts on the issue? I don't submit a PR (yet), because I expect that a lot of things will likely change conceptually until the idea is ready for a PR (if at all). Until then, I'll be relying on this modded version to get my work done.

**Comment by tailsu** [comment] 2017-03-27 11:25
I've just realized that react-redux's `connect` keeps the entire redux state as component state, so the entire redux store gets transmitted to the devtools once for each `Connect` component in the tree. So, this line: `mapState: state => state`, should read `mapState: state => _.omit(state, 'storeState')`

**Comment by gaearon** [comment] 2017-04-19 15:27
Thanks for filing the issue. IMO it would make sense to lazy-load deeper properties. I’m not sold on the “extension point” proposal because most people wouldn’t know about it, and it sounds pretty hacky. Ideally we should change our architecture itself to not do too much work.

@jaredly Do you have any thoughts on this? Maybe this was planned and didn’t get implemented, or something.

**Comment by gaearon** [comment] 2017-04-20 13:13
Actually, from reading the source it does seem like we strip out everything that’s more than 2 levels deep. Perhaps we could add more such heuristics (such as delaying hydreation of tails of large arrays)?

**Comment by gaearon** [comment] 2017-04-20 13:15
Marking as needing contributions. I’m not sure what the solution would be like, but we’d want to add a way to lazily trigger hydration of large (>100) arrays. This is somewhat similar to https://github.com/facebook/react-devtools/pull/569 and related to https://github.com/facebook/react-devtools/issues/608. Working on this would probably require a good understanding of how hydration and dehydration works so it’s not an easy contribution (but probably comparable to https://github.com/facebook/react-devtools/pull/569 or https://github.com/facebook/react-devtools/pull/459 in complexity).

**Comment by bvaughn** [comment] 2019-08-19 23:27
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:27 UTC
Labels: difficulty: complex, enhancement, good first bug
