### ISSUE TITLE
devtools freeze after updating Chrome Version 61.0.3163.100 

### ISSUE THREAD

**Issue by dragonza** [facebook/react-devtools#903] opened 2017-09-28 09:22 UTC
I cannot do anything on react dev tools anymore. It froze when I navigated to react tab in devtools. The version of Chrome Version 61.0.3163.100

**Comment by erichdev** [comment] 2017-09-29 22:52
@dragonza Are you using an external monitor? See rickcav's comment: https://github.com/facebook/react-devtools/issues/897#issuecomment-332323561

**Comment by gaearon** [comment] 2017-11-14 10:53
Can you please file a bug with Chrome? We didn't change anything.

**Comment by dragonza** [comment] 2017-11-15 08:36
@erichdev yes I am using an external monitor. It is weird that I didn't have any problem until now. Now I have to move to my laptop screen in order to use react devtool. Otherwise, it freezes out.

**Comment by gaearon** [comment] 2017-11-15 13:02
Please file a bug in Chrome. There's nothing we can fix here if Chrome broke something.

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
