### ISSUE TITLE
Add `==$r` suggestion in inspect tree for currently selected node

### ISSUE THREAD

**Issue by radubrehar** [facebook/react-devtools#638] opened 2017-04-26 08:52 UTC
In chrome devtools the currently selected node displays a `== $0` faded text besides it.
React Devtools would need to display it like `== $r` - see image below.

 ![59b3e2d8-29d9-11e7-8f74-c5c414a1e0b3](https://cloud.githubusercontent.com/assets/196656/25426015/7f5f5b64-2a76-11e7-99bb-8fd880937f1b.png)

Also relates to #618

**Comment by jomahoney** [comment] 2017-04-28 10:47
I'm gonna jump on this if y'all don't mind

**Comment by skyboyer** [comment] 2018-11-18 20:44
I believe it has been implemented and deployed some time ago.
![2018-11-18 22_43_30-uncontrolled components react](https://user-images.githubusercontent.com/956687/48677828-6efb3480-eb83-11e8-8c92-b2c779ed27bb.png)

**Comment by bvaughn** [comment] 2019-08-19 23:27
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:27 UTC
Labels: difficulty: starter, someone is working on this
