### ISSUE TITLE
Typing quickly into filter box drops characters

### ISSUE THREAD

**Issue by spicyj** [facebook/react-devtools#220] opened 2015-09-21 21:17 UTC
Reported by @MichelleTodd.

**Comment by jaredly** [comment] 2015-09-25 14:29
This is the search bar @ that bottom? Assuming it's in Chrome, debugging Web?

**Comment by kassens** [comment] 2015-09-25 17:33
Yes the filter bar on the React panel. I can repro on facebook.com by quickly typing `abc` and only get `ac` as the result.

This is likely caused by the input being managed and going through a `postMessage` roundtrip to the store and back. (Haven't looked into it though)

**Comment by jketcham** [comment] 2015-11-20 23:32
Also experiencing this issue, would debouncing the search function help? Is this the component for search https://github.com/facebook/react-devtools/blob/master/frontend/SearchPane.js?

**Comment by kassens** [comment] 2015-12-16 23:20
So what's happening here is:

- Value in input is `foo`.
- User types <kbd>b</kbd>, an async action "change search to `foob`" is dispatched to the store using `postMessage`.
- The UI side still has the value `foo`, so React doesn't let the `input.value` change.
- `input.value` is still `foo`, user types <kbd>a</kbd> and another async action "change search to `fooa`" is sent.
- `search` is updated in the UI to `foob` and with the next update to `fooa`, dropping the `b`.

Keeping these async user actions with dependencies under control while still allowing the backend to update the value is surprisingly difficult.

**Comment by spicyj** [comment] 2015-12-16 23:31
I suppose we need an optimistic update within the devtools UI.

**Comment by jaredly** [comment] 2016-01-11 16:27
#311 is a fix for this -- @spicyj or @kassens do you want to look at it? I checked it out & it looks good

**Closed** 2016-08-19 18:52 UTC
