### ISSUE TITLE
React developer tools doesn't appear 

### ISSUE THREAD

**Issue by Afra-20** [facebook/react-devtools#954] opened 2017-12-23 05:50 UTC
![react](https://user-images.githubusercontent.com/33478712/34317378-2d2063f0-e7d3-11e7-9a08-10ac57a6d63b.JPG)

**Comment by hristo-kanchev** [comment] 2018-12-14 11:47
@Afra-20 Are you still experiencing this issue?

If not, can you please close the issue?

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
