### ISSUE TITLE
error when inspecting an element with margin-left: 'auto'

### ISSUE THREAD

**Issue by bsr203** [facebook/react-devtools#1145] opened 2018-09-04 15:49 UTC
This may be similar to https://github.com/facebook/react-devtools/issues/982
But in my case, I get error.

` jason value 'auto' of type NSstring cannot be converted to NSnumber`

Updated everything to the latest release.
The error is exactly same error as [here](https://github.com/facebook/react-native/issues/350#issuecomment-171445181). Note that, margin: "auto" is implemented in react native as @vjeux commented on that thread. So, I am not getting any error in the simulator. But, when selecting the element on react-devtools, I get error

`jason value 'auto' of type NSstring cannot be converted to NSnumber`

**Comment by bvaughn** [comment] 2018-09-06 20:27
Sounds like a duplicate of #982. In both cases, it sounds like a string value (e.g. "auto" or "10%") is being treated as if it were a number.

Let's close this issue and leave a comment on that one.

**Closed by bvaughn** 2018-09-06 20:27 UTC
