### ISSUE TITLE
Request support toggle hide element or only show component mode

### ISSUE THREAD

**Issue by Riokai** [facebook/react-devtools#864] opened 2017-08-02 06:49 UTC
Something the page show lots of tags, but I just want focus component.

**Comment by bvaughn** [comment] 2017-08-02 15:20
I don't understand what you're suggesting @Riokai. Could you elaborate?

**Comment by Riokai** [comment] 2017-08-02 15:31
@bvaughn  Of course, `vue-devtools` only show component in window and somethings I just want a toggle to hide html tag like `header`, `p` and `div`, make interface more cleaner.

![image](https://user-images.githubusercontent.com/7970372/28881134-c2a12d3e-77d9-11e7-8c1e-2e3e2329bd3a.png)

![image](https://user-images.githubusercontent.com/7970372/28881305-4699a094-77da-11e7-8655-05f36eb66843.png)

**Comment by emil14** [comment] 2018-02-22 13:31
+1

**Comment by bassarisse** [comment] 2018-04-11 18:37
+1

**Comment by bvaughn** [comment] 2019-08-19 23:16
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:16 UTC
