### ISSUE TITLE
Profiler: Empty state is shown right after profiling

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#1149] opened 2018-09-08 19:52 UTC
I found this confusing:

![empty state](https://dzwonsemrish7.cloudfront.net/items/1X0H0j2I0h1k1Q3S0m2V/Screen%20Recording%202018-09-08%20at%2008.51%20pm.gif?v=46b585e7)

Some loading indicator would be nice.

**Comment by bvaughn** [comment] 2019-08-19 23:09
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:09 UTC
Labels: plugin: profiler
