### ISSUE TITLE
Editing state does not trigger componentDidUpdate correctly

### ISSUE THREAD

**Issue by autra** [facebook/react-devtools#946] opened 2017-11-24 10:14 UTC
# Context

I'm using react to manage the interface for an external webgl application. React controls the state of said application. When a checkbox change, I need to launch some (costly) operations on said application. I therefore do not want to do this operation every time a state change, but only when this particular state property change. So I implemented a check in `componentDidUpdate`, which is basically:

```js
componentDidUpdate(prevProps, prevState) {
   // ....
   if (prevState.fooActivated !== this.state.fooActivated) {
       externalApi.reticulateFooSplines();
   }
   // ....
}
```
This works fine from my app. Unfortunately, this does not work when changing the state from the devtools: `prevState.fooActivated` is already set to the new value.

# Description

When editing a simple boolean state from the devtools, `componentDidUpdate` is called, but the prevState parameter is wrong: it already has the new values.

# Step to reproduce

- open https://s.codepen.io/autra/debug/xPzXLo/WPMLYGmQZYYr (the code is https://codepen.io/autra/pen/xPzXLo)
- click the "Display message" checkbox, observe that an alert shows old and new value for `this.state.displayMessage` and that the message is displayed
- use the React DevTools to change `this.state.displayMessage`

**expected behaviour**
The alert is displayed.

**actual behaviour**
The alert is not displayed, because prevState.displayMessage is equal to this.state.displayMessage in `componentDidUpdate`.

Thanks!

**Comment by p0la** [comment] 2018-03-08 18:00
I see the same behavior. I seems that the existing state is mutated instead of having a new state poperly set. 

in my tests, when trying to implement `componentWillReceiveProps(nextProps)`, `nextProps`, would always be the same as `this.props`.

This makes testing quite tricky.

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
