### ISSUE TITLE
can't install devtools

### ISSUE THREAD

**Issue by AliveDD** [facebook/react-devtools#967] opened 2018-01-16 11:21 UTC
whats wrong? i enter this command to terminal and get err message (i use root# access)
```macbook:~ root# npm install -g react-devtools
/usr/local/bin/react-devtools -> /usr/local/lib/node_modules/react-devtools/bin.js

> electron@1.7.10 postinstall /usr/local/lib/node_modules/react-devtools/node_modules/electron
> node install.js

/usr/local/lib/node_modules/react-devtools/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/react-devtools/node_modules/electron/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.10 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-16T11_18_38_234Z-debug.log
MAC433RIH:~ root# 
```
help please

**Comment by ryanlittle** [comment] 2018-01-18 18:41
Are you installing with sudo? That might be the problem. #741

**Comment by hesgroup** [comment] 2018-01-20 12:12
+1 
Me too. It's not work with sudo too.

**Comment by AliveDD** [comment] 2018-01-20 18:04
@ryanlittle im try with sudo and with root access

**Comment by ryanlittle** [comment] 2018-01-20 22:22
If you need sudo to install packages globally, in most cases, I'd suggest configuring npm to use a different directory. See [this guide](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md) for simple instructions, and [this](https://docs.npmjs.com/getting-started/fixing-npm-permissions) for more info. This may fix the problem.

Alternatively, you may be able to run `sudo npm install -g react-devtools --unsafe-perm=true` with success.

**Comment by TheNuclearCat** [comment] 2018-05-11 21:52
Issue is still there with windows 10 64bit, the solution from @ryanlittle has worked for me (without admin permissions in powershell).

**Comment by shashankbarsin** [comment] 2018-08-09 00:02
I was running into the same issue when using npm to install globally using `sudo npm install -g react-devtools`. 
However  yarn did the trick for me as `yarn global add react-devtools` executed successfully without any errors

**Comment by tomgit2016** [comment] 2018-11-15 02:14
@shashankbarsin is right, yarn works!

**Comment by biswa-m** [comment] 2019-08-19 20:36
I was also having the same problem with `sudo npm install -g react-devtools`.
`sudo npm install -g react-devtools --unsafe-perm=true` worked for me

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
