### ISSUE TITLE
React devtools works with localhost but not hostname

### ISSUE THREAD

**Issue by melissachang** [facebook/react-devtools#1006] opened 2018-03-23 23:57 UTC
Unfortunately I don't think you can reproduce because it has to do with my corporate network (I think). Although maybe your corporate network is set up the same way, so it's worth trying. Here's what I see:

* npx create-react-app my-app && cd my-app && npm start
* Open localhost:3000 in Chrome. React devtools extension icon is red.
* Open http://hostname:3000/ in Chrome. React devtools extension icon is gray. The only thing I see in the console is:
    ```
    Download the React DevTools for a better development experience: https://fb.me/react-devtools
    ```
    I don't see any errors, so I don't know how to debug. Is there a log file I can check?

**Comment by gaearon** [comment] 2018-03-24 14:18
Could this be related to CSP settings or something like this? (Disclaimer: I don't know anything about CSP.)

**Comment by tstirrat15** [comment] 2019-08-06 14:13
I'm also wondering if CSP settings have something to do with it.

When I run react devtools on Chrome on https://www.getmyboat.com, it works just fine, but when I go to the same page with react devtools on Firefox, the icon is greyed out and it says the page doesn't appear to be using React.

The site uses a strict CSP policy - i.e. no `unsafe-inline` or `unsafe-eval` - so I'm wondering if it's something where Firefox treats extension code as injected code, where Chrome doesn't.

**Comment by bvaughn** [comment] 2019-08-19 23:13
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:13 UTC
