### ISSUE TITLE
Feature Request: Perf buttons

### ISSUE THREAD

**Issue by AsaAyers** [facebook/react-devtools#71] opened 2015-03-05 18:18 UTC
It would be really nice if this extension had buttons that called out to `React.addons.Perf.start()` / `React.addons.Perf.stop()` / `React.addons.Perf.print*()`

**Comment by mfunkie** [comment] 2015-03-05 18:29
:+1: This would be fantastic.

**Comment by facebook-github-bot-7** [comment] 2015-08-04 18:05
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment] 2015-08-05 18:03
This is on our radar. Looking into some great perf integration in the devtools

**Comment by Anahkiasen** [comment] 2015-08-08 22:32
:+1: Would love this

**Comment by albertogasparin** [comment] 2016-03-29 15:17
No further update on this? It would be really handy

**Comment by crysislinux** [comment] 2016-04-11 05:19
Hi everyone and @albertogasparin.

I have built a chrome devtools extension to achieve this.

link: https://github.com/crysislinux/chrome-react-perf

**Comment by aight8** [comment] 2016-04-20 01:30
+1

**Comment by martin-svk** [comment] 2016-05-26 09:20
+1

**Comment by sicdigital** [comment] 2017-01-18 03:34
+1

**Comment by ruanmer** [comment] 2017-02-02 06:05
+1

**Comment by marob** [comment] 2017-03-01 14:06
@crysislinux: thanks!
@jaredly & @crysislinux: having a unique/official extension would be great. Is it conceivable to port the chrome-react-perf code to the react-developer-tools?

**Comment by crysislinux** [comment] 2017-04-15 02:25
@marob I am not sure about that. But I will try to dig into react-developer-tools.

BTW. Do people still want this feature? If yes. I will start work on this.

see https://github.com/crysislinux/chrome-react-perf/issues/14

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
Labels: enhancement
