### ISSUE TITLE
Errors in console when using with requirejs

### ISSUE THREAD

**Issue by azizhk** [facebook/react-devtools#689] opened 2017-05-05 04:41 UTC
We use react with requirejs bundler.
```js
require(['react'], (React) => {
  // ...
})
```
Has anything changed regarding the check if website uses react? Like maybe before the check was on 'load' or documentComplete event but is now is on every script addition.

The issue is the the check looks first for `window.React` if not found looks for `window.require` and then sees if `require('react')`
Now in our development build window.require is set first when the requirejs library is loaded but calling `require('react')` triggers that error in console. That you are trying to require a module which hasn't been loaded yet. You need to define a callback which will be called when this module is loaded, requirejs can't do it synchronously.
http://requirejs.org/docs/errors.html#notloaded

This issue does not affect us in production as our vendor is bundled together. The same script defines window.require and require('react'). So no hurry.

I'll try posting a screenshot.

**Comment by gaearon** [comment] 2017-05-05 14:34
Could you provide a minimal example reproducing this?

**Comment by azizhk** [comment] 2017-05-05 18:22
http://termvader.github.io/react-devtools.html
Let me know if this reproduces the error for you.
I've written some comments. Actually the check for "Does this website use React" is run every second or so.

**Comment by azizhk** [comment] 2017-05-05 18:45
Ok so this is not introduced in a recent version of react-devtools but it was always there.
We recently migrated from one error logging solution to another which coincided with the release.
We had set it up such that this error be ignored previously.

Now I realize this is not something which react-devtools should fix but rather the onError implementation. Extremely sorry. What are your thoughts? Also if you know any other browser CommonJS "require" library where I can see how it is implemented.

**Comment by azizhk** [comment] 2017-05-05 19:09
Related to #59

**Comment by bvaughn** [comment] 2019-08-19 23:28
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:28 UTC
