### ISSUE TITLE
Update context issue

### ISSUE THREAD

**Issue by oliviertassinari** [facebook/react-devtools#763] opened 2017-05-31 19:46 UTC
Following @gaearon input, it seems that tha following situation should work (and obviously without warning)
Here is a reproduction example navigating to the next branch of the documentation of Material-UI:

![warning](https://cloud.githubusercontent.com/assets/3165635/26642681/f18aafbc-462e-11e7-8921-6aa56dc61070.gif)
https://material-ui-next.com/demos/text-fields/

```json
"react": "15.5.4",
"react-dom": "15.5.4",
"chrome": "58.0.3029.110", 
```

**Comment by bvaughn** [comment] 2019-08-19 23:24
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:24 UTC
Labels: bug
