### ISSUE TITLE
should lock electron minor version

### ISSUE THREAD

**Issue by paranoidjk** [facebook/react-devtools#887] opened 2017-09-12 09:37 UTC
electron do not obey semver:

- https://github.com/electron/electron/blob/master/docs/tutorial/electron-versioning.md
- https://github.com/electron/electron/issues/5561

Right now electron 1.8.0 released , but actuallay it's a beta release according realease note and npm dist-tag  

https://github.com/facebook/react-devtools/blob/master/packages/react-devtools/package.json#L26

**Comment by sospedra** [comment] 2017-09-27 10:17
This is bad :/
All CI pipelines are blowing up because installation is not possible

**Comment by sospedra** [comment] 2018-04-06 18:57
Again

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
