### ISSUE TITLE
Can't print $r in console

### ISSUE THREAD

**Issue by zhouhao27** [facebook/react-devtools#366] opened 2016-04-21 01:19 UTC
Got an error message:

> VM370:1 Uncaught ReferenceError: $r is not defined(…)

When I input $r in console.  But I can see the **state** and **props**.

<img width="796" alt="2016-04-21 9 19 14" src="https://cloud.githubusercontent.com/assets/8099731/14695175/294351f6-07a2-11e6-8973-6e426c4caff2.png">

**Comment by ngyikp** [comment] 2016-04-21 01:22
On the Console section, just to the left of "Preserve log" checkbox, make sure it is selected to the page you are inspecting, which is most likely `top`

**Comment by zhouhao27** [comment] 2016-04-21 02:36
Still doesn't work even after I selected the page.

<img width="1178" alt="2016-04-21 10 35 24" src="https://cloud.githubusercontent.com/assets/8099731/14696353/dc212cd0-07ac-11e6-8d98-f5811191a160.png">

**Comment by jaredly** [comment] 2016-04-21 05:22
I think it should say `top`, like this
![image](https://cloud.githubusercontent.com/assets/112170/14698716/ab8255c6-074e-11e6-83ff-033f9a4fdb73.png)

I just looked at that egghead page, and `$r` works fine. What version of Chrome are you on?

**Comment by zhouhao27** [comment] 2016-04-25 08:06
My version is 50.0.2661.75 (Mac).

**Comment by kevinSuttle** [comment] 2016-04-29 18:57
That fixed it @jaredly. Thanks!

**Comment by donboli** [comment] 2016-07-16 00:30
For those who are still struggling with this issue: The $r object is only accessible once the React devtool tab has been selected.

**Comment by cveld** [comment] 2016-08-10 14:38
Suggestion: from the scope of the extension itself, you could write out an instructional message when one tries to retrieve $r. Good that this is issue is present in this repository as a form of documentation / instruction anyways :)

**Comment by kevinSuttle** [comment] 2016-08-10 15:37
Great point @cveld. Now that's thinking like Elm. :)

**Comment by gaearon** [comment] 2017-02-15 18:09
Closing, as the mistake is related to doing it in the wrong iframe context.

>from the scope of the extension itself, you could write out an instructional message when one tries to retrieve $r

Not sure I understand how we could get access to the top-level context. Also doesn't feel right to pollute a different context than the one React app is running in.

**Closed by gaearon** 2017-02-15 18:09 UTC

**Comment by EduardJS** [comment] 2017-02-16 11:30
@gaearon It's not just the `iframe context`. I have been struggling a few days recently, up until I realsed I need to open `React` tab in `Developer Tools` first, then and only then, `$r` will be accessible in the console.

Hope it helps.

**Comment by gaearon** [comment] 2017-02-16 11:31
I'm a bit confused—what did you expect `$r` to be before it’s open? Since it corresponds to currently selected component to DevTools.

**Comment by EduardJS** [comment] 2017-02-16 11:33
Well, since I am new to this, and most likely others here asking, are just like me, i supposed `$r` was some globally instantiated variable, referring to `React` instance, just like `lodash` does with it's `_`.

I think that's what people miss out when trying to access it.

**Comment by gaearon** [comment] 2017-02-16 11:35
Oh, that's not what it means. It's more similar to how Chrome DevTools elements view gives you `$0`.

How did you learn about `$r` in the first place? I thought the message is only visible with DevTools open. Why did it occur to you that it might contain `React`, or that it exists?

**Comment by EduardJS** [comment] 2017-02-16 11:40
I saw it inside the `React` tab, on the upper right corner. 
What I did not realise ( until now, when I read your post ) is that `$r` actually reflects the currently selected component, and secondly, I did not realise that `$r` is instantiated by `DevTools`. Just thought it's a global instance of the `React` app. My bad I guess.

off-topic: any reason I am seeing all components named `e` after using webpack ( not using uglifyJS ) ? [screen here](http://i.imgur.com/lMErxG2.png)

**Comment by gaearon** [comment] 2017-02-16 11:45
>Basically, I thought it might contain React just because that message says $r in the console. So that was my first thought. Maybe that message should be altered to reflect the nature of that data.

Got it! 👍 
Any suggestions for a message that would be more descriptive but also fit there?

>off-topic: any reason I am seeing all components named e after using webpack ( not using uglifyJS ) ? screen here

If you're not using Uglify then I don't know. Maybe you're using `export` syntax with arrow functions and don't use a Babel plugin that gives them implicit names.

**Comment by EduardJS** [comment] 2017-02-16 11:54
> Any suggestions for a message that would be more descriptive but also fit there?

Hmm .. to be honest... maybe remove the current message from the right, add another gray divider, and write a message like `Selected component (<CompName>) is now accessible via $r in console`.

I think that gives you an idea that you need to select components in order to access them via `$r` in the console.

> If you're not using Uglify then I don't know. Maybe you're using export syntax with arrow functions and don't use a Babel plugin that gives them implicit names.

All components are exported via `export default class CompName extends React.Component`. At least that's a starting point to look at. Found this: `babel-plugin-transform-react-stateless-component-name`, maybe it helps.

**Comment by gaearon** [comment] 2017-02-16 11:55
No, that's some third party transform. I was referring to the default ones. Please provide a project reproducing the problem and file a new issue about this.

**Comment by EduardJS** [comment] 2017-02-16 12:00
Maybe something like this would be more descriptive ? [http://i.imgur.com/8H1znGo.png](http://i.imgur.com/8H1znGo.png)

**Comment by EduardJS** [comment] 2018-08-27 09:33
@arifmahmudrana You could simply open React DevTools and try.

**Comment by arifmahmudrana** [comment] 2018-08-27 13:17
@EduardJS I was mentioning that ```$r``` isn't available for stateless functional component which is logically also should be as they don't have any state & you can't change there props value also those are read only.

**Comment by arifmahmudrana** [comment] 2018-08-27 13:39
@EduardJS ```$r``` is the instance of component so yes you can access anything from that component but for stateless functional component you don't have any functions it itself is a function which is a shorthand for render function AFAIK. So ```$r``` isn't accessible through console unlike other class based components which isn't stateless functional component.

**Comment by EduardJS** [comment] 2018-08-27 13:49
@arifmahmudrana You wrote about two different things.

1st message: `functional or stateless `
2nd message: `stateless functional component`

My reply is entirely correct for your first message, as you mentioned one or the other, whereas in your latest reply you only mentioned "stateless functional" ( a functional component is by itself stateless, so in my opinion the naming sounds like .. a double negation ) either way, make up your mind.

Just to conclude, you're wrong, both functional as well as stateless components can have methods.

1. Functional ( mostly means a simple return - function )
2. Stateless ( can always be a fully fledged `React.Class` )
3. Stateless Functional ( back to number 1 description )

Hope this clears the confusion for you 👍

**Comment by gaearon** [comment] 2019-01-17 16:16
Re: function components — we're tracking them here https://github.com/facebook/react-devtools/issues/645.

**Comment by ATeam1** [comment] 2019-03-03 11:23
This issue was resolved when I hid the console side bar. When the console side bar was open the error was $r undefined........ ????

**Comment by carnophager** [comment] 2019-07-23 15:26
You need to select the "App" component in react dev tab and then "$r" receives a value.
