### ISSUE TITLE
stuck at Waiting for React to connect...

### ISSUE THREAD

**Issue by debugginator** [facebook/react-devtools#1180] opened 2018-10-09 16:21 UTC
Hi,
I'm constantly getting the popular message: "Waiting for React to connect...". I've tried a lot of "solutions" and workarounds, but didn't get far. 

**What I've tried:**
Use GenyMotion android emulator instead -> no difference.
Tried to toggle development mode on and of.
I've tried to run `adb reverse tcp:8097 tcp:8097`, but to no avail. 
The farthest I've gotten was when I adb-reversed the port and then entered my inet address + port on my device's developer menu > Dev Settings > Debug server host & port for device. When I did that the message changed to "Connecting to react...", but yet again, after waiting 15 minutes, I realized I was stuck.

React Native version: 56.0
Platform: Android, real device
Operating System: Linux
App created by CRNA, but ejected.

**Comment by thejsbro** [comment] 2019-02-11 08:49
Shake device to invoke developer menu. Click "Debug Remote JS". Now you can debug remotely with such tools as react-devtools, but i recommend react-native-debugger.

**Comment by bvaughn** [comment] 2019-08-19 23:07
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:07 UTC
