### ISSUE TITLE
Tab doesn't show in Chrome Beta

### ISSUE THREAD

**Issue by priteshgupta** [facebook/react-devtools#188] opened 2015-09-05 18:12 UTC
That is Chrome 46.

The React component is not in an iFrame.

**Comment by vslinko** [comment] 2015-09-07 11:04
![](https://api.monosnap.com/rpc/file/download?id=ehHtxUjkyqFlH6BXct3WFnXK3oHEFp)
Version 47.0.2503.0 canary (64-bit)

**Comment by chicoxyzzy** [comment] 2015-09-07 22:26
dupe of https://github.com/facebook/react-devtools/issues/184

**Comment by kassens** [comment] 2015-09-08 17:37
You can go to chrome://extensions and hit "Update extensions now" to update to version 0.14.1. Please, reopen if this is some other issues.

**Closed by kassens** 2015-09-08 17:37 UTC
