### ISSUE TITLE
Canvas render

### ISSUE THREAD

**Issue by RodrigoHamuy** [facebook/react-devtools#1320] opened 2019-03-28 21:30 UTC
**Steps to reproduce**

1. Open a project using inlet/react-pixi. Example: https://jzl912w7k9.codesandbox.io/
(Source: https://codesandbox.io/s/jzl912w7k9 )
2. Open React DevTools

**Expected behaviour**

Should show Mask and Image components.

**Current behaviour**

Only shows Canvas.

This happens with all the canvas renders I tried so far.

- react-three-fiber: https://9y8vkjykyy.codesandbox.io/
- react-pixi-fiber: https://9qyxrljyo.codesandbox.io/

This use to work at some point based on the screenshot in lzzimach/react-pixi docs: 

https://github.com/Izzimach/react-pixi/raw/master/docs/react-pixi-devshot.png

**Comment by bvaughn** [comment] 2019-08-19 23:06
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:06 UTC
