### ISSUE TITLE
Work with styled-components and Emotion authors/maintainers to get rid of <Context.Consumer>s

### ISSUE THREAD

**Issue by corysimmons** [facebook/react-devtools#1355] opened 2019-06-20 21:16 UTC
DevTools is great, and I know this isn't your responsibility, but if you guys could sync up and help educate the authors/maintainers of styled-components and Emotion on a nice way to get rid of the million-billion `<Context.Consumer>`s that pollute DevTools I would be soooooo happy.

I _think_ styled-components may have already fixed this with their latest release, and I _think_ that Emotion is working on it, but I'm not sure if they got stuck somewhere.

Just opening this to try to promote collab/discussion between DevTools and these libs, as this `<Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer>Hello World...` stuff really ruins the DevTools experience and with how nice DevTools v4 is, I would hate for that pollution to stick around.

**Comment by corysimmons** [comment] 2019-06-20 21:19
@probablyup @mitchellhamilton as the lead authors/maintainers of your projects, could you please let everyone know the current status of this `<Context.Consumer>` stuff? If it's fixed, what version? If it's in progress, what's left?

**Comment by probablyup** [comment] 2019-06-20 21:31
@corysimmons the styled-components v5 beta switched entirely over to the useContext hook, but we still ship the context consumer if people want to use it

**Comment by corysimmons** [comment] 2019-06-20 22:07
@probablyup So DevTools isn't polluted with any `<Context.Consumer><Context.Consumer><Context.Consumer><Context.Consumer>` stuff in v5?

**Comment by probablyup** [comment] 2019-06-20 22:13
Correct, see the announcement blog post for an example

**Comment by bvaughn** [comment] 2019-08-19 23:05
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:05 UTC

**Comment by corysimmons** [comment] 2019-08-21 00:35
These new devtools are soooo good. Thanks to everyone involved in making it. 🙇
