### ISSUE TITLE
Impossible to use on https website

### ISSUE THREAD

**Issue by Jessidhia** [facebook/react-devtools#923] opened 2017-10-19 05:52 UTC
It is not possible to connect to the `react-devtools` application when running via https; as connections to http websockets are not allowed on https pages.

This is most easily reproduced by setting up a project in `webpack-dev-server` and then trying to connect after starting it with the `--https` flag.

This issue is related to #881 but made worse in my case as the website I am currently working on _only works over https_ (better than the alternative :wink:); so running it in http-only mode just for development is not an option.

**Comment by gaearon** [comment] 2017-11-14 10:49
Do you have ideas on how to fix it?

**Comment by joshribakoff** [comment] 2018-02-04 02:56
Same, here's what I get when devtools is docked on the right on my mac

google chrome Version 63.0.3239.132 (Official Build) (64-bit)
React Developer Tools 3.1.0
react 16.2.0

![screen shot 2018-02-03 at 6 49 27 pm](https://user-images.githubusercontent.com/4021306/35773842-110fb362-0913-11e8-9314-6580d06c084f.png)

I am using http not https though. My page is served over a vagrant private IP address & loads JS from webpack on localhost:8080 (origins differ). No errors in console though & I would still expect this to work.

It communicates via window.__REACT_DEVTOOLS_GLOBAL_HOOK__, apparently? it seems to be defined when I check in console. Does it also use websockets or something? The only WS activity in the network tab seems to be from webpack dev server.

**Comment by Kovensky** [comment] 2018-02-05 01:24
@gaearon the only option I can think of is to have a way to support loading a (likely self-signed) certificate chain.

If the options are named `ca`, `cert` and `key` like they are in webpack's devserver settings, it should be easy to just reuse the same files. If the user has already trusted the certificate in order to be able to open the dev server on their browser, hopefully that trust is also extended to the standalone react dev tools.

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
