### ISSUE TITLE
[feature] Style information in the pane (and the ability to edit it as well)

### ISSUE THREAD

**Issue by DancingQualia** [facebook/react-devtools#66] opened 2015-02-04 12:44 UTC
If possible, the style information for each node like the DOM inspector, with the ability to edit in place.

**Comment by facebook-github-bot-7** [comment] 2015-08-04 18:05
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jaredly** [comment] 2015-08-05 18:00
We're definitely looking into this. It's implemented for React Native, but it would also be great to have on the web

**Comment by wkerswell** [comment] 2015-08-18 12:59
I have a theme for my console which targets class names for its styling. I was just going to style the react panel in the same way but there are no classes on any or the divs. Do you think the solution will be through css or another method?

**Comment by jaredly** [comment] 2015-08-18 16:14
So this issue is actually about using the react devtools to style your page, not styling the devtools.
However, we are planning to implement theming for the devtools as well, so that we can have a style for firefox, etc. It is likely to remain javascript-managed however. :/
One possibility would be the option of loading a theme into the devtools, which theme would be a JSON file or something...

**Comment by BLamy** [comment] 2016-09-22 16:08
Honestly, just the ability to copy-paste a chunk of style from the dev tools directly into an editor without having to convert everything to camel case would be amazing.

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
Labels: enhancement
