### ISSUE TITLE
Code minified with babili get the red icon

### ISSUE THREAD

**Issue by jameslnewell** [facebook/react-devtools#690] opened 2017-05-05 09:12 UTC
[`babili`](https://github.com/babel/babili) definitely doesn't give as-good results as `uglify`, but it works with the latest language features. Is it intentional that the plugin highlights it as not minified?

**Comment by ngyikp** [comment] 2017-05-05 13:44
Is there a sample minified output so someone else can verify?

The code logic to determine production/development/unminified is at https://github.com/facebook/react-devtools/blob/master/backend/installGlobalHook.js , it's probably tripping one of those conditions.

**Comment by gaearon** [comment] 2017-05-05 14:33
Please provide a reproducing example.

**Comment by bvaughn** [comment] 2019-08-19 23:28
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:28 UTC
