### ISSUE TITLE
Prevent Hooks to be closed when they change

### ISSUE THREAD

**Issue by afucher** [facebook/react-devtools#1335] opened 2019-04-18 17:17 UTC
I have a component that is using react hooks, and every time that I click on the component it changes the internal state. 
When I'm with the react-devtools opened on the component, it collapses the state and then I need to re-open it to check the new value.
It could be nice to keep it opened, so it will be easier to check the state.

**Comment by bvaughn** [comment] 2019-08-19 23:05
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:05 UTC
