### ISSUE TITLE
Column width keeps resetting every refresh

### ISSUE THREAD

**Issue by Svish** [facebook/react-devtools#1338] opened 2019-04-25 09:09 UTC
The column with Props and State in the React dev tools panel keeps resetting to an annoyingly narrow width. So on every page change/refresh, I get the "Connecting to React..." message, and then I have to manually drag the divider back out again.

Could the width of that column / position of that divider be remembered somehow? At least on a tab-by-tab basis? 🤔

![Capture](https://user-images.githubusercontent.com/142162/56723997-69190900-674a-11e9-9aa6-00832bad4fdb.PNG)

Might be related to #295, but that issue seemed a lot more involved. I just want that divider to stay where I place it between loads. 🙂

**Browser:** Firefox
**Version:** 3.6.0

**Comment by bvaughn** [comment] 2019-08-19 23:05
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:05 UTC
