### ISSUE TITLE
Tab doesn't show

### ISSUE THREAD

**Issue by davidgilbertson** [facebook/react-devtools#184] opened 2015-09-04 03:39 UTC
I'm using version 0.14 of the extension and the tab doesn't show.

![no tab](https://cloud.githubusercontent.com/assets/4443482/9676099/08f298e6-530a-11e5-822d-278c7796fbb0.PNG)

* Windows 10
* Chrome 44 and Chrome 47
* I closed/opened Chrome after the install
* I'm looking at a site on localhost that has react and has `window.React = React` if that's relevant.

Also, when I go to `chrome://extensions/` I see a message `This extension may have been corrupted.`. I click repair, close/open chrome, and the message returns.

**Comment by jaredly** [comment] 2015-09-04 04:24
Crazy. Try uninstalling / reinstalling the extension?

**Comment by davidgilbertson** [comment] 2015-09-04 07:22
Tried that no luck. But I've just tried on a different (Win 10) machine and it works in both Chrome stable and Canary. Check out the comments on the extension [review page](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?utm_source=chrome-ntp-icon), there are others with the same problem.

**Comment by mistadikay** [comment] 2015-09-04 10:00
same here, Chrome 45

**Comment by jsg2021** [comment] 2015-09-04 18:37
Was working for me yesterday, but today its no longer working. Chrome says "This extension may have been corrupted." I tried clicking repair, and deleting it and reinstalling it. Always gets auto disabled by Chrome. (i'm on the dev channel 47.0.2498.0 dev (64-bit)... i think it updated yesterday)

**Comment by weisjohn** [comment] 2015-09-04 23:46
This has happened for me on other extensions when Chrome has been pending updates. Not sure if that helps...

**Comment by liuyanghejerry** [comment] 2015-09-05 07:57
Happened for me too. The extension pages show the extension has already broken. Fix won't help, and reinstall won't either.
47.0.2498.0 dev-m (64-bit)

**Comment by FutureKode** [comment] 2015-09-06 14:43
Same here, click repair but no joy. Version 47.0.2498.0 dev (64-bit)

**Comment by paulirish** [comment] 2015-09-07 21:01
Heya folks, I've reported this upstream to the extensions team: https://code.google.com/p/chromium/issues/detail?id=529077
It looks like some extension verification code was changed recently so it looks like we're hitting a regression here. 

There was some work done after the `47.0.2498.0` version mentioned here. I am not sure if it resolves this bug, but would be eager to find out.  

Can someone who is hitting this bug try things in Chrome Canary? It'd be very useful to hear if the bug is still present in Canary.  Thanks yall

**Comment by paulirish** [comment] 2015-09-07 21:02
Heya folks, I've reported this upstream to the extensions team: https://code.google.com/p/chromium/issues/detail?id=529077
It looks like some extension verification code was changed recently so it looks like we're hitting a regression here. 

There was some work done after the `47.0.2498.0` version mentioned here. I am not sure if it resolves this bug, but would be eager to find out.  

Can someone who is hitting this bug try things in Chrome Canary? It'd be very useful to hear if the bug is still present in Canary.  Thanks yall

**Comment by chicoxyzzy** [comment] 2015-09-07 21:19
same here 47.0.2503.0 canary (64-bit)

**Comment by davidgilbertson** [comment] 2015-09-07 21:19
No joy. Updated chrome to `Version 47.0.2503.0 canary (64-bit)`, installed the extension again, the tab shows and works.

But then I closed Chrome and opened again: sad face. I get `This extension may have been corrupted` on the extensions page and no tab showing.

If I click repair, then go to a site everything works, until I close/open Chrome.

**Comment by paulirish** [comment] 2015-09-07 21:56
Okay, super helpful. Thanks guys. Star the chromium ticket and we should hear something tomorrow.

**Comment by paulirish** [comment] 2015-09-08 16:31
Update:

We [isolated the problem](https://code.google.com/p/chromium/issues/detail?id=529077#c5) on the Chrome side and it'll be fixed everywhere soon.

@spicyj has already done the workaround (https://github.com/facebook/react-devtools/commit/743f53261a69cb5cfc6cfa826c19e3665280208e) and will be pushing a new build to CWS very soon now!

**Comment by spicyj** [comment] 2015-09-08 16:36
I've just published a new version with the fix suggested in that thread.

Can everyone here try going to `chrome://extensions` and hitting "Update extensions now" to see if version 0.14.1 fixes the issue?

**Comment by chicoxyzzy** [comment] 2015-09-08 18:20
all is fine now

**Comment by spicyj** [comment] 2015-09-08 20:26
Closing, but if anyone is still experiencing this problem after updating please let us know!

**Closed by spicyj** 2015-09-08 20:26 UTC

**Comment by davidgilbertson** [comment] 2015-09-08 21:01
Working for me. Thanks all.

**Comment by gyzerok** [comment] 2016-03-04 06:26
@spicyj I've now hit the same problem. I do not know the details when it has happen because I haven't do any React development for several days.

**Comment by lebe-dev** [comment] 2016-08-31 15:27
OS: Win 10 latest x64
Chrome 52.0.2743.116

Reinstalling didn't help

**Comment by adrienne-vium** [comment] 2017-01-27 20:59
React tab still does not show up for me.
