### ISSUE TITLE
can't install react devtool extension with firefox developer build

### ISSUE THREAD

**Issue by rodney757** [facebook/react-devtools#872] opened 2017-08-20 00:51 UTC
using firefoxDeveloperEdition build 56.0b3 (64-bit), the option to install is disabled. 

I'm able to install with nightly build 57.0a1 (2017-08-19) (64-bit), beta build 56.0b3 (64-bit), and regular build 55.0.2 (64-bit)

**Comment by clarkbw** [comment] 2017-08-20 15:14
The option from the Firefox addons site?

**Comment by rodney757** [comment] 2017-08-20 15:29
yes. I'm able to install the .xpi file directly and everything seems to
work fine, but the firefox addons site doesn't allow the install,
complaining about unsupported firefox version.

I first filed a bug with firefox, but they said to raise the issue with the
extension dev

**Comment by clarkbw** [comment] 2017-08-21 15:20
It might be something with the compatibility listing in the addons site however since you are able to install it with the Beta build that doesn't make sense to me because DevEdition and Beta are the same version.

I'm using DE with the same version on Mac and I'm able to install via the addons site.

<img width="777" alt="screen shot 2017-08-21 at 8 19 26 am" src="https://user-images.githubusercontent.com/2134/29526100-918ed5c4-8649-11e7-8b73-7ce977777582.png">

**Comment by digitarald** [comment] 2017-09-08 21:08
@rodney757 can you still reproduce this?

**Comment by rodney757** [comment] 2017-09-08 21:30
yes,  but I didn't notice there is a "download anyway" button that isn't
very obvious that will allow me to install it.

The "Add to Firefox" button is disabled.

**Comment by bvaughn** [comment] 2019-08-19 23:16
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:16 UTC
