### ISSUE TITLE
Expanded trees blank out sections, basically unusable.

### ISSUE THREAD

**Issue by paularmstrong** [facebook/react-devtools#730] opened 2017-05-18 20:21 UTC
**Browser Versions:** Chrome 58 & Canary

**Site:** https://mobile.twitter.com

**Problem:** When attempting to navigate through a tree of components (very very nested), portions of the tree blank out and make the extension unusable.

<img width="900" alt="screen shot 2017-05-18 at 1 02 26 pm" src="https://cloud.githubusercontent.com/assets/33297/26221854/c702dd62-3bcc-11e7-8445-3a83e8e6d1d9.png">

**Notes:**
* I've disabled all other Chrome extensions
* Tried in multiple Chrome versions
* Tried in incognito

**Comment by bvaughn** [comment] 2017-05-20 08:09
More data points:
* OSX 10.12.4
* Chrome version 58.0.3029.110 (64-bit)

Latest devtools (built from master) on mobile.twitter.com:
<img width="1212" alt="screen shot 2017-05-20 at 10 06 59 am" src="https://cloud.githubusercontent.com/assets/29597/26274186/2a116856-3d44-11e7-95a8-5fb723f820b6.png">

Latest released devtools (from Chrome store):
<img width="1200" alt="screen shot 2017-05-20 at 10 08 54 am" src="https://cloud.githubusercontent.com/assets/29597/26274201/62f62b66-3d44-11e7-9f03-22feddf121ba.png">

**Comment by paularmstrong** [comment] 2017-05-20 13:51
@bvaughn Dock the dev tools to the side of the browser and try a bigger screen. When I undock and have devtools as a separate window, it seems to not happen. Only happens when devtools are a substantially large size and docked in the current window

Happens on both of my laptops while plugged into another screen.

**Comment by bvaughn** [comment] 2017-05-21 14:47
I'm traveling all week so I don't have a bigger screen to try on unfortunately. Maximizing the height of the devtools on my laptop's 15" screen is not sufficient to reproduce the bug though, no matter how deep I explore on Twitter Light.

My best guess at the moment is that it's some sort of browser rendering bug. (We don't do anything that should cause the behavior shown in your screenshot. It's just nested divs with color styles applied.)

I think this is edge-case enough that devtools are still pretty usable/useful 😁 but I'd love to figure out what's triggering this for you so we could add a fix. Any chance you could poke around in the Elements and Styles panels when this happens and see if there's any CSS properties that "fix" the issue when toggled off?

**Comment by bvaughn** [comment] 2017-06-01 21:18
Back in the states now (with an external monitor) but I'm still not able to reproduce the reported issue.

![screen shot 2017-06-01 at 2 17 05 pm](https://cloud.githubusercontent.com/assets/29597/26701210/0ad11884-46d5-11e7-85bb-9924bbada9de.png)

Tried docked and undocked, on external monitor, browsing pretty deep in the hierarchy.

Not sure what else to do with this one at present.

**Comment by bvaughn** [comment] 2017-06-01 21:38
PS Which version of react-devtools are you seeing this bug with? can you repro with latest (2.2.0+)?

**Comment by jmatsushita** [comment] 2017-06-19 14:51
Hi there,

I'm having exactly the same issue also on OSX. Using the latest extension version `2.3.3`. Chrome `58.0.3029.110 (64-bit)`. OSX `10.12.5 (16F73)`

I've recorded a performance session with the chrome dev of the chome dev, not sure if I'm reading this correctly but maybe the JS Heap is maxed out at which point nodes starts being dropped?

![image](https://user-images.githubusercontent.com/356097/27290635-2599a19e-550e-11e7-8f23-027b9023e7c0.png)

This might be a coincidence but I see the React tree start flashing as soon as I enter a node with a recompose HOC. Anyway, here's an animated gif which might give you some ideas!

![react_devtool](https://user-images.githubusercontent.com/356097/27290948-04402198-550f-11e7-8e93-6a88645debda.gif)

Let me know if you want a profiler session export.

Cheers,

Jun

**Comment by bvaughn** [comment] 2017-06-19 14:59
Hi @jmatsushita. Thanks for the extra context! Is the site you're viewing with DevTools accessible somewhere I can try to repro?

**Comment by paularmstrong** [comment] 2017-06-19 15:23
Maybe it makes a difference that I'm using a 24" HiDPI screen? (2x Dell P2715Q) @jmatsushita Are you using something similar?

**Comment by jmatsushita** [comment] 2017-06-19 15:27
Ha! @paularmstrong indeed, going to the laptop screen addresses the problem!

@bvaughn Not super easily right now... In a week or so probably! :)

**Comment by jmatsushita** [comment] 2017-06-19 15:30
Screen caps speaks louder than words :

![react_devtool_2](https://user-images.githubusercontent.com/356097/27292823-da7a79fc-5514-11e7-8c9b-b363bc3f72c0.gif)

**Comment by alexkrolick** [comment] 2017-07-10 17:12
This happens to me as well. The fastest way to reproduce is to inspect a DOM node, then switch to the React tab to instantly expand the tree to that position.

**Comment by bvaughn** [comment] 2017-07-10 17:19
@alexkrolick: Just to confirm, when that happens, are you sure that the tree isn't just scrolled to the incorrect horizontal position? I _have_ seen that (and we have #746 opened to fix that).

**Comment by alexkrolick** [comment] 2017-07-10 17:22
Yeah, it totally glitches out - see before/after below for trying to hover the devtools titlebar, plus the extra white areas where nodes should be.

![62006242-ced3-435e-9342-a2745e69ce4b](https://user-images.githubusercontent.com/1571667/28030643-723a1b7c-6559-11e7-9be6-5f7379b6be26.png)
![0fffd469-dec0-413d-97a9-de62e1bb22aa](https://user-images.githubusercontent.com/1571667/28030645-725c5fb6-6559-11e7-92f1-7209348e2c57.png)

**Comment by alexkrolick** [comment] 2017-07-10 17:41
It's actually happening on one of my coworker's screen right now, too 😱

**Comment by bvaughn** [comment] 2017-07-10 18:06
When it does this, can you inspect the React DevTools panel (using the "Elements" tab in another Chrome DevTools panel) and confirm if the nodes are _missing_ or if they're there but not rendered? My guess is that they're present, but not being rendered by the browser for some reason, but I have been unable to reproduce this bug so far.

**Comment by alexkrolick** [comment] 2017-07-10 19:23
![kapture 2017-07-10 at 12 21 20](https://user-images.githubusercontent.com/1571667/28035709-7117e5ec-656a-11e7-829f-dc220aedd4d3.gif)
![kapture 2017-07-10 at 12 20 22](https://user-images.githubusercontent.com/1571667/28035710-711c046a-656a-11e7-8bf1-807d948cc5f9.gif)

**Comment by bvaughn** [comment] 2017-07-10 19:35
That's interesting! I suspected this was some sort of browser/rendering bug.

**Comment by mbixby** [comment] 2017-07-25 20:12
Reverting to earlier versions of Chrome might work too, it didn't happen before a certain update.

**Comment by 8-bitTom** [comment] 2017-08-24 18:43
+1 I'm having the Same issue: 
Chrome Version 60.0.3112.101
OSX: 10.12.6
4k monitor: browser any width

**Comment by bvaughn** [comment] 2019-08-19 23:24
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:24 UTC
