### ISSUE TITLE
"Highlight Updates" doesn't "see" changes made through the context API

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#988] opened 2018-02-18 19:58 UTC
I don't see any highlighting with that option. I'd expect children of context consumers to be highlighted.

**Comment by gaearon** [comment] 2018-03-23 22:26
I looked a bit more at this. It's unrelated to context API: Highlight Updates doesn't do anything for host or functional components. I think we need to tweak its logic because it's already a bit misleading, and will become more so.

**Comment by scriptfoundry** [comment] 2018-07-13 07:50
I came across this same problem specifically with the Context API and have a test case of sorts (https://codesandbox.io/s/504qzw02nl). I see that *any* child of a `Provider` gets highlighted, except `PureComponents`, which never do (even when their contents mutate). First, (since I may be an idiot here), Dan @gaearon,   am I doing this right? Second, does this indicate that highlighting doesn't reflect an actual re-rendering like the docs suggest, but rather just that it just reflects what`shouldComponentUpdate()` says? Or something else?

**Comment by bvaughn** [comment] 2019-08-19 23:13
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:13 UTC
