### ISSUE TITLE
Add support for running devtools hook code through Babel 

### ISSUE THREAD

**Issue by davidwkeith** [facebook/react-devtools#1056] opened 2018-06-28 16:03 UTC
Currently we are supporting a NW.js application that is pegged at version 0.12.3 to support a NPAPI plugin. That means we are running in Chromium 41. We can't use the React Dev Tools standalone app because the hook code uses ECMAScript features that are not supported on such an old browser.

I think the cleanest solution would be to put a hook in the code server to allow this, that way we could embed the code, specifying the engine to run on, something like:

```html
<script src="http://localhost:8097?target=chrome,41"></script>
```

The query string above would translate to a dynamic Babel config where the presets included `[env, {targets: { chrome: '41' }}]` and the hook code would be transformed prior to serving.

If this seems like an acceptable solution, our team can start working on a PR. If there is a better way to solve this (or an existing solution that I just can't find) I am more than happy to work with that.

**Comment by bvaughn** [comment] 2019-08-19 23:12
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:12 UTC
