### ISSUE TITLE
react-devtools won't open

### ISSUE THREAD

**Issue by nbonfils** [facebook/react-devtools#1083] opened 2018-08-09 13:32 UTC
I'm trying react-native here, and following the instructions [here](https://facebook.github.io/react-native/docs/debugging#react-developer-tools) I installed the standalone app (since it doesn't seem to work inside chromium browser).
I had no problem or whatsoever during install but the when I try to run it it simply doesn't start... no errors no nothing, so I think I might need some help here.

this is the log for the sake of it...
``` bash
~
➔ react-devtools

~
➔
```

The only error I could manage to opbtain was when following the instruction to use react-devtools not globally but inside my project with `npm run react-devtools`, and here is the log:

``` bash
~
➔ npm run react-devtools

> reactNativeTest@0.0.1 react-devtools /home/nature/junk/reactNativeTest
> react-devtools

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! reactNativeTest@0.0.1 react-devtools: `react-devtools`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the reactNativeTest@0.0.1 react-devtools script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nature/.npm/_logs/2018-08-09T13_04_49_554Z-debug.log
```

Maybe I should also mention that I'm using the method with adb over network.

Thanks !

**Comment by AlexLexo** [comment] 2018-08-15 07:38
I think I have something similar.

Installed as per the docs and, as above, "I had no problem or whatsoever during install but the when I try to run it it simply doesn't start... no errors no nothing" and I also was able to obtain an error when running it through an NPM script (I have tried installing locally via --save-dev as well as globally but the result is the same - it doesn't run at all.)

I am running Ubuntu 18.04.1 LTS and react-devtools 3.2.3.

Here is the error log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'devtools' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'predevtools', 'devtools', 'postdevtools' ]
5 info lifecycle qapp@0.0.8~predevtools: qapp@0.0.8
6 silly lifecycle qapp@0.0.8~predevtools: no script for predevtools, continuing
7 info lifecycle qapp@0.0.8~devtools: qapp@0.0.8
8 verbose lifecycle qapp@0.0.8~devtools: unsafe-perm in lifecycle true
9 verbose lifecycle qapp@0.0.8~devtools: PATH: /usr/share/npm/bin/node-gyp-bin:/home/alex/projects/q-app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/alex/Android/Sdk/tools:/home/alex/Android/Sdk/tools/bin:/home/alex/Android/Sdk/platform-tools:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/alex/Android/Sdk/tools:/home/alex/Android/Sdk/tools/bin:/home/alex/Android/Sdk/platform-tools
10 verbose lifecycle qapp@0.0.8~devtools: CWD: /home/alex/projects/q-app
11 silly lifecycle qapp@0.0.8~devtools: Args: [ '-c', 'react-devtools' ]
12 info lifecycle qapp@0.0.8~devtools: Failed to exec devtools script
13 verbose stack Error: qapp@0.0.8 devtools: `react-devtools`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid qapp@0.0.8
15 verbose cwd /home/alex/projects/q-app
16 error Linux 4.15.0-30-generic
17 error argv "/usr/bin/node" "/usr/bin/npm" "run" "devtools"
18 error node v8.10.0
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error qapp@0.0.8 devtools: `react-devtools`
24 error spawn ENOENT
25 error Failed at the qapp@0.0.8 devtools script 'react-devtools'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the qapp package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     react-devtools
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs qapp
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls qapp
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by agustinch** [comment] 2019-02-28 15:42
I have the same problem. Has anyone solved this problem?

**Comment by Rexam14** [comment] 2019-03-05 13:41
Same problem here. I tried to run `react-devtools` from my project folder (even if it shouldn't be necessary) but it simply won't start, returning the terminal control to the user. No errors, warnings, nothing. Didn't find a workaround or a fix yet.

**Comment by devdanoliveira** [comment] 2019-03-07 22:09
I have the same problem to run devtools with react native windows. All setup are run on Windows 10. I installed react-devtools but chrome devtools is not enabled

**Comment by thought7878** [comment] 2019-03-18 02:51
I have the same problem.I'm looking for solution

**Comment by thought7878** [comment] 2019-03-18 03:37
you can use this [React Native Debugger](https://github.com/jhen0409/react-native-debugger) ,intead of react-devtools

**Comment by melvsparks** [comment] 2019-04-23 21:33
I'm having the same problem

**Comment by StartupSam** [comment] 2019-05-01 01:56
Same problem - seems like there's no solution yet?

**Comment by StartupSam** [comment] 2019-05-01 02:21
> you can use this [React Native Debugger](https://github.com/jhen0409/react-native-debugger) ,intead of react-devtools

I tried using this, but it seems to have the same problem of refusing to start (with no error messages).

**Comment by StartupSam** [comment] 2019-05-01 02:22
I also tried the full npm cache clean, delete packages etc. just in case, but the issue persists.  :'(

**Comment by StartupSam** [comment] 2019-05-01 04:11
For those who come come later: A solution on this thread worked for me: [https://github.com/facebook/react-devtools/issues/1097](https://github.com/facebook/react-devtools/issues/1097)

**Comment by saeedeyvazy** [comment] 2019-05-03 16:36
This solved my issue
`sudo apt install libgconf-2-4`

**Comment by apiep** [comment] 2019-05-10 08:06
I am facing the same issue, yesterday it was running fine and open. But today, it is silently close, with no warning or error.
When I try to install it locally, and run it with `node .\node_modules\react-devtools\bin.js` I get this error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\Me\\AppData\\Local\\nvs\\default\\node.exe',
1 verbose cli   'C:\\Users\\Me\\AppData\\Local\\nvs\\default\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'tools' ]
2 info using npm@6.9.0
3 info using node@v8.15.1
4 verbose run-script [ 'pretools', 'tools', 'posttools' ]
5 info lifecycle @~pretools: @
6 info lifecycle @~tools: @
7 verbose lifecycle @~tools: unsafe-perm in lifecycle true
8 verbose lifecycle @~tools: PATH: Removed
9 verbose lifecycle @~tools: CWD: C:\Users\Me\code\react-native-sample
10 silly lifecycle @~tools: Args: [ '/d /s /c', 'node ./node_modules/react-devtools/bin.js' ]
11 silly lifecycle @~tools: Returned: code: 1  signal: null
12 info lifecycle @~tools: Failed to exec tools script
13 verbose stack Error: @ tools: `node ./node_modules/react-devtools/bin.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Me\AppData\Local\nvs\node\8.15.1\x64\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Me\AppData\Local\nvs\node\8.15.1\x64\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd C:\Users\Me\code\react-native-sample
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Users\\Me\\AppData\\Local\\nvs\\default\\node.exe" "C:\\Users\\Me\\AppData\\Local\\nvs\\default\\node_modules\\npm\\bin\\npm-cli.js" "run" "tools"
18 verbose node v8.15.1
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ tools: `node ./node_modules/react-devtools/bin.js`
22 error Exit status 1
23 error Failed at the @ tools script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Node version: v8.15.1
NPM version: 6.9.0
react-devtools version: 3.6.1
Operating System: Windows 10

**Comment by michaellee8** [comment] 2019-05-20 04:06
@saeedeyvazy Thank you so much dude, this one solved my issue.

**Comment by melvsparks** [comment] 2019-06-07 19:48
Any update on this? I still am unable to use the React-devtools stand alone app on Windows 10 with React Native. It just sits there and hangs, nothing opens up. 

No errors when ran:
1. From the project with `npm run react-devtools`
2. From outside the project with `react-devtools`

**Comment by saeedeyvazy** [comment] 2019-06-09 07:30
> @saeedeyvazy Thank you so much dude, this one solved my issue.

I'm so happy!

**Comment by shaqal** [comment] 2019-06-23 05:42
Facing the same issue. Windows 10. Please halp.

**Comment by melvsparks** [comment] 2019-07-02 19:02
I installed react devtools again (version 3.6.1) using `npm i -g react-devtools` and it's now working

**Comment by bvaughn** [comment] 2019-08-19 23:10
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:10 UTC
