### ISSUE TITLE
Icon in firefox looks out of place

### ISSUE THREAD

**Issue by domoritz** [facebook/react-devtools#1356] opened 2019-06-21 00:50 UTC
It would be sweet if the React Devtools icon looked more like the other icons in the Firefox dev tools. 

<img width="438" alt="Screen Shot 2019-06-20 at 17 49 44" src="https://user-images.githubusercontent.com/589034/59890018-e1373000-9383-11e9-9c41-d91609f7c8ba.png">

**Comment by bvaughn** [comment] 2019-08-19 23:05
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:05 UTC
