### ISSUE TITLE
How to display a label from useState hook

### ISSUE THREAD

**Issue by togakangaroo** [facebook/react-devtools#1334] opened 2019-04-17 15:04 UTC
Picking up [on this comment](https://github.com/facebook/react-devtools/issues/1215#issuecomment-479943810) about how to get a nice semantic label displaying from a bit of state created by the `useState` function.

Currently, when we `useState` all you can see in devtools is something like this. 

![Just the non-semantic clabel "state"](https://user-images.githubusercontent.com/66150/56298779-638f4380-60f8-11e9-98a7-6a8b06a95ec2.png)

Obviously that's not great but how to reliably show a label there given that the runtime doesn't necessarily have that context without introspecting over the function body itself (and even then its not perfect)

I have a few suggestions.

1. Definitely the api should probably be changed to allow passing in a label as a second parameter to `useState` - make it optional but have the option
2. At least show the invocation number if there's more than one `useState` in a render - so `State[0]` for the first usage of `useState` `State[1]` for the second, etc
3. If the state is an object with a single key maybe consider that as the label? If I do `setSomeBitOfState({ foo: someVal })` then by all means, let's have `foo` be immediately visible!
4. This one is a stretch but let's say `useState` is called within a custom hook, then maybe when react devtools is running, the first time a given `useState` is called you can walk the callstack, grab the function name that contains `useState` and - if its not the `render` method - use that as the label?

Between the above 4 there should be enough there to cover 80% of cases, what do you think?

**Comment by fanny** [comment] 2019-07-12 12:47
the community has created some initiatives in this direction, [this comment](https://github.com/facebook/react-devtools/issues/1305) may be useful for you

**Comment by bvaughn** [comment] 2019-08-19 23:05
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:05 UTC
