### ISSUE TITLE
React-Devtools 2.5.2 Doesn't Work on Firefox 58

### ISSUE THREAD

**Issue by kbsletten** [facebook/react-devtools#970] opened 2018-01-24 01:20 UTC
The chrome extension works just fine, but the Firefox one just says "This page doesn't appear to be using react". I was able to use the extension not that long ago (maybe pre-57?). I've tried on my macbook and on a windows 10 parallels virtual machine with no dice.

**Comment by ngyikp** [comment] 2018-01-26 14:36
The Firefox extension is working for me on a clean Firefox 58 for https://reactjs.org

What is the website URL you are trying to inspect?

![parallels picture 3](https://user-images.githubusercontent.com/6135313/35444205-b5741bb8-02e8-11e8-86c0-46a62cccc073.png)

**Comment by kbsletten** [comment] 2018-01-27 04:43
Well, the URL is `http://vmhost:8081` which is just a hosts file redirect to a local iisexpress project in a Windows 10 parallels instance. Chrome works just fine, but FF can't detect react. I can look at anything that could help you out, how does the plugin scan the page for react?

**Comment by kbsletten** [comment] 2018-01-27 04:46
Sorry, actually I've also tested from within the Windows 10 instance (FF 58) and `http://localhost:8080` as well. No dice, but Chrome picks it up just fine.

**Comment by kbsletten** [comment] 2018-01-27 05:06
I found this line of code in your extension (I'm not a extension dev, but I tried following from the manifest out) and it may be the problem:

https://github.com/facebook/react-devtools/blob/master/shells/webextension/src/main.js#L21

I threw this expression in the inspector:

```
!!(
    Object.keys(window.__REACT_DEVTOOLS_GLOBAL_HOOK__._renderers).length || window.React
  )
```

On Chrome Version 63.0.3239.132 (Official Build) (64-bit):

```
true
```

On Firefox 58.0 (64-bit):
```
TypeError: window.__REACT_DEVTOOLS_GLOBAL_HOOK__ is undefined
```

So I tried just the second half on Firefox:
```
window.React
```

and got:
```
Object { Children: {…}, Component: Component(), PureComponent: PureComponent(), unstable_AsyncComponent: AsyncComponent(), Fragment: Symbol(react.fragment), createElement: createElementWithValidation(), cloneElement: cloneElementWithValidation(), createFactory: createFactoryWithValidation(), isValidElement: isValidElement(), version: "16.2.0", … }
```

**Comment by cpruitt** [comment] 2018-02-23 16:23
Not sure if it's helpful but I'm seeing the same thing using Firefox 58 on Mac OS (10.13.3), but not for all sites. React dev tools are enabled for both Chrome and Firefox if I inspect https://reactjs.org/ but are not enabled for Firefox if I visit https://www.airbnb.com/. They are enabled for Airbnb in Chrome only.

Full disclosure: I am trying out React and the React Developer Tools for the first time so I wouldn't completely discount user error on my part.

**Comment by Morikko** [comment] 2018-03-22 16:22
I confirm what @cpruitt said, but with Firefox 59 on Fedora 27. 

Also I am developing web-extension that includes js libraries locally.
```html
  <script src="/lib/js/react.production.min.js"></script>
  <script src="/lib/js/react-dom.production.min.js"></script>
```
Both Chromium and Firefox are telling me that my pages are not React pages.

**Comment by zhoutuo** [comment] 2018-05-10 21:34
Also can confirm, some pages only work with chrome not firefox 59.0.3

**Comment by rkstar** [comment] 2018-05-28 14:59
confirmed in firefox nightly `62.0a1 (2018-05-28) (64-bit)` as well. react-devtools **3.2.3**. console shows [the same as this comment](https://github.com/facebook/react-devtools/issues/970#issuecomment-360960757)

**Comment by EpicOrange** [comment] 2018-09-18 17:29
Same issue:

<img width="715" alt="screen shot 2018-09-18 at 10 28 31" src="https://user-images.githubusercontent.com/6273197/45705131-a15dc680-bb2d-11e8-9dff-1578195c734d.png">

<img width="998" alt="screen shot 2018-09-18 at 10 26 16" src="https://user-images.githubusercontent.com/6273197/45705088-81c69e00-bb2d-11e8-8073-f41a2b168cf2.png">

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
