### ISSUE TITLE
Multiple <option> children causes TypeError: Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by mik01aj** [facebook/react-devtools#248] opened 2015-10-07 10:18 UTC
When I open react-devtools, I see this:

![screenshot 2015-10-07 12 14 45](https://cloud.githubusercontent.com/assets/3027415/10334830/1c37805e-6ced-11e5-8b10-9b5f394b9792.png)

After clicking the button, it fails with this error:

![screenshot 2015-10-07 12 16 47](https://cloud.githubusercontent.com/assets/3027415/10334856/4de4c2e2-6ced-11e5-92a9-dd221796b5a1.png)

I tried closing the tab and opening everything again, but the problem persists.

My page uses React `0.14-rc1`. I tried react-devtools on another page that uses react `0.13` and it works fine (in spite of the warning about version).

**Comment by mik01aj** [comment] 2015-10-07 10:37
Possible cause, although weird, might be that [React Headroom doesn't work with React 0.14-rc1](https://github.com/KyleAMathews/react-headroom/issues/12).

**Comment by mik01aj** [comment] 2015-10-09 15:41
I just discovered this does not happen only for my app. I get the same error on https://react-bootstrap.github.io/components.html.

**Comment by jaredly** [comment] 2015-10-09 16:48
Oh! Are you using stateless function components? That might be the issue

**Comment by mik01aj** [comment] 2015-10-10 05:18
You mean the old form from React 0.12? I don't. But maybe react-bootstrap does.

**Comment by mrm007** [comment] 2015-10-21 00:46
@mik01aj [stateless components][st] is a new feature from React 0.1

@jaredly I get the same error, and I'm using stateless functional components

[st]: http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components

**Comment by joelburget** [comment] 2015-10-26 23:51
I just got the same error, but with React 0.13.3, so obviously no stateless components. Possibly useful stack trace: https://gist.github.com/joelburget/02e94bae85aa75b60e58

**Comment by kuy** [comment] 2015-11-17 09:14
The error is occurred In backend/getData.js file at [line 43](https://github.com/facebook/react-devtools/blob/master/backend/getData.js#L43)

```
	  } else if (element._renderedChildren) {
	    children = childrenList(element._renderedChildren);
	  } else if (element._currentElement.props) {             <=== ERROR
	    // This is a native node without rendered children -- meaning the children
	    // prop is just a string.
	    children = element._currentElement.props.children;
	  }
```

When I put a breakpoint here, `element` parameter is plain String object.
I guess this mean that the caller of `getData()` function passes it as DOM text node.

Please see following two snippets.

**NOT WORK**
```
              <select defaultValue={level} onChange={e => onChangeLevel(e.target.value)}>
                {_.range(LEVELS).map(n =>
                  <option key={n} value={n}>
                    Level {n + 1}
                  </option>
                )}
              </select>
```

**WORK**
```
              <select defaultValue={level} onChange={e => onChangeLevel(e.target.value)}>
                {_.range(LEVELS).map(n =>
                  <option key={n} value={n}>
                    <span>Level {n + 1}</span>
                  </option>
                )}
              </select>
```

Finally, `getData()` function should handle DOM text node correctly.

**Comment by kuy** [comment] 2015-11-17 09:18
Forgot to write my environment.

+ Mac OS X 10.10.5
+ Chrome 46.0.2490.86 (64-bit)
+ Firefox Developer Edition (44a2...?)
+ React 0.14.2 + Redux 3.0.4

**Comment by mik01aj** [comment] 2015-11-17 11:31
Whoa, this looks really weird. Why does the additional `<span>` change anything?... :dizzy_face:

**Comment by kassens** [comment] 2015-11-17 17:50
This is a great pointer. `option` is a special case in React: https://github.com/facebook/react/blob/master/src/renderers/dom/client/wrappers/ReactDOMOption.js#L74

**Comment by kuy** [comment] 2015-11-18 07:53
I attempt to fix this issue on [`bugs/fix-248`](https://github.com/kuy/react-devtools/tree/bugs/issue-248) branch on my forked repo. Please check [diff](https://github.com/kuy/react-devtools/commit/edfc13331a8fe061aaf21eced98b59ae1eedf918).
Since `getData()` function receives a String object as `element` parameter, now it handles them as text nodes.
Please comment on this, because I don't know this is a right way :smiley:

**Comment by mik01aj** [comment] 2015-11-18 10:35
I would test it on my page, but I don't know how to install the forked version. Maybe just someone could check it it doesn't break on https://react-bootstrap.github.io/components.html?

**Comment by goodwink** [comment] 2015-11-20 12:30
This seems to work on the page I was having this same problem with. :+1:

**Comment by kassens** [comment] 2015-11-20 17:20
@spicyj, @jimfb: This is caused by the way `ReactDOMOption` implements `getNativeProps` to have a custom flatten for children (only text or numbers). Do you see a way to re-use some of the ReactDOMComponent magic to normalize the props here?

**Comment by spicyj** [comment] 2015-11-20 19:44
Not offhand. Maybe better to not try to correlate .props.children with ._renderedChildren.

**Comment by adampatterson** [comment] 2016-02-01 00:50
@kuy Putting my{values} in a span tag inside the option tag fixed the issue for me. 

Thanks! I wasted a lot of time on this.

**Comment by manuscript80** [comment] 2016-02-11 01:58
Weird, I tried to use a span tag inside my <option> tag and I got this warning message "Warning: Only strings and numbers are supported as <option> children."

I'm facing the same problem described above.  Any idea when this fix will be merged?

**Comment by realseanp** [comment] 2016-02-15 00:45
@manuscript80 i wouldn't worry about wrapping your stuff in a span within an option. This is a bug with react-devtools not your code. But yes, the error is unsightly and not having access to the dev tools is not helpful either.

**Closed** 2016-04-20 18:46 UTC
