### ISSUE TITLE
Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by MitchWeiss** [facebook/react-devtools#338] opened 2016-03-01 10:16 UTC
I'm attempting to build a Select dropdown and populate the input fields using a for loop. 

``` 
import React, { Component } from 'react';

export default class Test extends Component {
  render() {
    let options = [];
    for (let i=2; i < 20.5; i += 0.5){
      options.push(<option value={i*60} key={i}>{i} hours</option>)
    }
    return (
      <select>
        {options}
      </select>
    )
  }
}
```

The `{i} hours` section causes an `Uncaught TypeError: Cannot read property 'props' of undefined` error message in backend.js on line 8441. Changing it to a fixed string prevents the error.

I have created a standalone gist to make it easy to reproduce the error. 

https://gist.github.com/MitchWeiss/3a6b8b7643999b07f599

**Comment by spicyj** [comment] 2016-03-02 19:44
Dupe of #248.

**Closed by spicyj** 2016-03-02 19:44 UTC
