### ISSUE TITLE
Props rigth lateral bar is gone.

### ISSUE THREAD

**Issue by snow-dev** [facebook/react-devtools#1110] opened 2018-08-22 17:37 UTC
When I select an element on tree, rigth props bar disappear, and i cant make visible again.
![initial_reactdevtool](https://user-images.githubusercontent.com/2772989/44480048-e3b3e680-a607-11e8-998c-bbfd9d9476d6.png)
![final_reactdevtool](https://user-images.githubusercontent.com/2772989/44480152-2ecdf980-a608-11e8-8046-a3971bb153d4.png)

**Comment by iamdustan** [comment] 2018-08-22 17:52
Duplicate of #1107. Tracked in #1099.

<img width="688" alt="screen shot 2018-08-22 at 1 50 48 pm" src="https://user-images.githubusercontent.com/227879/44480891-6477e000-a612-11e8-81d9-2a479e1ee145.png">

**Closed** 2018-08-22 18:14 UTC
Labels: duplicate

**Comment by bvaughn** [comment] 2018-08-22 18:35
Fixed via #1111

**Comment by gaearon** [comment] 2018-08-23 14:04
Submitted fixes to Chrome and FF stores.

**Comment by bvaughn** [comment] 2018-08-24 01:30
Thanks Dan! 🙇
