### ISSUE TITLE
[Relay] No queries logged with Relay.Environment

### ISSUE THREAD

**Issue by Zn4rK** [facebook/react-devtools#571] opened 2017-03-02 14:33 UTC
I can't seem to get any Relay Queries to be picked up by the Relay plugin if I'm using `Relay.Environment` instead of `Relay.Store`

```javascript
// ... imports
const env = new Relay.Environment();
env.injectNetworkLayer(new Relay.DefaultNetworkLayer('http://example.com/graphql'));

ReactDOM.render(
    <Router
        history={history}
        routes={routes}
        render={applyRouterMiddleware(useRelay)}
        environment={env}
    />,
    document.getElementById('root')
);

env.commitUpdate(new TestMutation({data: 'data'}));
```

Results in "No Relay Queries logged", but if I switch to:

```javascript
const env = Relay.Store;
// ... same as the above
```

...I can see the query get logged under the Relay-tab. 
The Console shows that the Mutation gets executed either way. 

I'm using `v2.0.12` (Google Chrome Extension) of `react-devtools` and `0.10.0` of `react-relay` (and `0.13.5` of `react-router-relay` if that matters). I'm using the default setup of create-react-app (`0.9.3`) and have not made any modifications to the webpack config more than added Relay.

Am I missing something?

**Comment by gaearon** [comment] 2017-03-08 22:20
Nobody is currently maintaining the Relay integration, so unfortunately you’re on your own here. I would suggest looking into [how the plugin works](https://github.com/facebook/react-devtools/tree/master/plugins/Relay) and figuring out what’s wrong. It’s likely somebody didn’t just add a hook for this.

**Comment by mormahr** [comment] 2017-03-10 00:52
Maybe this is because Relay.Store uses the/a default environment and the relay integration always holds on to that default one, even if you create a new one.

**Comment by Zn4rK** [comment] 2017-03-10 08:03
I tried to figure out what's happening, and it's definitley related to the [Relay.Store singleton](https://github.com/facebook/relay/blob/ea03e9ba6bc5763c18b9745eeab375087507307e/src/tools/RelayInternals.js). If I manually set the DefaultStoreData and NetworkLayer on the _relayInternals I get closer, but the NetworkLayer doesn't get decorated with emitters (in [installRelayHook.js](https://github.com/facebook/react-devtools/blob/master/plugins/Relay/installRelayHook.js)), and the requests are not picked up by the rest of the plugin.

I don't really know how to proceed from here. Until Relay2 is shipped, [I have a feeling](https://github.com/facebook/relay/issues/1053) that we won't see any major activity on the Relay Plugin.

The Relay.Renderer knows about the Environment passed to it, so maybe that's a possible way.

**Comment by gaearon** [comment] 2017-04-19 15:37
Relay Modern is announced / published now, I think.

**Comment by mormahr** [comment] 2017-04-19 19:02
I still think about doing this (because i have much use for it), but currently don't have the time to. This won't get easier with Relay 1.0, but it won't be harder either. There would have to be some way to find all created Stores, but i'm not sure how to do that without either: Modifying the relay store constructor (bad) or let the user manually set the store to some kind of global or otherwise registering it (still bad). 

Maybe we can move from the identified react tree. It should be possible to get the environment from every relay container in the react tree.

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
Labels: bug, difficulty: medium, good first bug
