### ISSUE TITLE
Component tree does not show all props shown in sidebar

### ISSUE THREAD

**Issue by wearhere** [facebook/react-devtools#1361] opened 2019-07-17 21:01 UTC
![](https://dzwonsemrish7.cloudfront.net/items/120o2T470C432i0G1v1t/Image%202019-07-17%20at%201.59.51%20PM.png)

Very glad to provide additional information if someone lets me know what might be helpful. It'd be a bit difficult to extract this exact component setup from my current project otherwise I'd provide a repro project. I'm wondering if there's a simple explanation like "oh the component tree only shows the first `n` props" or "oh the component tree only shows certain types of props".

On the latter hypothesis there, I note that the props missing in the tree are an object and a function, perhaps those are currently considered too complex to represent in the tree?

The problem (IMO) with showing props in the sidebar, but not in the tree, is that it's common for me to scroll upward through the tree to try to find where an event handler is registered. If I have to click a component to get it to show a function prop like `onSelectValue`, that makes my search for the handler more difficult.

My React DevTools version (the version of the Chrome extension) is 3.6.0.

**Comment by bvaughn** [comment] 2019-08-19 23:04
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:04 UTC
