### ISSUE TITLE
[React Native] Include react tags in inspector UI

### ISSUE THREAD

**Issue by rigdern** [facebook/react-devtools#439] opened 2016-10-03 23:54 UTC
When seeing a native view in the debugger, I do not know of a good way to map between that native view and the JavaScript view that generated it.

A couple of changes to the devtools could be useful in this scenario:
- When inspecting a view, include its tag in the UI. This would give me a clue as to which native view I'm looking at.
- Allow searching by react tag. That way, if I encounter a native view in the debugger, I can quickly see which JavaScript view it corresponds to.

**Comment by gaearon** [comment] 2017-02-15 17:24
I have an alternative proposal. Let's include it on the *right* pane, next to props, state, context, etc, and only show it when it exists. This way it's a bit less intrusive but still useful to those who look for it.

**Comment by rigdern** [comment] 2017-02-15 19:53
@gaearon Thanks for the suggestion. Compared to my proposal, you won't be able to see several react tags at a glance but this might be useful enough. I'll think about it.

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
