### ISSUE TITLE
Android - unable to connect to remote debugger

### ISSUE THREAD

**Issue by nicodmf** [facebook/react-devtools#862] opened 2017-07-30 08:48 UTC
versions : 
 - native 4.3 4.6
 - OS : linux debian 9 
 - react-devtools : standalone 2.5.0
 - device : emulator or samsung S6

With many tests, and reading, i can't connect react native with react-devtools, this is the same with nuclide and with the standalone app.

Same problem with geny motion : https://stackoverflow.com/questions/45093161/how-can-i-get-react-developer-tool-to-work-with-genymotion

I'm not sure, i see two possibility : the doc should mention option to add by use REACT_DEBUGGER variable or the system doesn't work actually. But i spend many hours to test and no solution appears. So i hope this issue could be usefull to find it.

**Comment by jhen0409** [comment] 2017-08-09 02:44
React DevTools isn't debugger of React Native, I think you misunderstood (even the StackOverflow problem).

**Comment by nicodmf** [comment] 2017-08-09 14:37
React dev tools debug native with versions from 4 month ago. I don't understand why this is broken now, as Atom/Nuclide debugger. 

But this is a strange competition and now the winner isn't the open source neither a javascriptcore debugger which would be more efficient aand realistic than a V8 engine.

**Comment by muhyidin3222** [comment] 2019-03-12 15:21
uninstall your application, then run => react-native run-android in terminal then click debugging end in chrome replace http://localhost:8081/debugger-ui/, end run react-native run-android. if you still haven't succeeded try again

**Comment by bvaughn** [comment] 2019-08-19 23:16
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:16 UTC
