### ISSUE TITLE
react-devtools still has PATENTS file

### ISSUE THREAD

**Issue by jwhitley** [facebook/react-devtools#1342] opened 2019-05-01 00:13 UTC
## 🐛 Bug Report

This repo still has the PATENTS file, effectively meaning that React Native is still impacted by the patent retaliation clause.

## To Reproduce
Inspect this repo and observe that it's still under the BSD 3-clause LICENSE and critically, still has the PATENTS file.

## Expected Behavior

React Native is no longer (transitively!) affected by the PATENTS file clause.  I believe this was an oversight from the previous switch of React Native's own license.

**Comment by bvaughn** [comment] 2019-08-19 23:05
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:05 UTC
