### ISSUE TITLE
Firefox displays duplicate (leaked?) instances

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#622] opened 2017-04-24 16:38 UTC
The issue seems confined to Firefox version.

(You can go to `shells/firefox`, `./build.sh` there and go to Firefox > Tools > Add-ons > Debug Addons > Load Temporary Addon > `shells/firefox/react-devtools.xpi` to test it.)

When I go to https://facebook.github.io/react/, I see one copy of each root:

<img width="1109" alt="screen shot 2017-04-24 at 5 33 50 pm" src="https://cloud.githubusercontent.com/assets/810438/25348006/add9e486-2914-11e7-8fe3-4df87beb0fa5.png">

But then if I refresh the screen a couple of times and close-and-open the DevTools panel a couple of times, at some point suddenly it displays a bunch of dead roots:

<img width="1075" alt="screen shot 2017-04-24 at 5 34 42 pm" src="https://cloud.githubusercontent.com/assets/810438/25348025/c620a73c-2914-11e7-8d87-bc70ae7403eb.png">

I imagine the Firefox entry point needs either cleanup, or an extra check for the part that could run twice. Not sure where it is though.

**Comment by kwnccc** [comment] 2017-04-25 21:05
Hey @gaearon I'd like to work on this

**Comment by clarkbw** [comment] 2017-07-19 19:24
I can't reproduce this anymore with the new Firefox WebExtension.

Here are my steps:

- `yarn install`
- `yarn run build:extension:firefox`
- `WEB_EXT_FIREFOX=nightly yarn run test:firefox`
- open React DevTools panel
- refresh multiple times

**Comment by bvaughn** [comment] 2019-08-19 23:27
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:27 UTC
Labels: bug, difficulty: medium, someone is working on this
