### ISSUE TITLE
Can't edit fontWeight in RN Style Editor

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#797] opened 2017-06-06 15:00 UTC
Here's the current value:

<img width="183" alt="screen shot 2017-06-06 at 3 59 17 pm" src="https://cloud.githubusercontent.com/assets/810438/26835879/309e6cf6-4ad1-11e7-93f8-9a6324f660ea.png">

If I try to set it to `200` I get this:
<img width="308" alt="screen shot 2017-06-06 at 3 59 22 pm" src="https://cloud.githubusercontent.com/assets/810438/26835885/3c620746-4ad1-11e7-83ae-f9763725dc84.png">

If I try to set it to string `'200'` I get this instead:
<img width="313" alt="screen shot 2017-06-06 at 3 59 35 pm" src="https://user-images.githubusercontent.com/810438/26835893-43dfe8bc-4ad1-11e7-84f7-a7416d782ebc.png">

How do we fix it?

**Comment by akoserwal** [comment] 2018-09-12 07:14
@gaearon: Is this still a valid issue? I can't find those CSS properties in the `ReactNativeStyle/StyleEdit` etc.

**Comment by bvaughn** [comment] 2019-08-19 23:24
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:24 UTC
Labels: bug, difficulty: medium, good first bug
