### ISSUE TITLE
Feature Request: option to change panel layout

### ISSUE THREAD

**Issue by alexdevero** [facebook/react-devtools#1021] opened 2018-04-25 11:19 UTC
I'd like to suggest / discuss adding an option to change the default panel layout of React Developer Tools. The idea is implementing something similar to "Panel layout" dropdown in Chrome DevTools. This could add more space to all sections of the panel. What do you think?

Default layout:
![react-dev-tools-before](https://user-images.githubusercontent.com/4237724/39242579-bb02c646-488a-11e8-8ab8-12c18d0fba68.png)

Additional layout:
![react-dev-tools-after](https://user-images.githubusercontent.com/4237724/39242578-bae640a2-488a-11e8-8c8c-a9bdb7f79b08.png)

_* screens are from undocked Chrome DevTools._

**Comment by bvaughn** [comment] 2018-05-09 22:44
I can see this being helpful in some cases. Although typically I would just resize the (Chrome) DevTools window if I need more width or height for the React DevTools view.

That being said, I think we'd be happy to review a PR for this.

**Comment by bvaughn** [comment] 2019-08-19 23:12
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:12 UTC
Labels: difficulty: medium, enhancement
