### ISSUE TITLE
Fix Fiber DEV mode detection

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#694] opened 2017-05-06 13:10 UTC
I fixed a false positive in https://github.com/facebook/react-devtools/pull/693 but we should have a better strategy than relying on a particular function. I think we should pass a completely separate function in Fiber which we'll check for crushed-ness, and keep it explicit. This will require a small change in React.

**Comment by prometheansacrifice** [comment] 2017-05-10 16:17
[The approach](https://github.com/facebook/react/blob/b61f060044780cd3d309fc7644cddf7633212465/src/renderers/dom/ReactDOM.js#L108), using a self declared `testFunc` and checking it name in the runtime, taken in earlier ReactDOM.js seems to be missing in `ReactDOMFiber.js`. Is this the small change in React you are talking about?

If the same approach is taken in Fiber, we again run the same check in devtools right?

**Comment by gaearon** [comment] 2017-05-10 16:19
I think something similar is reasonable. We keep `testFunc` declared in `ReactDOMFiber` but pass it together with `injectInternals()` call. Then in DevTools we can expect it.

I want to check two things:

1) That `name` is minified
2) That something inside `__DEV__` block in `testFunc` does not exist at all in `toString()`'d code

**Comment by prometheansacrifice** [comment] 2017-05-10 16:35
Ah! Interesting. And use regex to check if __DEV__ block is empty?

**Comment by bvaughn** [comment] 2019-08-19 23:28
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:28 UTC
