### ISSUE TITLE
How to keep opened DOM Node after Hot reload

### ISSUE THREAD

**Issue by roslaneshellanoo** [facebook/react-devtools#819] opened 2017-06-21 09:49 UTC
When you selecting a component in React DevTools and changing some code in the editor, the React DevTools not preserving the selected component.

### **for example, component selection:**
![screen shot 2017-06-21 at 12 45 44](https://user-images.githubusercontent.com/20886073/27378144-a50a244a-567f-11e7-9959-4ab5436705c8.png)

### **When you changing some code in the editor, react devtools showing the root component**

![screen shot 2017-06-21 at 12 47 43](https://user-images.githubusercontent.com/20886073/27378242-f610eb4e-567f-11e7-8302-2ee098b5ec7d.png)

**Comment by bvaughn** [comment] 2019-08-19 23:23
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:23 UTC
