### ISSUE TITLE
Documentation for "Trace React Updates"

### ISSUE THREAD

**Issue by CodyReichert** [facebook/react-devtools#335] opened 2016-02-27 21:37 UTC
Is there any place to read about what information "Trace React Updates" is giving me? Sometimes traces are different colors (blue, green, red) and I'd like to know what those mean but could find anything out there.

Related threads:
#327
#297

**Comment by stipsan** [comment] 2016-02-29 15:03
This is the code that decides what color to show you:
https://github.com/facebook/react-devtools/blob/68a71d3d9e5bf982ced63a960437a53f789be64c/plugins/BananaSlug/BananaSlugWebNodePresenter.js#L95
and this is where `data.hits` get incremented:
https://github.com/facebook/react-devtools/blob/68a71d3d9e5bf982ced63a960437a53f789be64c/plugins/BananaSlug/BananaSlugAbstractNodePresenter.js#L61

The shorter the time is between each time an update happens the hotter the color.

**Comment by CodyReichert** [comment] 2016-03-02 17:33
Thanks, @stipsan - I'll check that out! Any chance of a documentation PR getting merged for this (from me or anyone else)? If so, what would be the best place to add it?

**Comment by stipsan** [comment] 2016-03-02 17:35
I'm going to submit a PR about a related issue, see: #337
It was suggested to add it to the readme FAQ.

**Comment by timrichd** [comment] 2016-06-06 09:43
What do the different colours mean?

**Comment by bratberg** [comment] 2017-03-27 08:34
What [the colors](https://github.com/facebook/react-devtools/issues/335#issuecomment-190249223) actually looks like: 
![screen shot 2017-03-27 at 10 29 19](https://cloud.githubusercontent.com/assets/1135523/24347510/d5268fdc-12d8-11e7-83fb-643e789a6814.png)

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
