### ISSUE TITLE
Uncaught Error: Relay Devtools: Called only call setRequestListener once

### ISSUE THREAD

**Issue by felix-d** [facebook/react-devtools#605] opened 2017-04-10 02:24 UTC
Hi! 👋 

I'm currently working on a Phoenix/React/Relay application. When Phoenix livereload kicks in, it seems [this event listener is created twice](https://github.com/facebook/react-devtools/blob/master/shells/chrome/src/backend.js#L27), which ends up throwing this error [here](https://github.com/facebook/react-devtools/blob/eb96aaf8ad3c6188f6b7e08131f0d703670d2bd5/plugins/Relay/installRelayHook.js#L48). 

<img width="523" alt="screen shot 2017-04-09 at 9 55 22 pm" src="https://cloud.githubusercontent.com/assets/5751476/24843690/2cdd1f80-1d73-11e7-82f9-b56a0308114e.png">

I added a breakpoint at this location and it is indeed activated twice.

I also noticed that the root element appears twice in the dev tools.

<img width="564" alt="screen shot 2017-04-09 at 9 53 13 pm" src="https://cloud.githubusercontent.com/assets/5751476/24843687/230ebab8-1d73-11e7-8ac6-929f21b20324.png">

Note that this does not happen when manually refreshing the page.

Not sure why livereload could cause this? It seems [to simply call `window.top.location.reload()` when a file changes ](https://github.com/phoenixframework/phoenix_live_reload/blob/master/priv/static/phoenix_live_reload.js#L40)

Thanks a lot!

**Comment by felix-d** [comment] 2017-04-10 22:11
Also It does not happen with the Firefox addon.

**Comment by gaearon** [comment] 2017-04-19 15:11
What exactly does Phoenix livereload do? It is not obvious to people like me who never even heard of Phoenix 😉 . Can you create a reduced example that does the same thing (but without Phoenix)? I assume it’s executing the React script twice in the context of the same page, or something like that?

**Comment by felix-d** [comment] 2017-04-19 15:15
@gaearon yes that's probably what it is doing, I could try to recreate without Phoenix but I feel like it's going to be hard 🤦‍♂️ . Maybe I can try to call a stripped down version of their livereload js script

**Comment by gaearon** [comment] 2017-04-19 15:24
Do you use Relay?

**Comment by felix-d** [comment] 2017-04-19 15:25
@gaearon yes I do

**Comment by gaearon** [comment] 2017-04-19 15:31
Can you give me the full callstack of the error? I'm confused who calls `backend.js`.

**Comment by felix-d** [comment] 2017-04-19 15:35
That's all I have
```
VM101:68 Uncaught Error: Relay Devtools: Called only call setRequestListener once.
    at setRequestListener (<anonymous>:68:34)
    at module.exports (backend.js:9987)
    at setup (backend.js:120)
    at welcome (backend.js:79)
setRequestListener	@	VM101:68
module.exports	@	backend.js:9987
setup	@	backend.js:120
welcome	@	backend.js:79
```

It seems to come from this event listener that is created twice (because the script is evaluated twice?)

```js
window.addEventListener('message', welcome);
```

**Comment by gaearon** [comment] 2017-04-19 15:36
Can you somehow put a breakpoint in the script itself so that we learn *what* evaluates it twice? I’m not fully following how we end up in `backend.js` in the first place (I don’t really know a lot about how this repo works).

**Comment by felix-d** [comment] 2017-04-19 15:45
It seems to be injected [https://github.com/facebook/react-devtools/blob/master/shells/chrome/src/panel.js#L71](here)

**Comment by gaearon** [comment] 2017-04-19 15:53
This is just the `inject` definition but who calls it? `Panel`?

**Comment by felix-d** [comment] 2017-04-19 16:01
no idea, the callstack does not say much

<img width="151" alt="screen shot 2017-04-19 at 11 57 33 am" src="https://cloud.githubusercontent.com/assets/5751476/25189535/6cd31b5e-24f7-11e7-874d-13c59dbfe3a7.png">

 the event listener creation is global and must be fired at soon as `backend.js` is evaluated. It's an entry point for this webpack build

https://github.com/facebook/react-devtools/blob/f4b774e145b7a9444152c8bc72e018e39c90a7d6/shells/chrome/webpack.backend.js#L19

**Comment by gaearon** [comment] 2017-04-19 16:39
The `inject` calls I was referring to are here:

* https://github.com/facebook/react-devtools/blob/361bc0877eb1b63f66dd45aa6df34126cf2085e5/frontend/Panel.js#L216
* https://github.com/facebook/react-devtools/blob/361bc0877eb1b63f66dd45aa6df34126cf2085e5/frontend/Panel.js#L84

**Comment by gaearon** [comment] 2017-04-19 16:40
I’m not sure what the right fix is here. The backend makes an assumption that it only runs once, but it probably can run multiple times? It’s not clear where is the right place to fix this.

cc @jaredly who might provide hints on the initial design.

**Comment by felix-d** [comment] 2017-04-19 16:45
thanks for investigating @gaearon, sorry to not be of much more help here I don't JS a lot these days and I'm at work

**Comment by bvaughn** [comment] 2019-08-19 23:27
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:27 UTC
Labels: bug, difficulty: medium
