### ISSUE TITLE
Hi I am unable to access react dev tools on chrome developer tools.

### ISSUE THREAD

**Issue by aswinputra** [facebook/react-devtools#1327] opened 2019-04-11 08:19 UTC
I am using OS Mojave Version 10.14,
the extension version that I am using is 3.6.0.

I am doing an online tutorial for ReactJS and I tried to debug using the React Developer tools, however it does not come up in the google developer tools tab.

**Comment by shahzeb1** [comment] 2019-04-11 21:31
Are you trying to access a `file://` URL? Or is this a `localhost` URL?

**Comment by aswinputra** [comment] 2019-04-12 07:17
Via local service. I think it works now. Thanks

**Comment by bvaughn** [comment] 2019-08-19 23:06
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:06 UTC
