### ISSUE TITLE
devtools cannot connect

### ISSUE THREAD

**Issue by Char-set** [facebook/react-devtools#935] opened 2017-11-04 05:36 UTC
Why doesn't it connect
![1509773769712](https://user-images.githubusercontent.com/27180609/32402711-2f4bd530-c0f8-11e7-83b1-21e923d932e7.jpg)

**Comment by fmorato** [comment] 2017-11-08 16:17
I Also can't get it to connect to react native app. Could not find any information about it.
Using react native 0.50.1 and react 16.0.0 on linux. Tried with device plugged through USB and over Wifi. Also changed the port in the In-app dev settings to 8097 but it didn't work. I guess that's only for packager.

**Comment by fmorato** [comment] 2017-11-10 17:44
Running `adb reverse tcp:8097 tcp:8097` made it to work with connected device. :) probably works for simulator as well.

**Comment by gaearon** [comment] 2017-11-14 10:47
Is this a new issue caused by RN update? We'd need more details.

**Comment by joshribakoff** [comment] 2018-02-04 02:52
Same, here's what I get when devtools is docked on the right on my mac

google chrome Version 63.0.3239.132 (Official Build) (64-bit)
React Developer Tools 3.1.0
react 16.2.0

![screen shot 2018-02-03 at 6 49 27 pm](https://user-images.githubusercontent.com/4021306/35773842-110fb362-0913-11e8-9314-6580d06c084f.png)

Page is served over a vagrant private IP address & loads JS from webpack on localhost:8080 (origins differ). No errors in console though & I would still expect this to work.

**Comment by DiegoBM** [comment] 2018-03-10 11:11
I was having the same issue (in my case running an android virtual device) until I run @fmorato's solution. Which should be marked as valid.

Windows 10 Professional
react-native: 0.54.0
react-devtools: 3.1.0

**Comment by toan301** [comment] 2019-01-17 17:40
My issue till not resolved even with `adb reverse tcp:8097 tcp:8097`

**Comment by shubknit** [comment] 2019-05-10 10:11
> Running `adb reverse tcp:8097 tcp:8097` made it to work with connected device. :) probably works for simulator as well.

Yeah, issue also resolved on simulator | Windows10 OS | android simulator

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
