### ISSUE TITLE
Pressing <Tab> on last value in RN style editor should add a new style

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#794] opened 2017-06-06 14:40 UTC
Currently it doesn’t:

![](https://d2ppvlu71ri8gs.cloudfront.net/items/1D2o2q3S3E2Y2a1m423H/Screen%20Recording%202017-06-06%20at%2003.40%20PM.gif?v=8845f351)

We need to fix it to create a new key-value pair, just like Chrome does.

**Comment by glennreyes** [comment] 2017-06-12 13:20
Will work on this 👍

**Comment by bvaughn** [comment] 2017-07-10 18:26
Tagging this as in-progress since [@sumnerevans asked to work on it](https://github.com/facebook/react-devtools/pull/810#issuecomment-313773234).

Let me know if you change your mind, Sumner! 😄

**Comment by sumnerevans** [comment] 2017-07-17 15:52
@bvaughn, were you going to merge in #810? I would rather work off of this repo (I'm working on this on behalf of Kenzan so, for administrative reasons, it's easier).

**Comment by bvaughn** [comment] 2017-07-17 16:29
I was not planning on merging #810 as it had a few issues needing to be addressed first. I was holding off to see what you did with your fork, assuming I'd merge a PR from you and close #810.

What do you prefer?

**Comment by sumnerevans** [comment] 2017-07-19 18:14
@bvaughn, I've been working on this for Kenzan and there have been a few changes in my work allocation. I'm not going to be able to work on this. I'm really sorry.

**Comment by bvaughn** [comment] 2017-07-19 18:16
That's okay. It happens.

Does this also apply to #814 ? Need to know if I should mark that as ready for someone to pick up also.

**Comment by fumblehool** [comment] 2017-10-13 06:14
@bvaughn Is this issue still open?

**Comment by hectorpla** [comment] 2018-10-30 20:46
@bvaughn, I have a pr to make this work(#1205). Please check it out.

**Comment by bvaughn** [comment] 2019-08-19 23:24
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:24 UTC
Labels: difficulty: starter, enhancement, good first bug
