### ISSUE TITLE
Standalone app on Mac is stuck at "Waiting for React to connect" with regular react

### ISSUE THREAD

**Issue by donpinkus** [facebook/react-devtools#1285] opened 2019-01-23 01:10 UTC
I'm using the standalone app to debug a web based react app. (I can only use Safari as my browser)

**What I've done:**
1. `$ npm i -g react-devtools`
2. `$ react-devtools`
3. Copy and paste the `<script src="http://localhost:8097"></script>` line into my app.

**The result:**
No errors in my console or terminal, and the electron app displays the landing page "Waiting for React to connect..."

**Comment by herodrigues** [comment] 2019-01-30 20:52
That should the trick.
Have you tried adding `react-devtools` as a devDependency and import it to your code instead of using the script tag?

```js
// main app JS file
import React from 'react'
import { render } from 'react-dom'

import 'react-devtools'
```

**Comment by bvaughn** [comment] 2019-08-19 23:06
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:06 UTC
