### ISSUE TITLE
Illegal Invocation error - on File unfold - in props tree

### ISSUE THREAD

**Issue by Aarbel** [facebook/react-devtools#987] opened 2018-02-11 22:51 UTC
The React Devtools doesn't seem to be allowed to access local files when i click on the arrow to unfold the details of the file (here "files" are the input content of an `<input type="file" multiple/>`. 

![image](https://user-images.githubusercontent.com/25119847/36079674-06a5dd60-0f86-11e8-99cc-6c7bc8f4f6e5.png)

![image](https://user-images.githubusercontent.com/25119847/36079669-faef2968-0f85-11e8-8d4b-e39403c59c15.png)
![image](https://user-images.githubusercontent.com/25119847/36079680-1281aa88-0f86-11e8-995c-56ed1bf49db6.png)

**Comment by Saifadin** [comment] 2018-09-02 17:26
I got the same error. It is not blocking me or anything, just gonna link a screenshot of it happening today, in the hopes it may help @bvaughn to debug it.

<img width="539" alt="screen shot 2018-09-02 at 18 53 25" src="https://user-images.githubusercontent.com/1507057/44958840-01c1f680-aee6-11e8-83f3-24850cf0176e.png">

**Comment by bvaughn** [comment] 2019-08-19 23:13
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:13 UTC
