### ISSUE TITLE
Could not resolve '_reactFragment' for complex properties like objects.

### ISSUE THREAD

**Issue by viktorchukhantsev** [facebook/react-devtools#1019] opened 2018-04-16 04:39 UTC
I'm using awilix as IoC container to pass all my services to components and extension can't properly work with such behavior.

**Comment by gaearon** [comment] 2018-05-01 19:52
Please provide more information. It's very hard to understand what problem you're having from this description.

**Comment by bvaughn** [comment] 2018-05-09 22:40
Closing this issue for now due to lack of info. We'll re-open it later if there are repro instructions! 😄 Cheers!

**Comment by bvaughn** [comment] 2018-05-10 16:13
This is the runtime error I see:
> awilix.browser.js:90
> Uncaught Error: Could not resolve '_reactFragment'.
> Resolution path: _reactFragment

Specifically, this error is [thrown by `AwilixResolutionError`](https://github.com/jeffijoe/awilix/blob/355d3e1025a4f8012e36a49303d20788a7e9ddfb/src/errors.ts#L136).

React DevTools has a line of code that [tries to read `_reactFragment`](https://github.com/facebook/react-devtools/blob/ed27c461ad4057fe08c30854383bbacc06f9708b/agent/dehydrate.js#L23) as part of filtering out complex objects from the properties panel. It seems the [awilix `resolve()` function does not like this because it isn't one of its `computedRegistrations`](https://github.com/jeffijoe/awilix/blob/6b734ebd5b72e18c4796195b5705e6ffea9f6dc3/src/container.ts#L388-L428).

I'm not familiar with this awilix module. Just reporting what I see when stepping through the stack trace.

I suppose React DevTools _could_ add a try/catch inside of its `getPropType` method to handle cases like this.

**Comment by bvaughn** [comment] 2018-05-10 16:13
cc @gaearon if he has an opinion on this

**Comment by viktorchukhantsev** [comment] 2018-05-11 07:12
Awilix is just IoC container, it's an example of a complex structure that can present in properties of react component class. I totally agree with 

> I suppose React DevTools could add a try/catch inside of its getPropType method to handle cases like this.

It doesn't matter that I can't receive access to such properties(except name), but the extension should handle such cases and continue work.

**Comment by bvaughn** [comment] 2019-08-19 23:12
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:12 UTC
