### ISSUE TITLE
Doesn't detect React App in Shadow DOM

### ISSUE THREAD

**Issue by krabbypattified** [facebook/react-devtools#1068] opened 2018-07-27 09:26 UTC
React DevTools doesn't detect an app inside a shadow root. Is this intended?

``` jsx
const shadow = document.getElementById('app').attachShadow({ mode: 'open' })
ReactDOM.render(<App/>, shadow)
```

**Comment by herodrigues** [comment] 2018-07-30 18:26
I guess you have to use the standalone app 

https://github.com/facebook/react-devtools/tree/master/packages/react-devtools

**Comment by krabbypattified** [comment] 2018-07-31 11:25
Ok :\ That's unfortunate. It would be nice to detect this if at all possible. An open shadow root should be accessible to javascript anywhere on the page.

**Comment by herodrigues** [comment] 2018-08-23 20:10
@krabbypattified this could be an awesome feature, but I guess it would add a lot of complexity to this package, for example, multiple shadow root elements with React apps on their.

The standalone package works in my case (Chrome extension that injects a React app sidebar into the page using a shadow DOM element), but sometimes it doesn't connect automatically and I have to reload the page multiple times.

@bvaughn since you've added lots of enhancement issues recenetly, do you have any thoughts on this?

**Comment by bvaughn** [comment] 2018-08-27 14:57
Unfortunately, no. This isn't something I've spent any time or thought on before. 😄

**Comment by bvaughn** [comment] 2019-08-19 23:11
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:11 UTC
