### ISSUE TITLE
Stateless components not being highlighted

### ISSUE THREAD

**Issue by satazor** [facebook/react-devtools#958] opened 2018-01-01 13:15 UTC
I noticed that stateless components are not being highlighted but they are being re-rendered.
I searched the issue tracker but couldn't find any issue related to this.

Here's a simple reproducible example: https://pure-components-sbosypcvwa.now.sh/
The list and the item are stateless components. Open the devtools, select highlight, and press `load more`.

You will see console.log's being printed for repeated items but no highlighting :(

**Comment by carlosagsmendes** [comment] 2018-02-10 17:21
Hey @satazor I experienced the same issue today so I think we can confirm that this is a bug ([link to my example](https://codesandbox.io/s/k378jn3817)). 

I don't know if it will be easy to sort out since as far as I know functional components don't have a lifecycle like regular Components/PureComponents. But I'm willing to work on it if someone can provide some guidance.

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
