### ISSUE TITLE
Firefox plugin seems to cause memory leak

### ISSUE THREAD

**Issue by jochenberger** [facebook/react-devtools#333] opened 2016-02-25 13:57 UTC
I have the Tab Memory Usage plugin installed. When I reload a React page multiple times, the tab's memory usage increases every time and does not decrease back to the level that it had before. If I disable the plugin, I don't see that behavior. I'm using Iceweasel 44.0.2-1 on Debian.

**Comment by ZipoKing** [comment] 2016-03-03 15:48
I'm experiencing the same issue - developing React with Freifox, especially when Firebug window is open is causing out-of-memory errors, even that I've 8GB of RAM on my 64-bit machine.
Using the newest Firefox @ Slackware64  with automatic updates enabled (current version: 44.0.2)

**Comment by betolink** [comment] 2016-10-24 01:41
Same here, if I open the devtools and reload a react app the memory fills completely and then it gets back to normal.

**Comment by envygeeks** [comment] 2016-12-09 09:41
This isn't just the Firefox plugin, this also happens with the Chrome extension.  From 2 hours of development in one of our React apps React Dev tools has consumed 1.5gb of ram on my Ubuntu machine.

**Comment by envygeeks** [comment] 2016-12-09 09:42
To add a secondary note: For anybody who is getting the leak with the Chrome extension, just close the console and reopen it, Chrome will flush it when the inspector closes, I don't know if that will work for Firefox but it works for Chrome.

**Comment by JacquelinClement** [comment] 2017-07-21 15:15
@envygeeks Doesn't work for me with Firefox (v54.0.1) on MacOS (v10.11). 
I have delete the Facebook React plugin, it was a total disaster, always out of memory (got 8Go) and more than 3Go taked by FF.

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
