### ISSUE TITLE
sidebar gets pushed out of view with a very long DOM hierarchy

### ISSUE THREAD

**Issue by skYYman** [facebook/react-devtools#1107] opened 2018-08-22 08:28 UTC
The latest update leads to the sidebar getting pushed out of view when you have a very large DOM hierarchy at the bottom of the tool. The sidebar also can't be dragged over the hierarchy. When I do that the sidebar disappears completely and I have to close and re-open the dev-tools.

Ubuntu 18.04
FF 61.0.1 (x64)

**Comment by iamdustan** [comment] 2018-08-22 12:55
Tracked in #1099

**Comment by gaearon** [comment] 2018-08-22 15:56
I don't think #1099 is relevant? It's about the profiler.

@skYYman Please provide screenshots.

**Comment by snow-dev** [comment] 2018-08-22 17:43
Same here, have you fix it??

**Comment by iamdustan** [comment] 2018-08-22 17:51
<img width="688" alt="screen shot 2018-08-22 at 1 50 48 pm" src="https://user-images.githubusercontent.com/227879/44480891-6477e000-a612-11e8-81d9-2a479e1ee145.png">

(I only know it’s in there because I experienced this while testing the profiler with @bvaughn last week)

**Comment by iamdustan** [comment] 2018-08-22 17:53
![devtools](https://user-images.githubusercontent.com/227879/44481034-cb959480-a612-11e8-9042-40ea577228d4.gif)

**Comment by bvaughn** [comment] 2018-08-22 18:17
Duplicate of #336 – let's move the conversation there.

**Closed by bvaughn** 2018-08-22 18:17 UTC

**Comment by bvaughn** [comment] 2018-08-22 18:35
Fixed via #1111

**Comment by gaearon** [comment] 2018-08-23 14:05
Fixes are out to both stores, wait for 3.3.1 to show up.
