### ISSUE TITLE
Make prominent link from component to Sources tab

### ISSUE THREAD

**Issue by unphased** [facebook/react-devtools#152] opened 2015-08-17 18:34 UTC
Even though it is easy to do the task of looking up the source file corresponding to any given component (as long the naming scheme is a reasonable one that is), it seems like a workflow that can be streamlined... Imagine, digging around in the tools and being able to click to open the source tab for that component, right inside the inspector.

**Comment by spicyj** [comment] 2015-08-17 18:37
Surprise! You can do this by right-clicking the tag on the left. Maybe we should add a link on the right too though.

**Comment by unphased** [comment] 2015-08-17 18:42
OMG it even takes you to the line that `render()` is declared. :heart:

**Comment by spicyj** [comment] 2015-08-17 18:53
Gonna leave this open; I think we should add a more prominent link.

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
