### ISSUE TITLE
Feature Request: Opening Component in code editor

### ISSUE THREAD

**Issue by shobhitchittora** [facebook/react-devtools#975] opened 2018-01-28 19:39 UTC
Hi! This is my first issue here and I'm not sure whether this has already been raised. I'd like to suggest / discuss on the possibility of having react-devtools open a component in an editor of choice when clicking on `Show <Component> source` (from the menu on right clicking in devtools as below).

<img width="226" alt="screen shot 2018-01-29 at 1 03 04 am" src="https://user-images.githubusercontent.com/4711855/35486166-354c0460-0490-11e8-92de-ee51ecd4fb9e.png">

Also I've seen that the same is done in CRA's  overlay component (react-error-overlay), clicking on which takes you to the file in an open editor. I found a code pointer here - 
[here](https://github.com/facebook/create-react-app/blob/5348d6eecf208a6298e48072314157804282002e/packages/react-dev-utils/webpackHotDevClient.js#L26)

I'd like to take this up in case it makes sense. Also would like some guidance. 😇

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
