### ISSUE TITLE
"Node was deleted" when switching root RN views

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#796] opened 2017-06-06 14:53 UTC
I'm not sure how to reproduce this outside of FB environment (Catalyst) but I see ghost nodes every time I switch root views:

<img width="333" alt="screen shot 2017-06-06 at 3 52 06 pm" src="https://cloud.githubusercontent.com/assets/810438/26835412/31ff90c6-4ad0-11e7-87c9-c7e4f870851a.png">

We probably don't clean up something on RN.

**Comment by bvaughn** [comment] 2019-08-19 23:24
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:24 UTC
Labels: bug, difficulty: medium, good first bug
