### ISSUE TITLE
Theme dropdown/select options in Settings unexpected rendering on Chrome

### ISSUE THREAD

**Issue by miglrodri** [facebook/react-devtools#1306] opened 2019-02-18 17:20 UTC
Hello,

I'm using Chrome: V 72.0.3626.109 (Compilação oficial) (64 bits)
And react dev tools: 3.6.0 (for Chrome)

In the following image you can see what's happening to me when i go to settings and click on the theme dropdown. The options don't appear in the correct way. I should see all the names clearly.

![alt text](https://i.imgur.com/hpvDUAC.png "react docs with react dev tools")

Best regards,
Miguel.

**Comment by bvaughn** [comment] 2019-08-19 23:08
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:08 UTC
