### ISSUE TITLE
Errors from react-devtools when debugging NodeJS application in Chrome  

### ISSUE THREAD

**Issue by bmihelac** [facebook/react-devtools#1250] opened 2018-12-18 12:27 UTC
Hello,

I have noticed, that react-devtools produces a lot of errors when it is enabled and node inspector is used.

OS: Ubuntu 18.10
Chrome:
Version 72.0.3626.17 (Official Build) beta (64-bit)
Version 71.0.3578.98 (Official Build) (64-bit)

1. Start node with debugger:

```
node --inspect-brk test.js
```

test.js is not react application, it is just a dummy file with `console.log('foo')` content.

2. Open `chrome://inspect/#devices`, click on "inspect" in Remote Target 

3. inspect background page of React devtools

Errors are throwed every second in console:
.
```
evaluate @ shell.js:7819
shell.js:7831 Extension server error: Object not found: <top>
makeStatus @ shell.js:7831
shell.js:7819 evaluate: the main frame is not yet available
evaluate @ shell.js:7819
_onEvaluateOnInspectedPage @ shell.js:7744
_onmessage @ shell.js:7796
```
This errors are also visible with `journalctl`:

```
Dec 18 13:14:37 bell org.gnome.Shell.desktop[18233]: [803:803:1218/131437.466402:ERROR:CONSOLE(7831)] "Extension server error: Object not found: <top>", source: chrome-devtools://devtools/bundled/shell.js (7831)
Dec 18 13:14:38 bell org.gnome.Shell.desktop[18233]: [803:803:1218/131438.467673:ERROR:CONSOLE(7831)] "Extension server error: Object not found: <top>", source: chrome-devtools://devtools/bundled/shell.js (7831)
Dec 18 13:14:39 bell org.gnome.Shell.desktop[18233]: [803:803:1218/131439.467788:ERROR:CONSOLE(7831)] "Extension server error: Object not found: <top>", source: chrome-devtools://devtools/bundled/shell.js (7831)
Dec 18 13:14:40 bell org.gnome.Shell.desktop[18233]: [803:803:1218/131440.467854:ERROR:CONSOLE(7831)] "Extension server error: Object not found: <top>", source: chrome-devtools://devtools/bundled/shell.js (7831)
Dec 18 13:14:41 bell org.gnome.Shell.desktop[18233]: [803:803:1218/131441.467157:ERROR:CONSOLE(7831)] "Extension server error: Object not found: <top>", source: chrome-devtools://devtools/bundled/shell.js (7831)
Dec 18 13:14:42 bell org.gnome.Shell.desktop[18233]: [803:803:1218/131442.468022:ERROR:CONSOLE(7831)] "Extension server error: Object not found: <top>", source: chrome-devtools://devtools/bundled/shell.js (7831)
```

If I disable react-devtols (or open inspector in the incognito mode where extensions are disabled), there are no such errors.

Please let me know if you need any other information regarding this.

**Comment by bvaughn** [comment] 2019-08-19 23:08
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:08 UTC
