### ISSUE TITLE
Persist "Highlight updates"-value when dev tools reloads

### ISSUE THREAD

**Issue by Fralleee** [facebook/react-devtools#844] opened 2017-07-13 05:27 UTC
This is useful when using 3rd party login, which forces react dev tools to reload and thus disabling highlight updates, or just simply when you are in "optimization"-mode and want the "highlight updates"-option enabled for a longer period of time.

**Comment by sumnerevans** [comment] 2017-07-14 22:38
@Fralleee, I can look into this. I've been looking through the codebase trying to figure out how to tackle this. Are there any mechanisms in place currently for
1. storing state in a way that is persistent across reloads; and
2. restoring state after a reload?

**Comment by falinsky** [comment] 2018-11-06 09:57
@gaearon @bvaughn Is there any chance to get a fix for this issue to be reviewed? May be is there any schedule regarding this? Thanks.

**Comment by bvaughn** [comment] 2018-11-07 19:14
This change will go out with the next DevTools release (probably sometime this week). Thanks @falinsky!

**Comment by falinsky** [comment] 2018-11-07 19:51
@bvaughn Thats a great news. Thank you.

**Comment by bvaughn** [comment] 2019-08-19 23:23
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:23 UTC
Labels: difficulty: medium, good first bug
