### ISSUE TITLE
Profiler: how to work with interactions traced before profiling started?

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/react-devtools#1289] opened 2019-01-29 13:27 UTC
I followed the [guide](https://gist.github.com/bvaughn/8de925562903afd2e7a12554adcdda16) to setup interaction tracing for my initial render.

However, it's not clear how I can actually inspect this trace. If I understand correctly, the trace would only appear in the dev tools if it happened whilst profiling was running.

As far as I can see there is no way to start the profiler before the initial render (#1121?), so I don't see any clear way to actually view this interaction trace in the dev tools.

Is this issue therefore the same as #1121, or is it different?

**Comment by bvaughn** [comment] 2019-02-08 21:58
This looks like a duplicate of #1121. DevTools can't gather profiling information for stuff that happens before it's profiling.

There is an unofficial (I think undocumented) API to subscribe to interaction events, but it's probably not what you're looking for. Best answer I have is to wait for the (new) DevTools to support reload-and-profile.

I'm going to close this issue as a duplicate.

**Closed by bvaughn** 2019-02-08 21:58 UTC
