### ISSUE TITLE
Support for Microsoft Edge shell

### ISSUE THREAD

**Issue by satyapramodh** [facebook/react-devtools#1025] opened 2018-05-02 07:26 UTC
Are there plans to support edge at this time? If not I would like to give it a go depending on support for required APIs in edge extensions.

**Comment by bvaughn** [comment] 2018-05-09 22:49
I am not aware of any plans we have to work on Edge support.

If you're interested in working on this- please do! Provided we can automate the build/test process in a similar way as we have for Chrome and Firefox.

**Comment by sagarrabadiya** [comment] 2018-05-11 04:35
would love to see this in MS edge.. 👍 thank you so much for the wonderful dev experience.. 😄

**Comment by satyapramodh** [comment] 2018-05-11 05:39
@bvaughn thats great. thanks! I can start on this from June if thats ok. To follow its progress check https://github.com/satyapramodh/react-devtools

**Comment by satyapramodh** [comment] 2018-05-11 06:28
@bvaughn thanks for getting back to me. I apologize for taking the time, but upon further inspection, it looks like edge does not support [devtools](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/devtools.inspectedWindow) api yet. Its not present in their [roadmap](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/extension-api-roadmap). Also we can track the feature request here at [user-voice](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/15574155-allow-extensions-to-exist-on-the-devtools-pane#comments) and [here](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/15646866-allow-f12-tools-to-be-extended-with-browser-extens).

**Comment by kaleabmelkie** [comment] 2019-04-13 08:08
Now that [Microsoft has launched Edge (Insider Preview) using Chromium](https://www.microsoftedgeinsider.com/en-us/), are there any plans to add this extension to the new browser's official extensions store?

**Comment by bvaughn** [comment] 2019-08-19 23:12
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:12 UTC
Labels: difficulty: complex, enhancement
