### ISSUE TITLE
Feature Request - Export state

### ISSUE THREAD

**Issue by Quantumplation** [facebook/react-devtools#871] opened 2017-08-17 19:36 UTC
Apologies if this feature already exists, I couldn't find any way to do what I'm looking for...

It would be very useful if react dev tools allowed some kind of "Export" functionality, that could later be reimported to inspect further.  The primary use case around this would be for capturing erroneous states to attach to a bug report and aid the developer in tracking down the issue.  Especially useful if the bug is difficult to reproduce or poorly understood.

This is very analogous to saving and submitting a HAR file with the network requests that were made.

**Comment by bvaughn** [comment] 2017-08-17 21:34
I think this is probably a larger scope than React DevTools can tackle. Not all applications can be safely serialized and there no common convenient (that I'm aware of) for how this would be done.

If you're using Redux for state management (for example) there are some time-traveling/persistence tools that do things similar to what you're describing (eg [redux-state-history](https://github.com/inakianduaga/redux-state-history)) but React DevTools can't assume a particular state management tool.

It would be possible to serialize and restore values stored in component `props` and `state` but any instance variables outside of those 2 would not be restored successfully, side effects (like network requests or application code that lives outside of the scope of React) might cause problems, etc.

Am I misunderstanding this issue? 😄

**Comment by Quantumplation** [comment] 2017-08-17 22:14
I agree that a perfect solution might be difficult to impossible.  Something that approximates it, by exporting what it can, might go a long way though.  The moral equivalent of saving the page source.

**Comment by bvaughn** [comment] 2019-08-19 23:16
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:16 UTC
