### ISSUE TITLE
Show non-enumerable properties in the right pane

### ISSUE THREAD

**Issue by tquetano-r7** [facebook/react-devtools#288] opened 2015-11-19 14:32 UTC
I want to be able to trace back the inline styles I apply to the keys in the object they relate to, so I tried adding a non-enumerable, non-configurable property to my style object that just contains the key, thinking if it was non-enumerable then React's style creator would ignore it. This is true, however the key also does not appear in devtools, basically just disappears once the component is created.

My question is if its possible to surface that hidden property in DevTools? Or perhaps I'm going about it the wrong way, is there another good practice for tracing back the styles for a rendered component to the object you instantiated them with?

**Comment by jaredly** [comment] 2015-11-19 20:06
neat trick! I've actually also been thinking about how to make inline styles easier to reason about. 
For hidden properties, we currently just do a `for ... in` on the object [as seen here](https://github.com/facebook/react-devtools/blob/master/agent/dehydrate.js#L86). It shouldn't be hard to include non-enumerables, but I wonder if there are any downsides to doing so.
@spicyj are there typically non-enumerables that we'd rather not send up to the devtools?

**Comment by spicyj** [comment] 2015-11-22 06:29
I think it would be fine to show nonenumerable keys (via Object.getOwnPropertyNames).

**Comment by tquetano-r7** [comment] 2015-11-24 23:58
Sweet! Do you guys need me to do a PR? It's a fairly minor change, so didn't know if you guys just wanted to churn it out or if you want the audit trail.

**Comment by jaredly** [comment] 2015-11-25 18:40
go ahead and PR!

**Comment by gaearon** [comment] 2017-02-15 17:47
Fixed in https://github.com/facebook/react-devtools/pull/376.

**Comment by gaearon** [comment] 2017-02-15 21:00
Reopening because I reverted #376 in https://github.com/facebook/react-devtools/pull/517.

**Comment by gaearon** [comment] 2017-02-16 15:23
We can fix this again after https://github.com/facebook/react-devtools/issues/390#issuecomment-280360149 is implemented.

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
