### ISSUE TITLE
Follow up about RN Fiber changes after Fiber refactoring is merged

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#757] opened 2017-05-31 15:49 UTC
https://github.com/facebook/react-devtools/pull/755 relies on `pendingProps` which may change after https://github.com/facebook/react/pull/9695. Let's follow up and fix style editor again if Fiber changes how pending props are set.

**Comment by bvaughn** [comment] 2019-08-19 23:24
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:24 UTC
