### ISSUE TITLE
"Highlight Updates" shouldn't disappear too fast

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#814] opened 2017-06-15 14:53 UTC
They currently disappear a bit too fast. It would be nice to fade them out instead of instantly hiding them.

I'm also not confident colors are very useful, at least the current ones. They don't tell me much. I'm open to alternative ideas of how to represent updates on the screen.

**Comment by sumnerevans** [comment] 2017-07-07 18:58
@gaearon, I can tackle this. I think that making the updates fade should be fairly straightforward.

One thing that may improve usability is allowing the user to configure how long to persist the highlights for.

I also looked at the coloring and became confused. What do the colors indicate currently (if anything)?

**Comment by gaearon** [comment] 2017-07-07 19:38
I don't think we want to keep this configurable. Let's just find good defaults.

I think the colours are supposed to represent how often the updates have been happening. The hotter the colour the more updates. I'm not sure if this is how it works in practice though and I'm open to changing heuristics to be more useful.

**Comment by sumnerevans** [comment] 2017-07-10 17:13
@gaearon, I doubled the length of the highlight and made the borders fade out. Here's a screen capture of what that looks like.

![highlight-updates-animation](https://user-images.githubusercontent.com/16734772/28030337-96124356-6560-11e7-9dd2-9eb8d7c2f874.gif)

Any thoughts on how I could improve this?

**Comment by gaearon** [comment] 2017-07-10 17:26
I think @bvaughn might have more helpful suggestions on UI than me. Thanks for working on this!

**Comment by bvaughn** [comment] 2017-07-10 18:16
I think I like this change. @sumnerevans is it somewhere I can try it out? Maybe a PR?

**Comment by sumnerevans** [comment] 2017-07-10 18:51
@bvaughn, here's the branch where I've been developing this: https://github.com/kenzanlabs/react-devtools/tree/highlight-update-animation. I am working on this on behalf of Kenzan, so I can't send a PR upstream until an internal review occurs.

**Comment by bvaughn** [comment] 2017-07-10 19:36
I see. I suppose we'll wait for one then. 😄

**Comment by Fralleee** [comment] 2017-07-13 05:11
Don't know if I should write a new issue or write in this one but here goes.
Our app uses a 3rd party login, that means react dev tools "reloads" and the highlight updates is inactive.

Is it possible to add an option to have highlight updates activated by default? Or save the option value, if I once activated it I have to manually deactivate it.

**Comment by bvaughn** [comment] 2017-07-13 05:23
What you're describing definitely sounds like a separate thing to me, @Fralleee. Please file it as a new issue if you would. 😄

I think what you're really asking for (maybe) is that DevTools persist settings like "highlight updates" in the same way as we currently persist theme-selection. True? If so, I think that would be a reasonable feature request. 😄

**Comment by Fralleee** [comment] 2017-07-13 05:24
That's exactly what I meant, sorry for phrasing it so poorly. I will file a new issue.

**Comment by bvaughn** [comment] 2017-07-19 19:24
Okay, so a PR is still coming for this- it will just be delayed?

If so, I don't mind waiting a while. 😄  Just wanted to confirm!

**Comment by sumnerevans** [comment] 2017-07-19 19:36
@bvaughn, yes. We will submit a PR as soon as the CLA is signed.
CC: @thescientist13.

**Comment by ulrichb** [comment] 2018-07-26 16:51
@sumnerevans Still CLA signing? 😄

**Comment by sumnerevans** [comment] 2018-07-27 18:54
@ulrichb I am no longer at Kenzan (it was just an internship).

**Comment by hristo-kanchev** [comment] 2018-12-14 12:03
@sumnerevans This issue seems stale. Are you going open a PR for this?

**Comment by sumnerevans** [comment] 2018-12-18 04:15
@hristo-kanchev I made this contribution as a Kenzan intern, which means that I do not believe that I own the rights to this specific bit of code. Please reach out to @thescientist13 who I was working with to figure out how to get CLAs signed between Kenzan/Facebook.

**Comment by thescientist13** [comment] 2018-12-30 18:40
I can reach out to someone at Kenzan.

**Comment by bvaughn** [comment] 2019-08-19 23:23
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:23 UTC
Labels: difficulty: medium, someone is working on this
