### ISSUE TITLE
Search / search highlighting only updates when existing components are removed, not when new ones are added

### ISSUE THREAD

**Issue by mjmasn** [facebook/react-devtools#470] opened 2017-01-11 06:29 UTC
Search doesn't update with each render, so if I turn on highlighting for a particular component, and navigate to a new page (as in js routing/render, not http routing). I have to actually modify the search (e.g. add a space) then return to the original value to find the new components. Just pressing enter in the search box doesn't work. I would expect this to be automatic.

Interestingly if a component is removed it is removed from the search and search highlighting, but not when a new component is added.

**Comment by spicyj** [comment] 2017-01-11 18:24
Thanks, I agree. I'd be willing to look at a PR to fix this.

**Comment by nicksp** [comment] 2017-02-21 07:15
@mjmasn Could you please record a short demo (in `gif` for example) showing the problem? I just wanna make sure i completely understand the point ;)

**Comment by nicksp** [comment] 2017-02-21 07:16
@gaearon Would like to investigate the problem and propose a fix. Since this is my almost first contribution to the project, will probably require some help... But will do my best to work it out on my own.

**Comment by gaearon** [comment] 2017-02-22 12:29
1. Follow the instructions in `shells/plain/README.md` to open the test page
2. Search for "Todo" in the bottom part of the screen
3. Add a new Todo
4. New Todo component won't show up in the search, but it should

Does this help?

**Comment by vinhlh** [comment] 2017-02-24 01:58
hey @gaearon, In my side, the New Todo component is shown up on Search Results.

**Comment by ioantm** [comment] 2017-02-24 08:49
I was able to reproduce the issue by navigating to a new route and then navigate back  (no http routing) as @mjmasn describe . Maybe remove then add again the container that keeps the searched items is a case where this issue happens.

**Comment by nicksp** [comment] 2017-02-24 11:18
@gaearon Yes, this helped. Could replicate the issue. Going to prepare a PR.

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
Labels: difficulty: medium, someone is working on this
