### ISSUE TITLE
Use inside of https iframe

### ISSUE THREAD

**Issue by mikeyhew** [facebook/react-devtools#881] opened 2017-09-06 16:34 UTC
Is it possible to make react-devtools listen on https://localhost:8097 instead of http, so that it can be used inside of an https iframe?

**Comment by mikeyhew** [comment] 2017-09-13 21:05
I'd be willing to work on this, but could use some advice. What I need is a version of the react-devtools package that uses https instead of http, and wss instead of ws. Would it be better to add an option to react-devtools to change the protocol, or create a fork that just uses the secure protocols?

**Comment by mikeyhew** [comment] 2017-09-22 00:19
I've created a fork of this repo where `react-devtools` listens over https: https://github.com/mikeyhew/react-devtools/tree/https

I'm leaving this issue open in case you want to add https as an option to `react-devtools` or `react-devtools-core`

**Comment by dwbruhn** [comment] 2017-09-23 00:56
@mikeyhew awesome fork! Since issues aren't enabled on your repo, I'll respond here with some info for anyone else:

To get this to work on Safari, start the https version of react-devtools, then open https://localhost:8097 directly in Safari. Allow the certificate completely at the system level (expand "Trust" and change to Always Trust).

Then you can open your app and it will connect to the dev tools!

You'll have to repeat this process every time you start the dev tools app, since it generates a new cert at startup.

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
