### ISSUE TITLE
Minor UI issues with RN style editor

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#624] opened 2017-04-25 13:34 UTC
Go to `packages/react-devtools-core`, do `npm run build`, then go to `packages/react-devtools` and run `npm start`.

You'll see an Electron window.
Launch any React Native app using 0.43 or later.
DevTools should connect.

Now, I noticed two issues that would be nice to fix.

### Textboxes Don’t Fit

Find a `<View>` in the hierarchy. Notice how the textbox for style value wraps because it doesn’t fit in the right panel:

![screen shot 2017-04-25 at 2 28 58 pm](https://cloud.githubusercontent.com/assets/810438/25387712/b5ff2932-29c3-11e7-9272-f1747b8242b7.png)

This looks pretty confusing. Of course, you could resize the right panel, but ideally it would display normally the first time you open the window.

There are a few solutions:

* Make right pane wider by default (downside: for web it could be annoying since it obscures the tree but web version doesn’t have a style editor like this).
* Make value textboxes a bit more narrow (this might be a good solution).
* Something else I haven’t thought of (really, this is up to you and your design sense).

### Lack of Margin in Vertical Mode

We recently added a vertical mode which activates when the window gets too narrow:

![screen shot 2017-04-25 at 2 32 56 pm](https://cloud.githubusercontent.com/assets/810438/25387939/512239f4-29c4-11e7-8c83-0829fe308452.png)

As you can see, props/state panel looks okay in it, but RN style editor lacks any margins. We probably should add margins there. We might need to add padding to the whole panel content instead, so that the fix is not specific to RN style editor.

**Comment by ansumanshah** [comment] 2017-04-25 15:59
@gaearon would like to take this up

**Comment by gaearon** [comment] 2017-04-25 16:04
You got it!

**Comment by bvaughn** [comment] 2019-08-19 23:27
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:27 UTC
Labels: bug, difficulty: starter, someone is working on this
