### ISSUE TITLE
Impossible to debug firefox webextension moz-extension: pages due to strict CSP

### ISSUE THREAD

**Issue by jsmnbom** [facebook/react-devtools#922] opened 2017-10-14 20:40 UTC
## Steps to reproduce
1. Install react-devtools for firefox
2. Make a firefox webextenion that uses React on a `moz-extension:` page for example on the `option_ui` page
3. Navigate to options page either inside `about:addons` or directly via `moz-extension://{extension-id}/{option_path}`

### Expected
The react-devtools toolbar button should light up and the addon should be able to debug the page

### What actually happens
The react-devtools toolbar button does not light up and clicking on it says "This page does not appear to be using react".
This is probably since extensions are not allowed to inject scripts into other extensions' pages.
_____

## Attempted fixes
I have attempted to solve this by doing
### Manually add the `inject.js` 
1. Manually add `<script src="moz-extension://09f5232c-9e96-4640-853c-78b67560d321/build/inject.js"></script>` to the options page html

This fails due to [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src moz-extension://{my-extension-id} 'unsafe-eval'”). Source: ;(function installGlobalHook(window) {
 ....

### Manually add the `inject.js` and modify CSP
1. Manually add `<script src="moz-extension://09f5232c-9e96-4640-853c-78b67560d321/build/inject.js"></script>` to the options page html
2. Modify CSP so it allows the script to execute. I have tried everything i can think of but none of it works:
 - Adding 'unsafe-inline' to 'script-src' is not allowed
 - Adding 'moz-extension://09f5232c-9e96-4640-853c-78b67560d321' (the id of react-devtools) to 'script-src' changes nothing
- Adding pretty much anything with * in it is also not allowed

### Using the standalone `react-devtools`
1. Added `<script src="http://localhost:8097"></script>` to <head> in the options page html

This fails due to CSP problems however since `http://localhost` is an allowed script src.
### Use the standable `react-devtools` and modify CSP
1. Added `<script src="http://localhost:8097"></script>` to <head> in the options page html
2. Change `content_security_policy` in manifest.json to `script-src 'self' http://localhost:8097 object-src 'self';`

This unfortunately also doesn't work since `http:` domains are not allowed in firefox webextension CSPs
> The only permitted schemes for sources are: blob:, filesystem:, moz-extension:, and https:.
> [source](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_security_policy)

___
It is really impossible to debug these kind of pages in firefox?
As far as fixes go, the only that i can think of is either changing the `inject.js` to be more CSP compliant if possible, or using the standalone version and somehow having it use `https://localhost` instead of just `http`.

**Comment by bomjacob** [comment] 2017-10-19 11:27
I have found a temporary workaround to getting the standalone tools to work using [ngrok](https://ngrok.com/). Documenting it here for future reference and others with the same issue.

1) [Install ngrok](https://ngrok.com/download) (note you may or may not need an account - a free one is sufficient)
2) Execute `ngrok http 8097` in a terminal
3) Ngrok will output something like:
```
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://{unique_id}.ngrok.io -> localhost:8097
Forwarding                    https://{unique_id}.ngrok.io -> localhost:8097
```
4) Inside your html file for the page you would like to debug add the following before loading react (substituting `{unique_id}` with the id from ngrok):
```html
<script src="https://{unique_id}.ngrok.io"></script>
```
5) We need to allow connections to ngrok from the extension so inside `manifest.json` add (if you already have a `content_security_policy` key, you just need to add `https://*.ngrok.io` to the `script-src`-section:
``` json
"content_security_policy": "script-src 'self' https://*.ngrok.io; object-src 'self'"
```

After doing that the standalone version of react-devtools should work. Note that you'll need to do steps 2-4 everytime you close ngrok as it will give a new id.

I'm not gonna close this issue as this is only a workaround.

**Comment by paul-mesnilgrente** [comment] 2019-06-23 01:58
Did somebody find a better way to do it?

**Comment by saneyuki** [comment] 2019-08-11 13:24
I seem this may be Firefox-side problem and filed [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1573027) to their bugzilla.

**Comment by dmose** [comment] 2019-08-12 13:57
Out of curiousity, does debugging webextensions of this sort work in Chrome?

**Comment by ngyikp** [comment] 2019-08-16 20:57
For Chrome extensions, you need to [use the standalone react-devtools app](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools), inject the `<script>` tag and loosen the CSP, but it would work as Chrome does allow http://localhost:8097 in the extension CSP.

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
