### ISSUE TITLE
Illegal invocation when clicking on property that is a DOM node

### ISSUE THREAD

**Issue by hansott** [facebook/react-devtools#940] opened 2017-11-14 08:58 UTC
Related to https://github.com/facebook/react-devtools/issues/849

![screenshot 2017-11-14 09 54 15](https://user-images.githubusercontent.com/3886384/32771096-fac4f472-c921-11e7-9d06-cf30b4038b91.png)
![screenshot 2017-11-14 09 53 51](https://user-images.githubusercontent.com/3886384/32771098-faf304e8-c921-11e7-9ca7-bf612bd7a3c3.png)
![screenshot 2017-11-14 09 54 01](https://user-images.githubusercontent.com/3886384/32771097-fadbd3d6-c921-11e7-9c00-0442c49c91a0.png)

You can reproduce by having a component that has an DOM node (`HTMLAnchorElement` is the example) as property.

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
