### ISSUE TITLE
Native BigInt's cause Uncaught TypeError and crashes DevTools when stored in state.

### ISSUE THREAD

**Issue by Egrodo** [facebook/react-devtools#1252] opened 2018-12-24 04:54 UTC
Hi all, I'm working on a calculator as a personal project and I wanted to use the new BigInt because they recently hit stage 3 in TC39.

However I noticed that when I put a BigInt literal into my React state DevTools tries to serialize it and thus throws this error: 
```
VM5210 extensions::messaging:107 Uncaught TypeError: Do not know how to serialize a BigInt
    at stringify (<anonymous>)
    at PortImpl.postMessage (VM5043 extensions::messaging:107)
    at Port.publicClassPrototype.(/anonymous function) [as postMessage] (extensions::utils:138:26)
    at handleMessageFromPage (contentScript.js:24)
```

As far as I can tell this is happening because of the `$JSON.stringify` that's happening when DevTools tries to prepare a message to send between content scripts.

If I disable the extension the error goes away. From what I can gather from [this thread](https://github.com/tc39/proposal-bigint/issues/24) BigInts can't be converted to and from JSON as of now so they're not serializable. I suppose this would mean that BigInt's can't be handled natively within a Chrome extension, so there'd have to be some abstraction.

To reproduce, go to this [CodeSandbox ](https://codesandbox.io/s/v8qrr18k55)and open result in new tab. Then open React DevTools and the error should occur.

Thanks!

**Comment by bvaughn** [comment] 2019-08-19 23:08
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:08 UTC
