### ISSUE TITLE
arrow functions as members of class do not work with devtools

### ISSUE THREAD

**Issue by kiruh** [facebook/react-devtools#860] opened 2017-07-27 16:31 UTC
Here's the file in which I've added an arrow function as a member of class:
```
export default class TeamCollection extends Array {
	constructor(teamCollection) {
		super();
		this.push(...teamCollection);
	}

	getCopy = () =>
		this.map(team => ({
			...team
		}));
	...
}
```
Since I have **babel-plugin-transform-class-properties**, the function is being transpiled properly and the application works as it should.

But in the console I get error:
```
backend.js:92 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': function () {
			return _this.map(function (team) {
				return _extends({}, team);
			});
		} could not be cloned.
    at Object.send (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:92:15)
    at Bridge.flushBufferSlice (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:7291:19)
    at Bridge.flushBufferWhileIdle (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:7268:15)
```

Here's the code where I've got an error:
```
var wall = {
	listen: function listen(fn) {
		var listener = function listener(evt) {
			if (
				evt.source !== window ||
				!evt.data ||
				evt.data.source !== "react-devtools-content-script" ||
				!evt.data.payload
			) {
				return;
			}
			fn(evt.data.payload);
		};
		listeners.push(listener);
		window.addEventListener("message", listener);
	},
	send: function send(data) {
-->		window.postMessage(
			{
				source: "react-devtools-bridge",
				payload: data
			},
			"*"
		);
	}
};
```
The problem disappears when:

- I disable react-devtools
- I change my code to:

```
export default class TeamCollection extends Array {
	constructor(teamCollection) {
		super();
		this.push(...teamCollection);
	}

	getCopy() {
		return this.map(team => ({
			...team
		}));
	}
	...
}
```

**Comment by kyleramirez** [comment] 2018-04-06 21:56
I am experiencing the same issue  when extending Array

**Comment by bvaughn** [comment] 2019-08-19 23:16
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:16 UTC
