### ISSUE TITLE
Devtools throw error when expand props under __proto__

### ISSUE THREAD

**Issue by nuintun** [facebook/react-devtools#1049] opened 2018-06-18 04:12 UTC
See screenshot:

![tim 20180618120359](https://user-images.githubusercontent.com/1730277/41517838-b6cb538c-72f0-11e8-9948-7e0d7d8060ff.png)
![tim 20180618120452](https://user-images.githubusercontent.com/1730277/41517841-ba793d28-72f0-11e8-943d-b657e19b43d3.png)

**Comment by bvaughn** [comment] 2019-08-19 23:12
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:12 UTC
