### ISSUE TITLE
react devtool doesn't support react chrome extension

### ISSUE THREAD

**Issue by Nomia** [facebook/react-devtools#424] opened 2016-09-01 07:47 UTC
Hi,

I've built a chrome extension based on react. Recently , it's fairly slow when render list. I wanna have deep look at it. But, the react tab won't show up in the chrome devtool. My react version is 0.14.8. I've exposed both React and ReactDOM as global variables. 

The react tab will show when transfer my chrome extension app to a server.
Hope that you could help me

Thank you!

**Comment by ngyikp** [comment] 2016-09-01 07:49
Duplicate of https://github.com/facebook/react-devtools/issues/91

**Comment by Nomia** [comment] 2016-09-01 08:55
Sorry,

After reading that thread(#91) 3 times. I still don't understand how to fix this issue.

What should I do?
Should I hack into the react-devtool extension and inject some code, then upload a new extension?

**Comment by gaearon** [comment] 2017-02-15 20:06
Try the [standalone version](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools) of DevTools.

It should work within a Chrome extension: https://github.com/facebook/react-devtools/issues/434#issuecomment-280116615

**Closed by gaearon** 2017-02-15 20:06 UTC
