### ISSUE TITLE
Must update props for underlying native component on React Native

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-devtools#206] opened 2015-09-13 18:38 UTC
Raised in: https://github.com/facebook/react-native/issues/2557

Style updates only work on `RCTView` `RCTText` etc type nodes

**Comment by ffxsam** [comment] 2015-09-20 18:12
Just checking in, I noticed this is still an issue ("No display name"). Not a huge deal, I've just had to add `displayName: "..."` to all my components so I can identify them. Will this be fixed in the next release?

![leaderboard](https://cloud.githubusercontent.com/assets/12532733/9982203/7d39d770-5f88-11e5-8f57-858a0cc9ba16.png)

**Comment by kassens** [comment] 2015-09-21 02:50
This will be fixed when facebook/react-native@93b9329b758cde3e921b26e11ba91d9700d2a06d makes it into the release. Unfortunately, it wasn't part of react-native 0.11.0.

facebook/react-native#2905 might also be needed to invalidate the react-native transform caches.

cc @spicyj maybe we could add a react-native minor release in case the next release is longer out?

**Comment by spicyj** [comment] 2015-09-22 21:14
I think react-native releases every two weeks. Maybe we can pick that commit sooner though? (cc @ide)

**Comment by ide** [comment] 2015-09-22 22:43
Published 0.11.1 to npm with 93b9329 and #2905's cache breakers.

**Comment by ide** [comment] 2015-09-23 01:55
Had to roll back to 0.11.0 because of the way the Android code was pushed from another repo.

0.11.1 is still published to npm if you aren't doing Android work right now, or alternatively you can put react.displayName in your own .babelrc as a quick fix.

**Comment by spicyj** [comment] 2015-09-23 07:37
Also, this issue wasn't actually about display names.

**Comment by coodoo** [comment] 2015-09-23 08:01
As a side note, I did try to put `react.displayName` in `transform.js` and `.babelrc` to no avail, but upgrading to `0.11.1` did the trick.

**Comment by gaearon** [comment] 2017-02-15 17:21
I can't reproduce the issue with updating styles so assuming this is fixed now.

**Closed by gaearon** 2017-02-15 17:21 UTC
