### ISSUE TITLE
react-devtools can't use

### ISSUE THREAD

**Issue by xiaoyueyue165** [facebook/react-devtools#964] opened 2018-01-16 04:57 UTC
I use the 2015 version, open the debug element interface jump to jump, splash screen, ask for help！
The use of react website this plugin also undetectable.

Here is the animation.

![image](https://note.youdao.com/yws/public/resource/bd7f5b1de6825d4726fa47a997c1d28b/xmlnote/ECEF69E01B86469D9C12C9367FC82EDC/10587)

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
