### ISSUE TITLE
tired to use react in the chrome extension but it wont work for me.

### ISSUE THREAD

**Issue by chetanshinde118** [facebook/react-devtools#1336] opened 2019-04-22 13:27 UTC

**Comment by ngyikp** [comment] 2019-04-22 13:33
Please provide more details and steps you tried, the React Devtools itself *is* built using React, and React should work fine inside a Chrome extension.

If you're talking about not able to use React Devtools to inspect your Chrome extension, you need to run the devtools through another way: https://github.com/facebook/react-devtools/blob/master/packages/react-devtools/README.md

**Comment by bvaughn** [comment] 2019-08-19 23:05
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:05 UTC
