### ISSUE TITLE
Firefox Extension doesn't have option to "Allow access to file URLs"

### ISSUE THREAD

**Issue by safetypins** [facebook/react-devtools#1324] opened 2019-04-05 15:10 UTC
When I install the devtools extension in Firefox 66.0.2 on macOS 10.14.4 I don't see an option to "Allow access to file URLs".

**Comment by ngyikp** [comment] 2019-04-09 10:58
On my Firefox Nightly 68.0a1, the extension automatically works on file:/// with no extra setting like Chrome.

<img width="1031" alt="" src="https://user-images.githubusercontent.com/6135313/55794970-4a373780-5af9-11e9-985c-03b8204311d3.png">

**Comment by twnew** [comment] 2019-05-09 14:36
Yes, I can confirm it is not needed on Firefox for any extension. For example I use [kantu](https://a9t9.com/kantu) on all my machines, and only in Chrome is a switch available - and needed ,)

**Comment by bvaughn** [comment] 2019-08-19 23:06
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:06 UTC
