### ISSUE TITLE
[New devtools] I can't update Arrays

### ISSUE THREAD

**Issue by ghost** [facebook/react-devtools#102] opened 2015-08-03 22:56 UTC
I'm looking to add / remove items in an array in the component inspector (secondary window). This can be either in props or state, however I'm not able to change the array. I can update the properties of each object in an array however.

QoL improvement more than anything else.

**Comment by jaredly** [comment] 2015-08-03 23:17
It looks like this doesn't just apply to arrays --- it's that you can't replace a complex object (or array) with a literal.
Or am I misunderstanding?

**Comment by timrnz** [comment] 2015-08-04 01:26
Something like this

```js
//<MyComponent>
//Props or State
someArray : [ 'with', 'things' ]
```

I can't add something to the `someArray`

```js
//<MyComponent>
//Props or State
someArray : [ 'with', 'things', 'and', 'more', 'things' ]
```

Without hitting up the console and updating it directly using `$r.props.someArray.push('and');`

Which leads to, I can't add complex objects here either. (a bunch of my components are UI's driven from arrays of objects).

That said, to your point, you can't also change the types, e.g. from object or array to literal either (not that they should by good component building definitions), but no reason why we should limit that in the dev tools for quick testing in browser.

Hopefully that makes it a little clearer for you @jaredly

**Comment by jaredly** [comment] 2015-08-04 01:38
You also couldn't add things to an array in the old version, though -- right?

**Comment by timrnz** [comment] 2015-08-04 02:52
Hmm no I just tried it appears not, in that case is it possible to do in future?

I can however change it to null, boolean, string etc.

**Comment by jaredly** [comment] 2015-08-04 23:08
Yeah, we definitely flesh out the editing capabilites

**Comment by zubivan** [comment] 2017-06-05 08:18
Hey guys, I'm thinking of picking it up. Do you have any designs/ideas already on how add/remove to/from arrays should look like?

**Comment by AntonNiklasson** [comment] 2017-07-04 14:00
@zubivan Did you start working on this?

**Comment by AntonNiklasson** [comment] 2017-07-16 20:05
I would like to try and solve this. Any ideas on what kind of manipulations should be possible?

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC
Labels: difficulty: medium, enhancement, good first bug
