### ISSUE TITLE
"Copy element props" returns empty object instead of empty array

### ISSUE THREAD

**Issue by mstorus** [facebook/react-devtools#1359] opened 2019-07-08 21:51 UTC
https://02wiw.codesandbox.io/
https://codesandbox.io/s/sparkling-voice-02wiw

```jsx
const MyContext = React.createContext({});

function App() {
  return (
    <MyContext.Provider
      value={{
        foo: []
      }}
    >
      <div className="App">hello</div>
    </MyContext.Provider>
  );
}
```

I have a React context which contains a key with an empty Array as a value.
When I click "Copy element props" the result contains an empty object instead of an empty array.

Actual behavior:
"Copy element props" returns an object where the value of `foo` is `{}`

Expected behavior:
"Copy element props" returns an object where the value of `foo` is `[]`

![copy-props-empty-array](https://user-images.githubusercontent.com/1182738/60844887-85e0ac80-a18f-11e9-9c1d-9c9e0d06475c.gif)

**Comment by fanny** [comment] 2019-07-12 12:10
I think it may be related to the fact that here is made a `Object.assign({}, props);`, so when prop is `[]`, the result is `{}`

**Comment by srkchandru** [comment] 2019-07-31 09:22
Will `Array.isArray(props) ? [...props] : Object.assign({}, props)` fix this?

**Comment by bvaughn** [comment] 2019-08-19 23:04
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:04 UTC
