### ISSUE TITLE
Components are not visible properly when there is horizontal screen

### ISSUE THREAD

**Issue by abhi16z** [facebook/react-devtools#1326] opened 2019-04-10 15:31 UTC
![Screenshot 2019-04-10 at 8 57 55 PM](https://user-images.githubusercontent.com/35421798/55892290-b1291f00-5bd3-11e9-9da2-97c2be8fabda.png)

Please look at the screenshot. My eyes are hurting by trying to look at it

**Comment by abhi16z** [comment] 2019-04-13 06:35
@bvaughn kindly look into it when you have time

**Comment by bvaughn** [comment] 2019-08-19 23:06
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:06 UTC
