### ISSUE TITLE
Devtools highlight node even if it was not updated

### ISSUE THREAD

**Issue by rmuratov** [facebook/react-devtools#1254] opened 2018-12-26 08:38 UTC
Here's the [repo](https://github.com/rmuratov/react-devtools-test) with test project.

`Counter` component updates when clicking. It's highlighted as expected. But `Title` is a pure component but still highlighted. The thing is I placed the same `Title` below and it's not highlighted as it should. Then I placed `AddButton` above everything and now the top button is highlighted, but similar button at the bottom is not.

![test1](https://user-images.githubusercontent.com/4287685/50439005-61169d00-0901-11e9-9f83-5b3465071850.gif)
![test2](https://user-images.githubusercontent.com/4287685/50439006-61af3380-0901-11e9-8c97-1a113e9d343c.gif)

**Comment by carceri** [comment] 2019-01-29 10:21
Same

**Comment by herodrigues** [comment] 2019-01-30 21:04
Definitely a bug.
I thought it was related to fragments, but If you wrap all the elements using a `div`, it will highlight all elements.

![image](https://user-images.githubusercontent.com/1832537/52012360-27652300-24b9-11e9-8b85-700058c57924.png)

**Comment by marvinhagemeister** [comment] 2019-01-31 15:36
The way the highlighting seems to work is that it paints a border around the component `setState/forcUpdate` (and the direct children) it was called on. In the linked example this is the `App` component which has to traverse down the tree and check if each component needs to be updated. In other words: it doesn't reflect actual mutations to the DOM, but rather the children that need to be checked.

Moving the state into the `Counter` component fixes this and just draws a box around `Counter` as one would expect.

**Comment by rmuratov** [comment] 2019-01-31 19:15
@marvinhagemeister  Did you notice the top button on the second gif? It is being highlighted. I'm not talking about DOM, but what it says to developer this highlighted button which is pure component and doesn't rely on state? I understand that this button is a child of stateful component whose state changes over time, but what about this button's siblings, two Titles? Why they are not highlighted? I admit that I could understand something wrong, but this behavior is confusing.

**Comment by marvinhagemeister** [comment] 2019-01-31 20:52
@rmuratov You're right, I somehow missed the first title. That looks indeed like a bug :+1:

**Comment by bvaughn** [comment] 2019-08-19 23:08
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:08 UTC
