### ISSUE TITLE
Followup Work for Iterable Support

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#608] opened 2017-04-19 15:51 UTC
@cmmcleod sent an amazing PR for supporting iterables (including Immutable.js) in https://github.com/facebook/react-devtools/pull/459.

There’s a few remaining things which would be nice to investigate:

* We should provide a way to “load more” if there are too many items in the iterable. The arbitrary 100 item limit is a bit confusing.
* It shouldn’t be possible to edit things inside key-value pairs. Currently editing a fake “array” of key and value throws.
* Perhaps we can format key-value pairs differently? I know we bikeshedded on this in https://github.com/facebook/react-devtools/pull/459 but I wonder if all that’s necessary is to replace an array-like display with a dedicated “Key:” and “Value:” labels, and maybe change “Array” in this case to “Iterable” or something like that.

**Comment by gaearon** [comment] 2017-04-21 08:48
The last one sounds like something we'd want for arrays too.

**Comment by gaearon** [comment] 2017-04-21 08:50
In particular I think we should respect "two level dehydration" rule for both iterables and arrays according to how they're displayed in the UI. Arrays are already grouped into buckets of 100 items (if I'm not mistaken). Like in chrome. So we should make this work on dehydration side: send a list of those buckets instead of actual array if it's so large, and then load more as requested. This could dramatically improve startup performance too.

**Comment by gaearon** [comment] 2017-04-30 11:33
Friendly ping to @cmmcleod, do you still intend to work on this?

**Comment by shriah** [comment] 2017-04-30 12:50
> Arrays are already grouped into buckets of 100 items (if I'm not mistaken). Like in chrome.
I just tested this and arrays not grouped into buckets.
<img width="554" alt="screen shot 2017-04-30 at 6 18 12 pm" src="https://cloud.githubusercontent.com/assets/3917104/25564467/8586721c-2dd1-11e7-8fbe-5fad081d4e62.png">

**Comment by gaearon** [comment] 2017-04-30 14:38
Thanks for checking. Then we need to implement this for both. Would solve https://github.com/facebook/react-devtools/issues/599 too!

**Comment by shriah** [comment] 2017-04-30 14:44
I also found a small bug here 
https://github.com/facebook/react-devtools/blob/90b8b257ae659c7dbf759e3a3feeb561e6863f4a/agent/dehydrate.js#L38
It should be 
`if ( typeof data[Symbol.iterator] === 'function') {`
 because of which it was possible to edit the iterable objects.

**Comment by shriah** [comment] 2017-04-30 14:48
I also think we should refactor `Bridge.js` and move this code to `dehydrate.js` 

https://github.com/facebook/react-devtools/blob/90b8b257ae659c7dbf759e3a3feeb561e6863f4a/agent/Bridge.js#L410-L422

**Comment by bvaughn** [comment] 2019-08-19 23:27
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:27 UTC
Labels: difficulty: complex, good first bug
