### ISSUE TITLE
Feature request: reserved area to display more specific information for a given component class

### ISSUE THREAD

**Issue by gre** [facebook/react-devtools#219] opened 2015-09-21 20:54 UTC
This is how props are currently displayed on the right panel:

<img width="925" alt="screen shot 2015-09-21 at 22 35 09" src="https://cloud.githubusercontent.com/assets/211411/10004254/11c3887c-60b1-11e5-8581-6154161cdef6.png">

I think it's great, but it would be neat to allow a custom tab that can be refined by library implementers and that would visualize anything more specific and useful for a given component.

It would be great to have react-devtools "extensible" to support this easily (just each component class have a reserved area that it can render into).

I think this feature could improve the DX, a component library is likely to know better than a generic implementation how to render its specific props.

**Comment by spicyj** [comment] 2015-09-21 22:31
Yeah, we would like to add some sort of generic plugin support but we haven't figured out exactly how that would work.

**Comment by jaredly** [comment] 2015-09-24 18:19
@gre do you have thoughts about how this would be best done? My current thought is that plugins would live in this repo, and show up only when the library is present on the page, see #200 which adds a Relay Plugin

**Comment by bvaughn** [comment] 2019-08-19 23:30
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:30 UTC

**Comment by gre** [comment] 2019-08-20 02:15
awesome @bvaughn ! 👏
