### ISSUE TITLE
invalid style property values break running app instance

### ISSUE THREAD

**Issue by aloifolia** [facebook/react-devtools#879] opened 2017-09-01 17:41 UTC
I just got started with React Native development and, thus, react devtools. I noticed that you can change the styles of components. However, if you insert invalid values, this seems to break the react native process altogether and you have to restart it. Would it be possible to restrict the input to valid values only and prohibit the user from accidentally opening Pandora's box? Also, something like an autocomplete feature would be really helpful.

**Comment by bvaughn** [comment] 2017-09-01 17:47
Hey @aloifolia 😄  This sounds like a good idea, but one we're already tracking at #800. If you'd be interested in helping out, let's chat on that issue!

Closing as a duplicate of #800

**Closed by bvaughn** 2017-09-01 17:47 UTC
