### ISSUE TITLE
Hotkey for "Select a React element in the page to inspect it" in Chrome extension

### ISSUE THREAD

**Issue by k1sul1** [facebook/react-devtools#966] opened 2018-01-16 10:23 UTC
The "Select an element in the page to inspect it" button on the top of the devtools has the hotkey <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd>, and this is arguably the feature I use the most.

When in React tab of devtools, right under this button  is a "Select a React element in the page to inspect it" button, but it seems to lack a hotkey, or at least a label telling what the hotkey is. The button is tiny, and I'm having trouble hitting it with the mouse, hence I'd like a hotkey.

![image](https://user-images.githubusercontent.com/2719615/34980242-8a539588-faac-11e7-8581-4350f26d689e.png)

**Comment by concerned3rdparty** [comment] 2018-08-12 15:15
this button does not work. it worked for the first time but i could not jump from ui to component in react dev tools .

**Comment by kasperpeulen** [comment] 2019-03-28 10:38
Any progress on this?

**Comment by fasterthan** [comment] 2019-08-02 20:03
I **just** found out that React Dev Tools' "compass" icon was the same as Chrome Dev Tools' "Select an element to inspect".

A tooltip would be helpful.

**Comment by bvaughn** [comment] 2019-08-19 23:14
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:14 UTC
