### ISSUE TITLE
Expose a way to refresh search with a single click in the UI

### ISSUE THREAD

**Issue by blord-fullscreen** [facebook/react-devtools#742] opened 2017-05-25 17:44 UTC
To reproduce:

1) Load a page, and search for a Component. Cool, it's there in the inspector.
2) Interact with the page in some way that either removes that Component, or creates more instances of that component.
3) Ok, now I want to see the current state in the inspector. To do this, I currently have to do something like:

- focus the search field.
- delete a character from the end of the search entry
- optionally retype the last character of my search term

IMHO That's three clicks/keys that should be just one. Minor, but it *really* adds up. Here are three options I can think of:

a) Refresh inspector whenever the search field acquires focus. This has the advantage of not introducing any new UI. On the downside, refresh-on-focus isn't a well established convention.

b) Expose a circular arrow "refresh" button to the left of the search input. Very similar to the circular arrow to the left of the URL bar in Chrome. The button would be borderless, as in Chrome. This has the advantage of being obvious and highly discoverable, and following browser UI convention. Downside is it adds UI clutter. This is my personal preference. Like this:

![quick-react-refresh-comp](https://cloud.githubusercontent.com/assets/27975206/26462779/f1a5e5a4-4136-11e7-80bd-2f713fa6eb14.png)

c) Use the magnifying glass icon within the search input as a "refresh" button. This might take some fancy footwork. Advantage is no new UI clutter. Downside is it's not a common convention.

Thanks for considering. If I'm just missing something obvious please point it out :)

**Comment by gaearon** [comment] 2017-05-26 18:28
Ideally the search should just update automatically if new matching components are mounting. Not sure how hard or performant it would be but please feel free to explore!

**Comment by blord-fullscreen** [comment] 2017-05-26 18:37
Totally agree in principle. But that sounds like a huge undertaking, and I suspect there would be perf concerns.

Just for reference, string searches in the Chrome Elements Inspector do not autorefresh results on arbitrary DOM changes. You have to do the same rigmarole of retyping part of the search term in the inspector. So the current RDT behavior does align with Elements. It just stinks.

**Comment by clintjansen** [comment] 2017-05-29 14:28
Really looking forward to such a feature! It's quite a hassle working on one component and manually refreshing it by typing into the search field.

**Comment by bvaughn** [comment] 2019-08-19 23:24
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:24 UTC
