### ISSUE TITLE
Memo components that are not on the fast path show up as two components

### ISSUE THREAD

**Issue by Jessidhia** [facebook/react-devtools#1283] opened 2019-01-22 12:31 UTC
```jsx
const SimpleMemoComponent = React.memo(function Component() { return null })
const MemoComponent = React.memo(function Component() { return null }, () => true)
```

These two components show up differently in the dev tools tree. It might be useful to show that the component with a comparison function is outside the fast path, but that could maybe be done as a marker in the sidebar instead of in the tree itself.

To clarify, the `SimpleMemoComponent` above shows up as a single tree element: `<Memo(Component)></Memo(Component)>`. The `MemoComponent` shows up as `<Memo><Component></Component></Memo>`.

**Comment by Jessidhia** [comment] 2019-01-22 12:38
Another possible trick is to just have something in the generated name to indicate it isn't the common case. For example (done by making my own `.displayName`):

![image](https://user-images.githubusercontent.com/73085/51536116-d7210c00-1e8d-11e9-847a-f43b6956ae58.png)

but this still runs into the problem of having to know that the parent/child fibers are intrinsically related.

**Comment by bvaughn** [comment] 2019-08-19 23:06
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:06 UTC
