### ISSUE TITLE
Document how to self-diagnose unminified/development build results

### ISSUE THREAD

**Issue by ngyikp** [facebook/react-devtools#692] opened 2017-05-06 04:00 UTC
Many new bug reports are related to the detection of unminified/development builds and surprised at the results. It would be great to have a document on how to self-diagnose this and confirm the results.

I made a demo test suite with various conditions: https://github.com/ngyikp/react-devtools-minification-diagnosis

**Diagnosis:**

1. Temporarily turn off JavaScript source maps or else you might see confusing results
    1. Top-right three grey dots on the inspector > Settings
    2. At the Sources section, untick "Enable JavaScript source maps"
2. Run `window.__REACT_DEVTOOLS_GLOBAL_HOOK__._renderers` in the console
3. [Ensure there is only one renderer](https://rawgit.com/ngyikp/react-devtools-minification-diagnosis/master/duplicate/index.htm), if there are more than one, then React is being loaded twice

    ~~(I think there should be another bug report open to track this edge case)~~ (bug opened, see #700)

    <img width="417" alt="" src="https://cloud.githubusercontent.com/assets/6135313/25769307/36a4fea4-3248-11e7-8ab7-55d961c4e138.png">

4. Expand the renderer and `Mount`, right-click `_renderNewRootComponent` and click Show Function Definition

    (instructions are slightly different for Fiber)

    <img width="508" alt="screen shot 2017-05-06 at 10 41 05 am" src="https://cloud.githubusercontent.com/assets/6135313/25769318/8cdeec44-3248-11e7-8242-58af66c2c4d0.png">

The ideal [minified production](https://rawgit.com/ngyikp/react-devtools-minification-diagnosis/master/production-minified/index.htm) build should look like this: (you should probably pretty print it)

<img width="459" alt="screen shot 2017-05-06 at 10 42 29 am" src="https://cloud.githubusercontent.com/assets/6135313/25769327/bc6fce10-3248-11e7-9de8-7ea36aeeb76f.png">

**Comment by gaearon** [comment] 2017-05-06 13:12
Great, I agree this is useful. Where do you think would be the best place to put it?

**Comment by chisler** [comment] 2017-05-11 17:01
Hi @ngyikp,

Thank you for the guide! One may face confusing behavior.

For example, [iamdustan.com](http://iamdustan.com/) uses React. DevTools say it's production.
However, one may be surprised following the guide by clicking "Show Function Definition":

| Console | Source |
|---|---|
| ![image](https://cloud.githubusercontent.com/assets/13795437/25961545/5572f770-3683-11e7-9f35-04cf52c7d479.png) | ![image](https://cloud.githubusercontent.com/assets/13795437/25961560/61d033e8-3683-11e7-82b3-712446d25b48.png) |

Though, if we follow Dan's way from `detectReactBuildType()` we will see why DevTools think it's all good.

**Input**
```
rs = window.__REACT_DEVTOOLS_GLOBAL_HOOK__._renderers
Object.keys(rs).map(key => Function.prototype.toString.call(rs[key].Mount._renderNewRootComponent))
```

**Output**
```
["function (e,t,n,r){c(t)?void 0:h("37"),y.ensureScrollValueMonitoring();var o=E(e,!1);j.batchedUpdates(s,o,t,n,r);var a=o._instance.rootID;return N[a]=o,o}"]
```

**Comment by ngyikp** [comment] 2017-05-11 17:57
@gaearon 
Hmm, perhaps on this doc: https://facebook.github.io/react/docs/optimizing-performance.html

Write something like:
> It is expected that you use the development mode when working on your app, and the production mode when deploying your app to the users.
>
> A misconfigured build process that isn't minifying React properly can also cause the development mode warning to appear.
>
> If you're still unsure about the production/development mode results, you can verify manually with instructions at [hxxps://github.com/facebook/react-devtools/issues/692 or some doc location]

@chisler 
You have JavaScript source maps enabled, this is what I get when I disable source maps:

<img width="365" alt="screen shot 2017-05-12 at 1 36 11 am" src="https://cloud.githubusercontent.com/assets/6135313/25963309/6890819e-36b3-11e7-83aa-a6f8bdc10fa2.png">

<img width="246" alt="screen shot 2017-05-12 at 1 35 24 am" src="https://cloud.githubusercontent.com/assets/6135313/25963284/56202992-36b3-11e7-89b1-67d89f651402.png">
(that "Source Map detected" notice disappears when pretty-print is clicked, heh)

>

In this case, React Dev Tools _is_ correct about production mode and Chrome devtools is being misleading, I'll update my first comment to mention disabling source maps temporarily.

**Comment by chisler** [comment] 2017-05-11 18:56
Thanks for the good spot! It's great that guide is updated.

**Comment by bvaughn** [comment] 2019-08-19 23:28
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:28 UTC
