### ISSUE TITLE
Problems to show Hooks State in Chrome

### ISSUE THREAD

**Issue by apenab** [facebook/react-devtools#1301] opened 2019-02-10 15:54 UTC
Chrome Version => 72.0
React developers Tools => 3.6.0
Does not show the state, only showing this notation and  when I touch not pass nothing
![image](https://user-images.githubusercontent.com/22795807/52535877-acee9b80-2d21-11e9-902f-aa36bf577787.png)

**Comment by mgol** [comment] 2019-02-10 22:19
@apenab Since it looks like a duplicate of #1282, can you close this issue?

**Closed** 2019-02-11 14:31 UTC
