### ISSUE TITLE
Search UI Followup Work

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#643] opened 2017-04-28 10:59 UTC
Spillover from https://github.com/facebook/react-devtools/pull/641.

- [ ] Only search at word boundaries (see related PR #664)
- [ ] Debounce the input
- [ ] Perhaps, improve the ranking algorithm
- [ ] When resizing the window, there are several jumps (search bar jumps on second line -> search bar jumps back on first line, but split window layout changes -> search bar jumps on second line again). Would be great to make this less jumpy somehow.

Tentatively assigned to @bvaughn since he drove this effort.

**Comment by bvaughn** [comment] 2019-08-19 23:27
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:27 UTC
Labels: enhancement
