### ISSUE TITLE
i  open  npm run devtools but not use 

### ISSUE THREAD

**Issue by yehoan** [facebook/react-devtools#1317] opened 2019-03-20 12:17 UTC
![image](https://user-images.githubusercontent.com/22631753/54683539-db476e00-4b4c-11e9-923e-64980f5de977.png)
i  use npm run devtools  
![image](https://user-images.githubusercontent.com/22631753/54683579-ee5a3e00-4b4c-11e9-850a-0620d08da413.png)
and  i  also  use  expo  this frame  so  i  not  know  why  and  i  same  use  expo start    but  not use  so  i need  help

**Comment by bvaughn** [comment] 2019-08-19 23:08
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:08 UTC
