### ISSUE TITLE
Sparse arrays display "null" for missing indices

### ISSUE THREAD

**Issue by m-kondrateva-parc** [facebook/react-devtools#349] opened 2016-03-19 14:36 UTC
Hi,

Undefined array elements are shown as `null` in `React Dev Tool` chrome extension and it may be misleading when debugging.

Please refer to my test case:

I have array `units` with defined 1,2,3 and 1000 elements. Rest of the elements are `undefined`.
When I check state of Array with console:

``` javascript
$r.props.units
```

I get following:

```
Array[1001]

0: Object
1: Object
2: Object
1000: Object
length: 1001
__proto__: Array[0]
```

Ok, double-checking:

``` javascript
$r.props.units[5]
```

is `undefined`.
With `React Dev Tool` chrome extension I get `null` instead of `undefined`:

![alt text](http://snag.gy/553ob.jpg)

**Comment by jaredly** [comment] 2016-03-19 20:09
yeah, so we don't currently support sparse arrays.
two options here.
1) don't use sparse arrays :) I find them a bit of an anti-pattern, and your use case would probably be just as well served by using an object here. If you don't want a list of things, but rather a mapping of numbers to values, use an object.
2) change devtools to support sparse arrays :) I imagine the only thing needed would be to switch somewhere from a `for (var i=0; i<arr.length; i++)` to an `arr.forEach(`.

If you want to investigate 2, let me know and I can give you some pointers.

**Comment by 102** [comment] 2017-02-16 18:01
![selection_002](https://cloud.githubusercontent.com/assets/5839225/23033931/238d2198-f4a4-11e6-9eb9-5cbe4a462036.png)

Can't reproduce it: `undefined` items are just omitted

**Comment by tomaszlakomygp** [comment] 2017-02-16 22:45
I've created a PR for this issue although I'm not entirely sure which one is the "correct" approach - whether the `undefined` items should be omitted or not.

**Comment by gaearon** [comment] 2017-02-16 23:16
Unlabeling since there's an open PR: https://github.com/facebook/react-devtools/pull/536.

**Comment by gaearon** [comment] 2017-04-21 13:43
This was fixed in https://github.com/facebook/react-devtools/pull/536.

**Closed by gaearon** 2017-04-21 13:43 UTC
Labels: someone is working on this
