### ISSUE TITLE
Update Syntax Highlighting in Firefox Quantum (v57.0)

### ISSUE THREAD

**Issue by rhysforyou** [facebook/react-devtools#901] opened 2017-09-28 00:30 UTC
The latest Firefox beta includes an updated appearance for the developer tools, including a new syntax theme. It'd be nice to update the React Developer tools to be consistent with that. Here's an example of what the HTML inspector looks like:

<img width="994" alt="screen shot 2017-09-28 at 10 16 03 am" src="https://user-images.githubusercontent.com/320910/30943713-29e277cc-a436-11e7-9fa9-e1c1e1bee48d.png">

and the JavaScript debugger

<img width="588" alt="screen shot 2017-09-28 at 10 17 09 am" src="https://user-images.githubusercontent.com/320910/30943728-42808e36-a436-11e7-8858-2fa6b7fa9b4f.png">

There's also a fairly in depth post over [on the Nightly Blog](https://blog.nightly.mozilla.org/2017/09/11/developer-tools-visual-refresh-coming-to-nightly/) which includes a very handy image of the new color palette.

**Comment by clarkbw** [comment] 2017-09-28 07:03
Maybe @digitarald knows someone who could tackle this. 😀

**Comment by Acid-Crash** [comment] 2019-03-27 15:16
Hi, are there any updates on this?

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
