### ISSUE TITLE
 Firefox blocks React dev addon when CSP set, regardless of what is whitelisted.

### ISSUE THREAD

**Issue by DDR0** [facebook/react-devtools#460] opened 2016-12-01 18:54 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Firefox blocks the dev addon with the message:
```
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://localhost:8002 'unsafe-eval' data: https://maps.googleapis.com https://www.google-analytics.com https://unpkg.com"). echopay:1:0
"Download the React DevTools for a better development experience: https://fb.me/react-devtools" react.15.3.2.js:6909:9
```
Despite my csp section being:
```
script-src 'self' 'unsafe-eval' data: https://maps.googleapis.com https://www.google-analytics.com https://unpkg.com;
```
(I believe that `'self'` is being subbed in with `http://localhost:8002` by Firefox 45.3, since the same CSP setting works in Chromium 53.0. When the addon tries to load, it loads from `'self'` as opposed to `http://localhost:8002`. `'self'` shows up in the policy when I look at the headers themselves on a request, which tells me I got the CSP serving correctly to FF.)

React will start up in the dev tools, but it will never connect to my react web app. (It just says "Looking for React...")

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
Install the Firefox React dev plugin and visit http://24.85.23.206:8002/admin-panel, if I've left my development machine running. Note the CSP violation in the dev console.

**What is the expected behavior?**
The addon should work if `self` is an allowed script-src. Indeed, it _should_ work whatever my CSP is.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React plugin 0.15.3 (from https://addons.mozilla.org/en-US/firefox/addon/react-devtools/)
Firefox 45.3 is affected.
OS: Debian 8

**Comment by ngyikp** [comment] 2016-12-02 13:12
Try adding `'unsafe-inline'` for `script-src`, the problem is the extension tries to [inject an inline script](https://github.com/facebook/react-devtools/blob/master/shells/firefox/src/GlobalHook.js) but it is denied by CSP.

Or you could try the [Electron app](https://github.com/facebook/react-devtools/tree/master/shells/electron) as a workaround.

**Comment by DDR0** [comment] 2017-01-26 02:27
Thanks. I can't develop with `unsafe-inline` on consistently, though, as I'm not willing to enable it in production just for the react dev tools. I don't want to end up missing some inline piece of script in dev, only to eventually catch it in staging. (The dev tools do work in Chromium, so I'll just use them there for now.)

**Comment by gaearon** [comment] 2017-02-15 19:34
Is this something you could file with Firefox? I'm not sure what the actionable takeaway is for us.

**Comment by gaearon** [comment] 2017-04-21 13:23
Closing for lack of information. If you’re interested in fixing this, please contribute!

**Closed** 2017-04-21 13:22 UTC

**Comment by julienw** [comment] 2018-03-01 10:46
Related bugzilla issues:
https://bugzilla.mozilla.org/show_bug.cgi?id=1267027
https://bugzilla.mozilla.org/show_bug.cgi?id=1294996

**Comment by CamJN** [comment] 2018-06-15 00:05
I have a suggestion for how to make this a bit nicer for those affected, though I'm not a CSP expert so if this won't work hopefully someone will correct me. You could add a nonce to the injected `<script>` tag and mention it in the readme. Then people could add that nonce to their CSP, which would enable the addon, while allowing them to develop with CSP enabled.

**Comment by DDR0** [comment] 2018-06-15 01:53
Oh, I didn't think of that! That would be a great workaround here.

**Comment by CamJN** [comment] 2018-06-18 16:15
@gaearon thoughts?

**Comment by julienw** [comment] 2018-06-19 15:54
I believe this defeats the purpose: because then the nonce would be fixed, and so any malicious script could use this known nonce to be accepted by the CSP policy.

The nonce needs to be unique for each request. I don't think we can use this technique here.

What _can_ be used though, is using the injected script's hash. Obviously the caveat is the hash can/will change with each version.

The only long-term fix is to fix it in Firefox. I see there is movement in [bug 965637](https://bugzilla.mozilla.org/show_bug.cgi?id=965637) which from what I understand is the right path.

**Comment by CamJN** [comment] 2018-06-19 16:03
Yeah the nonce couldn't be part of the prod CSP, but allowing one extra script in dev would let you catch any other problems with your CSP, instead of disabling it altogether.

Waiting on Mozilla to change that policy is a pretty hard pill to swallow given it could take an arbitrarily long amount of time, and could be rejected altogether under the policy of protecting the user from themselves. I've had other requests closed or abandoned for that reason.
