### ISSUE TITLE
"Show X source" doesn't show anything

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react-devtools#773] opened 2017-06-01 17:29 UTC
In some cases if the source tab hasn't loaded yet or something, nothing will happen when you click "Show source" on a component.

Repo:

Goto http://isfiberreadyyet.com/
Open devtools without first opening the source tab.
Right click the root and click "Show t source".
Nothing happens.

**Comment by bvaughn** [comment] 2017-06-01 18:47
Thanks for filing this, Seb!

Picked it up for a quick look in case it was a recent, themes-related regression. I'm pretty sure that isn't the case. It doesn't look like we expose to the devtools whether or not source _can_ be shown. We just inject a function that tries and fails without throwing if it can't.

I'm not sure how we should know ahead of time whether it's okay to inspect. The [reference docs](https://developers.google.com/web/tools/chrome-devtools/console/command-line-reference#inspect) don't mention anything that I can see about enabled/active state.

**Comment by bvaughn** [comment] 2017-06-01 19:33
As for the repro steps, I think it's a matter of timing. If you wait a few seconds (5 or more) then it works fine. If you click right away, it fails (silently).

**Comment by bvaughn** [comment] 2017-06-01 19:34
Maybe a reasonable compromise fix would be to add the capability of showing some kind of toast-style temporary notification, and in this case, just inform the user that they might want to try again in a few seconds (if it fails). Not sure...

**Comment by sebmarkbage** [comment] 2017-06-01 19:38
There's a way to get notified when the React tab gets visible again right?

We can always show the error message (perhaps after a timeout), then hide it when the React tab gets visible again. That way if it switches tabs it won't be visible and it will be gone by the time you switch back to the React tab.

**Comment by bvaughn** [comment] 2017-06-01 19:40
Hm. Maybe. We'd need to add some sort of mechanism for showing that sort of error/notification to devtools though. Could be useful in other cases also (eg to notify a user that something has been added to their clipboard after the context copy-name option)

**Comment by gaearon** [comment] 2017-06-02 14:14
It works for me. 😕

**Comment by gaearon** [comment] 2017-06-02 14:17
Meaning, I can’t repro this even if I do it as fast as I can.

**Comment by bvaughn** [comment] 2017-06-02 14:42
Interesting. I can repro but only if I click in the first second or two.

**Comment by bvaughn** [comment] 2019-08-19 23:24
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:24 UTC
Labels: bug
