### ISSUE TITLE
DevTools do not showing: Uncaught DOMException: Failed to execute 'postMessage' on 'Window'

### ISSUE THREAD

**Issue by trungdq88** [facebook/react-devtools#902] opened 2017-09-28 03:28 UTC
Some pages on my app cause this error, the DevTools become totally unusable. I'm really not sure how to provide you more information to debug this other than these screenshots. Please help.

![image](https://user-images.githubusercontent.com/4214509/30948017-54bcecba-a437-11e7-8f76-7f1c8b5b5335.png)

![image](https://user-images.githubusercontent.com/4214509/30948005-3dfb97e2-a437-11e7-88dd-862a79874fbb.png)

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
