### ISSUE TITLE
Update code to latest Flow version and fix violations

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#581] opened 2017-03-08 22:17 UTC
We are an a very old version of Flow. I’d appreciate if somebody could update the version and then go through all violations, either fixing the code or adding suppressions where reasonable.

**Comment by tomaszlakomygp** [comment] 2017-03-09 21:24
I'm on it 👍

**Comment by gaearon** [comment] 2017-03-09 21:25
Sounds good. It won’t be a lot of fun but I bet you’ll learn something. 😄

**Comment by gaearon** [comment] 2017-03-09 21:26
You’ll need to bump the version both in `.flowconfig` and `package.json`.

**Comment by tomaszlakomygp** [comment] 2017-03-09 21:26
```
... 37 more errors (only 50 out of 87 errors displayed)
To see all errors, re-run Flow with --show-all-errors
```

What have I gotten myself into 😭

**Comment by tomaszlakomygp** [comment] 2017-03-09 21:29
I better dig into the documentation first 👍

**Comment by gaearon** [comment] 2017-03-09 21:40
One important thing to keep in mind is that an error usually has two sides in Flow. Either something is annotated (or inferred) incorrectly, or used incorrectly. So fixing one fixes the other, but you need to decide which side is wrong. Explicitly annotating things sometimes helps to discover where inference produced something you didn’t expect.

**Comment by tomaszlakomygp** [comment] 2017-03-09 21:42
I got a case like that right from the start:
```
if (!this.ids.has(element)) {
      this.ids.set(element, guid());
      this.reactElements.set(this.ids.get(element), element);
    }
```

`reactElements` is defined as `reactElements: Map<ElementID, OpaqueNodeHandle>;` and flow throws an error because it is not aware that `this.ids.set(element, guid());`will set a value and we will not try to amend the `Map` with an `undefined` key

**Comment by tomaszlakomygp** [comment] 2017-03-09 21:46
Could you tell me if this is the proper approach in this case before I dig in to apply fixes for ~80 errors?

```
getId(element: OpaqueNodeHandle): ElementID {
    if (typeof element !== 'object' || !element) {
      return element;
    }
    if (!this.ids.has(element)) {
      this.ids.set(element, guid());
      // $FlowIssue flow is not aware that the line above ^ will set the value to this.ids
      this.reactElements.set(this.ids.get(element), element);
    }
      // $FlowIssue same as above, this will be always defined
    return this.ids.get(element);
  }
```

**Comment by gaearon** [comment] 2017-03-09 21:46
Remove indirection helps.

```js
const id = guid();
this.ids.set(element, id);
this.reactElements.set(id, element);
```

**Comment by gaearon** [comment] 2017-03-09 21:48
In case of return, you could add an explicit check, e.g.
```js
const id = this.ids.get(element);
if (typeof id !== 'string') {
  throw new Error('Expected ID to exist.');
}
return id;
```

This way you can “prove” to Flow that this is safe.

**Comment by tomaszlakomygp** [comment] 2017-03-09 21:49
But what if the `element` key already has an id? I was under the impression that the `if` statement is for ensuring that this will not be overwritten.

BTW: How do I enable syntax colors on github? 😄

**Comment by tomaszlakomygp** [comment] 2017-03-09 21:49
Fair enough, explicit checks sounds good - that way both flow and maintainer will be aware that something went wrong.

**Comment by gaearon** [comment] 2017-03-09 21:52
Write ```js for colors.

**Comment by tomaszlakomygp** [comment] 2017-03-09 21:53
Allright, wish me luck - I'll let you know when I'll have the PR ready. Thanks for all the help, much appreciated 👍

**Comment by gaearon** [comment] 2017-03-09 21:53
>But what if the element key already has an id? I was under the impression that the if statement is for ensuring that this will not be overwritten.

This should work:

```js
getId(element: OpaqueNodeHandle): ElementID {
    if (typeof element !== 'object' || !element) {
      return element;
    }
    if (!this.ids.has(element)) {
      const id = guid();
      this.ids.set(element, id);
      this.reactElements.set(id, element);
      return id;
    }
    return this.ids.get(element);
  }
```

if you ensure your map is annotated.

**Comment by gaearon** [comment] 2017-03-09 21:54
Oh okay I see what you mean.
The method with catching an error should work then.

**Comment by gaearon** [comment] 2017-03-09 21:54
```js
getId(element: OpaqueNodeHandle): ElementID {
    if (typeof element !== 'object' || !element) {
      return element;
    }
    if (!this.ids.has(element)) {
      const id = guid();
      this.ids.set(element, id);
      this.reactElements.set(id, element);
      return id;
    }
    const id = this.ids.get(element);
    if (typeof id !== 'string') { // or whatever
      throw new Error('Expected ID to exist by now.');
    }
    return id;
  }
```

**Comment by tomaszlakomygp** [comment] 2017-03-25 14:47
FYI: I'm down to 36 errors but I'd need a bit of guidance regarding some event-related errors. I'll explain that in a PR which will come shortly (hopefully I'll get the time)

**Comment by tomaszlakomygp** [comment] 2017-03-25 15:50
I'm down to some quite cryptic error messages in `BananaSlugBackendManager.js` and some other so I decided to open a WIP PR so it can be reviewed in the meantime.

**Comment by gaearon** [comment] 2017-05-16 19:48
Re-adding the label since @tomaszlakomygp is not working on this.

**Comment by Rudeg** [comment] 2017-05-16 19:54
hey @gaearon, I would be happy to work on it :)

**Comment by tomaszlakomygp** [comment] 2017-05-16 19:57
@Rudeg Make sure to check out excellent comments made by @suchipi in my PR linked to this issue, unfortunately I won't be able to finish the work I started in a while due to some personal matters. Hopefully it'll be helpful :)

**Comment by mannanali413** [comment] 2017-05-16 19:58
@gaearon I can take this up

**Comment by gaearon** [comment] 2017-05-16 20:00
@Rudeg You got here first so it’s yours 👍 

Feel free to team up with @mannanali413 if you need any help!

**Comment by mannanali413** [comment] 2017-05-16 20:10
@Rudeg I will be happy to work along with you on this.

**Comment by aarondancer** [comment] 2017-05-16 21:29
Working on this rn as well. I've knocked out about half the violations so far (out of 105).

**Comment by gaearon** [comment] 2017-05-17 10:53
@aarondancer Can you please work it out with @mannanali413? He already claimed the issue so it’s not very nice to try to get there first. Ideally if you want to help, you need to coordinate with the person who claimed the issue, and maybe work on it together.

**Comment by aarondancer** [comment] 2017-05-17 13:53
Sure thing @gaearon

**Comment by gaearon** [comment] 2017-06-02 14:21
@aarondancer 

It seems like @mannanali413 and @Rudeg are busy.
Would you like to take over this, as you already started some work on it?

**Comment by aarondancer** [comment] 2017-06-03 00:56
Sure. I'll continue where I left off @gaearon

**Comment by riseremi** [comment] 2017-09-10 00:40
@aarondancer 
Any progress on the issue? Can I pick this up?

**Comment by aarondancer** [comment] 2017-09-10 00:42
Go ahead @riseremi. Feel free to take what you want from my fork. I was able to get the errors down to only 9 remaining at the time.

**Comment by riseremi** [comment] 2017-09-10 00:57
@aarondancer thank you. 👍  I'll look at your fork tomorrow.

**Comment by riseremi** [comment] 2017-09-10 15:43
@gaearon should I extract the flow types to [types.js](https://github.com/facebook/react-devtools/blob/master/frontend/types.js) or this file is supposed to contain only generic types? If types.js is for generic types only, where should I put these types?

For example, I want to extract the `Pane` type from [RelayPlugin](https://github.com/facebook/react-devtools/blob/master/plugins/Relay/RelayPlugin.js#L48) to use it in some other places:
```js
(node: Object, id: string) => React.Element<*>
```

**Comment by bvaughn** [comment] 2017-09-10 18:20
Frontend and backend `types.js` files are meant for types that are shared among many files. If you think the `Pane` type may be used by multiple components, it would be reasonable to relocate that type.

**Comment by riseremi** [comment] 2017-09-10 19:49
@bvaughn thank you, Brian.

I've submitted a PR. Please take a look when you'll have time. There are a lot of changes and workarounds just because I don't know how to do that properly. Also there are merge conflicts and I decided not to solve them by myself, since I may break something. I'll be happy to fix any issues and inaccuracies with the PR.

**Comment by bvaughn** [comment] 2019-08-19 23:29
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:29 UTC
Labels: difficulty: medium, someone is working on this
