### ISSUE TITLE
Highlight Components Styles Edited

### ISSUE THREAD

**Issue by feargswalsh92** [facebook/react-devtools#1167] opened 2018-09-24 19:29 UTC
Platform: React Native v 0.55.4
React-Devtools version: 3.2.3
#### SKIP TO FOURTH BULLET POINT FOR THE ACTUAL ISSUE,  1-3 = CONTEXT
- Hot reloading and even regular reloading uses increases RAM hugely for me so I try and use it sparingly.

-  A workaround for this for styling changes is to edit the styles in the devtools and see the effect of the changes updated live on the simulator.

- This is awesome, no complaints about that just giving context.

- However a problem with this for me personally is that I often play with styles in a trial and error fashion until I find the exact right combination. At which point I need to redo those edits in my editor It 
 would be nice if the tool gave some sort of a visual indicator so you can remember what styles you changed. 

- I know that Chrome can inject code straight into your editor but that's nontrivial, this would more than solve my problem.

- I thought that `Highlight Updates` was it, the feature may be present already too so if that's the case I would appreciate someone letting me know! Otherwise I would be open to making a PR myself to add it with some guidance on implementation.

**Comment by bvaughn** [comment] 2019-08-19 23:07
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:07 UTC
