### ISSUE TITLE
Feature: Simplified style for nodes in the tree view

### ISSUE THREAD

**Issue by hectorpla** [facebook/react-devtools#1188] opened 2018-10-15 23:43 UTC
Wouldn't it be great if there are simple style props like `flex` and `flex-direction` along with the styled `node` especially for RN? It would be much easier to debug flexbox styling. 

Currently, when a node is clicked, its styles are shown in the style editor panel. For nodes with styles referencing to a stylesheet, there is some like `style={3}` in the Props view and for nodes with inline styles, there is no 'style' key in the props.

**Comment by bvaughn** [comment] 2019-08-19 23:07
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:07 UTC
