### ISSUE TITLE
Not showing up when inspecting a popup window in chrome extension

### ISSUE THREAD

**Issue by Dharmoslap** [facebook/react-devtools#173] opened 2015-09-03 01:00 UTC
I’m building the UI of a [Popup](https://developer.chrome.com/extensions/browserAction#popups) in [Chrome Extension](https://developer.chrome.com/extensions) with React. If try to Inspect Popup, React Chrome Developer Tools are not there, though I can use them for inspecting websites.

**Comment by ngryman** [comment] 2015-11-29 19:02
Same here.

**Comment by oelmekki** [comment] 2016-01-30 17:50
Sorry for the +1 (we really need this as a core github feature), but I 
wanted to let you know I would love react-devtools to work in 
extensions as well, as I use react for all my browser actions.

I've tried to trick react-devtools into thinking it's a normal page, 
setting up `__REACT_DEVTOOLS_GLOBAL_HOOK__`, without any luck. I'm not 
even sure why it won't show up there, actually.

If this is a problem to support it in main codebase, could someone at 
least point the relevant part in code, so we can make custom builds of 
react-devtools for our needs? Thanks!

**Comment by spicyj** [comment] 2016-07-09 00:26
Dupe of #91 essentially, I think.

**Closed by spicyj** 2016-07-09 00:26 UTC
