### ISSUE TITLE
Issues with chrome dark theme developer tools

### ISSUE THREAD

**Issue by DamYeatman** [facebook/react-devtools#371] opened 2016-05-02 17:22 UTC
The react devtools don't appear to allow for a dark theme in chrome developer tools:

Example: [http://imgur.com/SlHz0W1](http://imgur.com/SlHz0W1)

**Comment by spicyj** [comment] 2016-05-02 17:27
Dupe of #108.

**Closed by spicyj** 2016-05-02 17:27 UTC
