### ISSUE TITLE
Theme dropdown in Settings on Firefox (Quantum) is unresponsive 

### ISSUE THREAD

**Issue by Manish-Giri** [facebook/react-devtools#983] opened 2018-02-07 02:36 UTC
When I click on the "settings" icon in the top left in Google Chrome, a small modal appears which has a dropdown for selecting different themes, as shown below -

![12](https://user-images.githubusercontent.com/11348778/35895391-37ba19e8-0b85-11e8-9187-3e1fa1aa8fbc.png)

The same dropdown is unresponsive on Firefox, no matter how many times you click on it -

![22](https://user-images.githubusercontent.com/11348778/35895454-79460bec-0b85-11e8-88ca-80039354fea2.png)

### Browser Versions -

- Google Chrome - Version 64.0.3282.140 (Official Build) (64-bit)
- Mozilla Firefox - 58.0.1 (64-bit)

**Comment by bvaughn** [comment] 2019-08-19 23:13
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:13 UTC
