### ISSUE TITLE
Option to hide Internal types in tree

### ISSUE THREAD

**Issue by jquense** [facebook/react-devtools#1001] opened 2018-03-21 13:44 UTC
With 16.3 there are a lot more "plumbing" types like Mode, Context, ForwardRef, etc. and as folks migrate to the new API's I think we'll see tree depth balloon, especially around Context, where (I think) the tendency will be to make lots of small ContextProviders, rather than large pass-a-big-object-bag down Providers, because it's easier to mange updates and context value equality.

This is what i'm starting to see from react-bootstrap as we try out the new apis:

![image](https://user-images.githubusercontent.com/339286/37713118-44060918-2cec-11e8-8f4c-47bf49aada11.png)

It'd be great if there was a toggle to hide these types, and maybe make it the default? I realize that seeing them is helpful in many contexts but for most folks this is plumbing of the libraries they use, it's not super important in that case that they always be visible, though the option is needed.

I'd be happy to try and take a swing at this if there is any agreement on adding it :)

**Comment by gaearon** [comment] 2018-03-23 19:00
Yeah we wanted to do something like this but never had the time. If you send a PR we'll definitely look!

**Comment by bvaughn** [comment] 2019-08-19 23:13
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:13 UTC
