### ISSUE TITLE
Console showing error: Failed to load resource when using standalone app 

### ISSUE THREAD

**Issue by pago88** [facebook/react-devtools#883] opened 2017-09-10 05:20 UTC
Using the standalone app in safari, the console always seems to shows an error that says: 
Failed to load resource: the server responded with a status of 404 (Not Found) in http://localhost:8080/backend.js.map. It shows up when the app just starts, and no matter what page I navigate to. 

The react devtools were installed as a project dependency instead of globally. It is being run by "react-devtools" as a script in the package.json file. Also, I am inserting 'react-devtools' as the first item in the entry array of my webpack configuration.

**Comment by bvaughn** [comment] 2019-08-19 23:15
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:15 UTC
