### ISSUE TITLE
Console error on Firefox "about:*" pages

### ISSUE THREAD

**Issue by jaller94** [facebook/react-devtools#1057] opened 2018-06-28 21:28 UTC
1. Install the React Dev Tools in Firefox.
2. Open the Console tab in the Dev Inspector.
3. On Urls like about:neterror or about:addons a console error appears.

`The extension "React Developer Tools" is not allowed to access about:neterror`

For me it would be ok, if the React Dev Tools are inaccessible on about:* pages.

**Comment by gaearon** [comment] 2018-07-17 01:43
Seems like something you should report to Firefox?

**Comment by jaller94** [comment] 2018-07-19 23:20
Thanks for looking into this.
I don’t have a strong opinion yet which project is responsible. 🤷‍♂️

https://bugzilla.mozilla.org/show_bug.cgi?id=1477112

**Comment by gaearon** [comment] 2018-07-20 00:00
No prob, thanks for reporting.

**Comment by garth** [comment] 2019-05-24 11:25
A very detailed response on bugzilla implies that the problem is with the extension:

> Other extensions do not use devtools.inspectedWindow.eval to detect if the current "inspected window" is an "interesting" target for the extension [...], and so they do not trigger that error message.

**Comment by bvaughn** [comment] 2019-08-19 23:11
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:11 UTC
