### ISSUE TITLE
Feature proposal - edit and manage context providers props so that they remain set after page reloads

### ISSUE THREAD

**Issue by steffencrespo** [facebook/react-devtools#1318] opened 2019-03-22 23:04 UTC
**Background**:
I am working with several context providers and in order to demonstrate the app or to quickly reproduce conditions to the business stakeholders use the React toolbar to set them with the values I want. Works like a charm, but as expected, once the browser refreshes it's all gone.

**Idea**
Inspired by chrome dev toolbar debugger (and also most debugger views I know) where I can go to the Sources tab and set a breakpoint/conditional breakpoint that remains there until I decide to remove it;

I would like to have a similar way of doing that specifically for react context providers in the React toolbar.

**It should work like this**
1. Once the page loads a Contexts tab shows all the providers;
2. I can then choose a provider and set it to have the values I want, just like I can do with the React toolbar by searching a provider (or any other component for that matter) and setting the props with the values I want;
3. All providers with changes to their props are displayed in a section of the right pane together with the edited prop values;
4. This Contexts tab gets 'paused' (same way we can deactivate all breakpoints) when the browser refreshes, so people have to manually reactivate it, thus reducing the risk of forgetting about the changes made with the toolbar and wasting time trying to debug something that is not even a problem

My initial idea was to work on it myself and submit a PR, but I've got much on my plate right now and maybe y'all already have something like that on the works.

**Comment by bvaughn** [comment] 2019-08-19 23:08
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:08 UTC
