### ISSUE TITLE
Chrome dev tools dark theme is not supported

### ISSUE THREAD

**Issue by tomaszlakomygp** [facebook/react-devtools#574] opened 2017-03-03 09:25 UTC
I just switched to dark theme in Chrome dev tools and I've noticed that it's not supported in react-devtools:

![screen shot 2017-03-03 at 10 23 23](https://cloud.githubusercontent.com/assets/16646517/23545442/a1ef7e52-fffb-11e6-98c9-f1de969efc8f.png)
![screen shot 2017-03-03 at 10 23 28](https://cloud.githubusercontent.com/assets/16646517/23545443/a1ef7e98-fffb-11e6-8803-823ed8cf573e.png)

I think it's a great starter issue for anyone who'd like to help a bit

**Comment by ngyikp** [comment] 2017-03-04 01:35
Duplicate of https://github.com/facebook/react-devtools/issues/108

**Comment by tomaszlakomygp** [comment] 2017-03-04 15:07
Fair enough, should I close this issue then?

**Comment by gaearon** [comment] 2017-03-08 22:15
Yep, thanks!

**Closed by gaearon** 2017-03-08 22:15 UTC

**Comment by gaearon** [comment] 2017-05-26 21:57
Out in the latest version.

![screen shot 2017-05-26 at 22 50 41](https://cloud.githubusercontent.com/assets/810438/26513950/72010de8-4266-11e7-8dfe-a0337d6346b1.png)
