### ISSUE TITLE
Feature Request: show which components changed during rerenders

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/react-devtools#1331] opened 2019-04-13 00:09 UTC
I'd love to have a feature in the devtools which has a dedicated tab for output of props

e.g.

---

**TodoList**: prevProps -> nextProps

---

you could click on TodoList and it'd take you to that exact component within the devtools react inspector

if you click on prevProps or nextProps it would twiddle down into a list of the props.

I'm currently dealing with optimizing useless renders for things like arrays and objects passed as props which are always unique on the next render so a feature like this would help me track down which components need optimizing a lot.

also, so its not super noisy it would be ideal to have a search feature so you could search by a component name e.g. if I type "Todo" it'd filter the list of rerenders by that name and return Todo, TodoList, etc.

**Comment by renancaldas** [comment] 2019-04-17 16:02
@lifeiscontent this tool would might help you: https://github.com/welldone-software/why-did-you-render
There is the "Highlight Updates" feature, but it would be nice having a log of rerenders as well.

I would love to see something like this as well: https://github.com/React-Sight/React-Sight

**Comment by renancaldas** [comment] 2019-04-17 16:03
@lifeiscontent  this tool would might help you: https://github.com/welldone-software/why-did-you-render
There is the "Highlight Updates" feature, but it would be nice having a log of rerenders as well.

I would love to see something like this too: https://github.com/React-Sight/React-Sight

**Comment by lifeiscontent** [comment] 2019-04-17 20:10
@renancaldas I saw that but it doesn’t have support for hooks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bvaughn** [comment] 2019-08-19 23:06
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:06 UTC
