### ISSUE TITLE
Using devtools in chrome extension

### ISSUE THREAD

**Issue by rhoman** [facebook/react-devtools#396] opened 2016-07-04 09:41 UTC
Hello,

Is there any way to use react-devtools in chrome-extension development?

Best,
Martin

**Comment by SamTharani** [comment] 2016-07-05 09:06
Hi rhoman
Refer this
https://facebook.github.io/react/blog/2015/09/02/new-react-developer-tools.html
it may be helpful to you

On Mon, Jul 4, 2016 at 3:11 PM, rhoman <notifications@github.com> wrote:

> Hello,
>
> Is there any way to use react-devtools in chrome-extension development?
>
> Best,
> Martin
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/facebook/react-devtools/issues/396>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AE7XijZJZsPxrj2DRZDbgw-3wXFZlXf-ks5qSNVKgaJpZM4JENfP>
> .
>



-- 
With regards

**Comment by spicyj** [comment] 2016-07-09 00:26
Dupe of #91, more or less.

**Closed by spicyj** 2016-07-09 00:26 UTC
