### ISSUE TITLE
Deleting a style in RN Style Editor puts it under an empty key

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#627] opened 2017-04-25 14:09 UTC
I tried deleting a style from the RN style editor by removing its key:

<img width="297" alt="screen shot 2017-04-25 at 3 07 01 pm" src="https://cloud.githubusercontent.com/assets/810438/25389578/ea3233b6-29c8-11e7-8850-130020c2cb82.png">

I would expect that the textbox pair would disappear on blur, and this particular style would be removed. However it stays, and RN complains about `''` being used as a key in the `style` object:

<img width="305" alt="screen shot 2017-04-25 at 3 07 03 pm" src="https://cloud.githubusercontent.com/assets/810438/25389606/01018f4c-29c9-11e7-82a3-92a72a56b4b8.png">

We should treat clearing the key textbox as deleting a style key on blur.

**Comment by tchaffee** [comment] 2017-04-25 16:34
Not sure how to reproduce this. Where do I find the RN style editor?

**Comment by soul-wish** [comment] 2017-04-25 16:36
@gaearon can I try to fix this?

**Comment by soul-wish** [comment] 2017-04-25 16:41
seems like @tchaffee was faster :)

**Comment by tchaffee** [comment] 2017-04-25 16:47
@soul-wish I don't even know how to reproduce this and it seems like it might be for React Native? If you have more of a clue than me, go for it.

**Comment by soul-wish** [comment] 2017-04-25 16:55
You are right, @tchaffee. As I can see the problem is in `plugins/ReactNativeStyle` module. @gaearon, correct me if I'm wrong.

**Comment by gaearon** [comment] 2017-04-25 17:37
Yes, this is for RN. I left some instructions for running RN shell here: https://github.com/facebook/react-devtools/issues/624. You can reproduce this with any RN example (for example UIExplorer in React Native repo).

**Comment by gaearon** [comment] 2017-04-25 17:37
Please sort it out between yourselves 😉 
Or let me know if you’d like to untag.

**Comment by bvaughn** [comment] 2019-08-19 23:27
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:27 UTC
Labels: bug, difficulty: starter, someone is working on this
