### ISSUE TITLE
Profiler: Commits don't load until I click around

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#1150] opened 2018-09-08 19:54 UTC
See this capture:

![no commits](https://dzwonsemrish7.cloudfront.net/items/1h0E0G3Q2b1x2e1E2s3o/Screen%20Recording%202018-09-08%20at%2008.51%20pm.gif?v=764c32bf)

Right after recording it says 1/1 commits. But I know I did more than one update. If I start clicking the flamechart, 1/1 changes to the real count. But they're still taking 100% of the width each so it's easy to miss.

**Comment by bvaughn** [comment] 2018-09-12 22:00
Huh. This is weird. What's your commit filter settings like by chance?

**Comment by gaearon** [comment] 2018-09-13 18:06
I don't think I touched them on that machine so whatever the defaults are.

**Comment by gaearon** [comment] 2018-09-14 00:38
Note this happens with *lots* of rows. I think it might have to do with data coming in in chunks or something.

**Comment by bvaughn** [comment] 2019-08-19 23:09
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:09 UTC
Labels: bug, plugin: profiler
