### ISSUE TITLE
Proposal: Dim Components with Parens in Name

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#676] opened 2017-05-03 15:57 UTC
Inspired by https://github.com/facebook/react-devtools/pull/503, I want to propose a super simple heuristic for making HOCs less prominent.

How about we just dim the components in the tree that have `(` or `)` in their names? These are always HOCs, as people commonly use `X(Y)` convention like `Connect(App)`, `Relay(FeedItem)`, or `withStyles(Button)`.  You can’t accidentally put parens into the name so it’s always intentional. HOCs that don’t adhere to this convention could easily adapt to it.

We wouldn’t completely *hide* the HOCs (at least, I’d like to start without it) because it obscures the data flow. But I think even making them dim in the tree would make a visual difference. Does anyone want to prototype this?

I don’t know if dimming will be helpful in practice or not but I’d like to experiment with it. If not, then we could add a “Hide Wrappers” checkbox that also uses `(` and `)` as a heuristic.

**Comment by mattvagni** [comment] 2017-05-03 16:32
Can I take this on? I think this could feel really nice and it seems like a good first bug to get to know how the dev tools are built.

**Comment by neeharv** [comment] 2017-05-03 16:33
I'd like to prototype something out, if no one else has started work on this. 

I like the idea of dimming it out, but I'm worried for people new to react dev tools it might look "disabled". Let me try a few styles out and send screenshots.

**Comment by gaearon** [comment] 2017-05-03 16:34
Seems like @mattvagni got there first!

**Comment by gaearon** [comment] 2017-05-03 16:35
(But seriously, feel free to prototype and collaborate. I’m not sure if this is viable, but it may work if someone figures out a good balance.)

**Comment by mattvagni** [comment] 2017-05-03 16:49
Initial impressions is that it works pretty well just dimmed out.

<img width="616" alt="screen shot 2017-05-03 at 5 44 29 pm" src="https://cloud.githubusercontent.com/assets/1372762/25671505/32844f9a-3028-11e7-9fad-7a36d799cb69.png">

However it would need some more consideration when searching:
<img width="1440" alt="screen shot 2017-05-03 at 5 48 08 pm" src="https://cloud.githubusercontent.com/assets/1372762/25671657/b98c96aa-3028-11e7-8b5f-5f46c3598028.png">

NOTE: Currently just styling the `HigherOrderComponent` vs. doing it properly and only matching components with `()` since I haven't yet found out how to change the pretend application.

**Comment by arturmuller** [comment] 2017-05-03 22:45
I would love a "Hide Wrappers" checkbox!

**Comment by iamstarkov** [comment] 2017-05-04 21:00
related #604

**Comment by bvaughn** [comment] 2019-08-19 23:27
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools

**Closed by bvaughn** 2019-08-19 23:27 UTC
Labels: difficulty: starter, someone is working on this
